/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import contact.manager.model.CrmContact;
import contact.manager.model.CrmContactModel;
import contact.manager.model.CrmContactSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CrmContact service. Represents a row in the &quot;crm_contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CrmContactModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CrmContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmContactImpl
 * @see CrmContact
 * @see CrmContactModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CrmContactModelImpl extends BaseModelImpl<CrmContact>
	implements CrmContactModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a CRM Contact model instance should use the {@link CrmContact} interface instead.
	 */
	public static final String TABLE_NAME = "crm_contact";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "crmContactId", Types.BIGINT },
			{ "constantContactId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "prefix", Types.VARCHAR },
			{ "salutation", Types.VARCHAR },
			{ "firstName", Types.VARCHAR },
			{ "middleName", Types.VARCHAR },
			{ "lastName", Types.VARCHAR },
			{ "organization", Types.VARCHAR },
			{ "jobTitle", Types.VARCHAR },
			{ "primaryAddress1", Types.VARCHAR },
			{ "primaryAddress2", Types.VARCHAR },
			{ "primaryAddressCity", Types.VARCHAR },
			{ "primaryAddressState", Types.VARCHAR },
			{ "primaryAddressZip", Types.VARCHAR },
			{ "primaryAddressCounty", Types.VARCHAR },
			{ "primaryAddressCountry", Types.VARCHAR },
			{ "secondaryAddress1", Types.VARCHAR },
			{ "secondaryAddress2", Types.VARCHAR },
			{ "secondaryAddressCity", Types.VARCHAR },
			{ "secondaryAddressState", Types.VARCHAR },
			{ "secondaryAddressZip", Types.VARCHAR },
			{ "secondaryAddressCounty", Types.VARCHAR },
			{ "secondaryAddressCountry", Types.VARCHAR },
			{ "primaryPhone", Types.VARCHAR },
			{ "primaryPhoneExtension", Types.VARCHAR },
			{ "primaryFax", Types.VARCHAR },
			{ "primaryCell", Types.VARCHAR },
			{ "primaryEmailAddress", Types.VARCHAR },
			{ "alternateContact", Types.VARCHAR },
			{ "alternateEmail", Types.VARCHAR },
			{ "isVip", Types.BOOLEAN },
			{ "facebookId", Types.VARCHAR },
			{ "twitterHandle", Types.VARCHAR },
			{ "linkedInUrl", Types.VARCHAR },
			{ "status", Types.VARCHAR },
			{ "kioskUuid", Types.VARCHAR },
			{ "imageFileEntryId", Types.BIGINT },
			{ "tagsList", Types.VARCHAR },
			{ "groupsList", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("crmContactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("constantContactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("prefix", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("salutation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("middleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("organization", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddress1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddress2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressCity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressState", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressZip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressCounty", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressCountry", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddress1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddress2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressCity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressState", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressZip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressCounty", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressCountry", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryPhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryPhoneExtension", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryFax", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryCell", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryEmailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("alternateContact", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("alternateEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isVip", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("facebookId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("twitterHandle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkedInUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kioskUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tagsList", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupsList", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table crm_contact (uuid_ VARCHAR(75) null,crmContactId LONG not null primary key,constantContactId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,prefix VARCHAR(500) null,salutation VARCHAR(500) null,firstName VARCHAR(500) null,middleName VARCHAR(500) null,lastName VARCHAR(500) null,organization VARCHAR(500) null,jobTitle VARCHAR(500) null,primaryAddress1 VARCHAR(500) null,primaryAddress2 VARCHAR(500) null,primaryAddressCity VARCHAR(500) null,primaryAddressState VARCHAR(75) null,primaryAddressZip VARCHAR(75) null,primaryAddressCounty VARCHAR(500) null,primaryAddressCountry VARCHAR(500) null,secondaryAddress1 VARCHAR(500) null,secondaryAddress2 VARCHAR(500) null,secondaryAddressCity VARCHAR(500) null,secondaryAddressState VARCHAR(75) null,secondaryAddressZip VARCHAR(75) null,secondaryAddressCounty VARCHAR(500) null,secondaryAddressCountry VARCHAR(500) null,primaryPhone VARCHAR(75) null,primaryPhoneExtension VARCHAR(75) null,primaryFax VARCHAR(75) null,primaryCell VARCHAR(75) null,primaryEmailAddress VARCHAR(500) null,alternateContact VARCHAR(500) null,alternateEmail VARCHAR(500) null,isVip BOOLEAN,facebookId VARCHAR(500) null,twitterHandle VARCHAR(500) null,linkedInUrl VARCHAR(500) null,status VARCHAR(75) null,kioskUuid VARCHAR(75) null,imageFileEntryId LONG,tagsList TEXT null,groupsList TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table crm_contact";
	public static final String ORDER_BY_JPQL = " ORDER BY crmContact.lastName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY crm_contact.lastName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.contact.manager.model.CrmContact"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.contact.manager.model.CrmContact"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(contact.manager.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.contact.manager.model.CrmContact"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long CONSTANTCONTACTID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long ISVIP_COLUMN_BITMASK = 8L;
	public static final long PRIMARYEMAILADDRESS_COLUMN_BITMASK = 16L;
	public static final long STATUS_COLUMN_BITMASK = 32L;
	public static final long UUID_COLUMN_BITMASK = 64L;
	public static final long LASTNAME_COLUMN_BITMASK = 128L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CrmContact toModel(CrmContactSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CrmContact model = new CrmContactImpl();

		model.setUuid(soapModel.getUuid());
		model.setCrmContactId(soapModel.getCrmContactId());
		model.setConstantContactId(soapModel.getConstantContactId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPrefix(soapModel.getPrefix());
		model.setSalutation(soapModel.getSalutation());
		model.setFirstName(soapModel.getFirstName());
		model.setMiddleName(soapModel.getMiddleName());
		model.setLastName(soapModel.getLastName());
		model.setOrganization(soapModel.getOrganization());
		model.setJobTitle(soapModel.getJobTitle());
		model.setPrimaryAddress1(soapModel.getPrimaryAddress1());
		model.setPrimaryAddress2(soapModel.getPrimaryAddress2());
		model.setPrimaryAddressCity(soapModel.getPrimaryAddressCity());
		model.setPrimaryAddressState(soapModel.getPrimaryAddressState());
		model.setPrimaryAddressZip(soapModel.getPrimaryAddressZip());
		model.setPrimaryAddressCounty(soapModel.getPrimaryAddressCounty());
		model.setPrimaryAddressCountry(soapModel.getPrimaryAddressCountry());
		model.setSecondaryAddress1(soapModel.getSecondaryAddress1());
		model.setSecondaryAddress2(soapModel.getSecondaryAddress2());
		model.setSecondaryAddressCity(soapModel.getSecondaryAddressCity());
		model.setSecondaryAddressState(soapModel.getSecondaryAddressState());
		model.setSecondaryAddressZip(soapModel.getSecondaryAddressZip());
		model.setSecondaryAddressCounty(soapModel.getSecondaryAddressCounty());
		model.setSecondaryAddressCountry(soapModel.getSecondaryAddressCountry());
		model.setPrimaryPhone(soapModel.getPrimaryPhone());
		model.setPrimaryPhoneExtension(soapModel.getPrimaryPhoneExtension());
		model.setPrimaryFax(soapModel.getPrimaryFax());
		model.setPrimaryCell(soapModel.getPrimaryCell());
		model.setPrimaryEmailAddress(soapModel.getPrimaryEmailAddress());
		model.setAlternateContact(soapModel.getAlternateContact());
		model.setAlternateEmail(soapModel.getAlternateEmail());
		model.setIsVip(soapModel.getIsVip());
		model.setFacebookId(soapModel.getFacebookId());
		model.setTwitterHandle(soapModel.getTwitterHandle());
		model.setLinkedInUrl(soapModel.getLinkedInUrl());
		model.setStatus(soapModel.getStatus());
		model.setKioskUuid(soapModel.getKioskUuid());
		model.setImageFileEntryId(soapModel.getImageFileEntryId());
		model.setTagsList(soapModel.getTagsList());
		model.setGroupsList(soapModel.getGroupsList());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CrmContact> toModels(CrmContactSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CrmContact> models = new ArrayList<CrmContact>(soapModels.length);

		for (CrmContactSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_CRM_CONTACTS_GROUPS_NAME = "crm_contacts_groups";
	public static final Object[][] MAPPING_TABLE_CRM_CONTACTS_GROUPS_COLUMNS = {
			{ "companyId", Types.BIGINT },
			{ "crmContactId", Types.BIGINT },
			{ "crmGroupId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_CRM_CONTACTS_GROUPS_SQL_CREATE = "create table crm_contacts_groups (companyId LONG not null,crmContactId LONG not null,crmGroupId LONG not null,primary key (crmContactId, crmGroupId))";
	public static final boolean FINDER_CACHE_ENABLED_CRM_CONTACTS_GROUPS = GetterUtil.getBoolean(contact.manager.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.crm_contacts_groups"), true);
	public static final String MAPPING_TABLE_CRM_CONTACTS_TAGS_NAME = "crm_contacts_tags";
	public static final Object[][] MAPPING_TABLE_CRM_CONTACTS_TAGS_COLUMNS = {
			{ "companyId", Types.BIGINT },
			{ "crmContactId", Types.BIGINT },
			{ "crmTagId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_CRM_CONTACTS_TAGS_SQL_CREATE = "create table crm_contacts_tags (companyId LONG not null,crmContactId LONG not null,crmTagId LONG not null,primary key (crmContactId, crmTagId))";
	public static final boolean FINDER_CACHE_ENABLED_CRM_CONTACTS_TAGS = GetterUtil.getBoolean(contact.manager.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.crm_contacts_tags"), true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(contact.manager.service.util.ServiceProps.get(
				"lock.expiration.time.contact.manager.model.CrmContact"));

	public CrmContactModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _crmContactId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCrmContactId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _crmContactId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CrmContact.class;
	}

	@Override
	public String getModelClassName() {
		return CrmContact.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("crmContactId", getCrmContactId());
		attributes.put("constantContactId", getConstantContactId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("prefix", getPrefix());
		attributes.put("salutation", getSalutation());
		attributes.put("firstName", getFirstName());
		attributes.put("middleName", getMiddleName());
		attributes.put("lastName", getLastName());
		attributes.put("organization", getOrganization());
		attributes.put("jobTitle", getJobTitle());
		attributes.put("primaryAddress1", getPrimaryAddress1());
		attributes.put("primaryAddress2", getPrimaryAddress2());
		attributes.put("primaryAddressCity", getPrimaryAddressCity());
		attributes.put("primaryAddressState", getPrimaryAddressState());
		attributes.put("primaryAddressZip", getPrimaryAddressZip());
		attributes.put("primaryAddressCounty", getPrimaryAddressCounty());
		attributes.put("primaryAddressCountry", getPrimaryAddressCountry());
		attributes.put("secondaryAddress1", getSecondaryAddress1());
		attributes.put("secondaryAddress2", getSecondaryAddress2());
		attributes.put("secondaryAddressCity", getSecondaryAddressCity());
		attributes.put("secondaryAddressState", getSecondaryAddressState());
		attributes.put("secondaryAddressZip", getSecondaryAddressZip());
		attributes.put("secondaryAddressCounty", getSecondaryAddressCounty());
		attributes.put("secondaryAddressCountry", getSecondaryAddressCountry());
		attributes.put("primaryPhone", getPrimaryPhone());
		attributes.put("primaryPhoneExtension", getPrimaryPhoneExtension());
		attributes.put("primaryFax", getPrimaryFax());
		attributes.put("primaryCell", getPrimaryCell());
		attributes.put("primaryEmailAddress", getPrimaryEmailAddress());
		attributes.put("alternateContact", getAlternateContact());
		attributes.put("alternateEmail", getAlternateEmail());
		attributes.put("isVip", getIsVip());
		attributes.put("facebookId", getFacebookId());
		attributes.put("twitterHandle", getTwitterHandle());
		attributes.put("linkedInUrl", getLinkedInUrl());
		attributes.put("status", getStatus());
		attributes.put("kioskUuid", getKioskUuid());
		attributes.put("imageFileEntryId", getImageFileEntryId());
		attributes.put("tagsList", getTagsList());
		attributes.put("groupsList", getGroupsList());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long crmContactId = (Long)attributes.get("crmContactId");

		if (crmContactId != null) {
			setCrmContactId(crmContactId);
		}

		Long constantContactId = (Long)attributes.get("constantContactId");

		if (constantContactId != null) {
			setConstantContactId(constantContactId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String prefix = (String)attributes.get("prefix");

		if (prefix != null) {
			setPrefix(prefix);
		}

		String salutation = (String)attributes.get("salutation");

		if (salutation != null) {
			setSalutation(salutation);
		}

		String firstName = (String)attributes.get("firstName");

		if (firstName != null) {
			setFirstName(firstName);
		}

		String middleName = (String)attributes.get("middleName");

		if (middleName != null) {
			setMiddleName(middleName);
		}

		String lastName = (String)attributes.get("lastName");

		if (lastName != null) {
			setLastName(lastName);
		}

		String organization = (String)attributes.get("organization");

		if (organization != null) {
			setOrganization(organization);
		}

		String jobTitle = (String)attributes.get("jobTitle");

		if (jobTitle != null) {
			setJobTitle(jobTitle);
		}

		String primaryAddress1 = (String)attributes.get("primaryAddress1");

		if (primaryAddress1 != null) {
			setPrimaryAddress1(primaryAddress1);
		}

		String primaryAddress2 = (String)attributes.get("primaryAddress2");

		if (primaryAddress2 != null) {
			setPrimaryAddress2(primaryAddress2);
		}

		String primaryAddressCity = (String)attributes.get("primaryAddressCity");

		if (primaryAddressCity != null) {
			setPrimaryAddressCity(primaryAddressCity);
		}

		String primaryAddressState = (String)attributes.get(
				"primaryAddressState");

		if (primaryAddressState != null) {
			setPrimaryAddressState(primaryAddressState);
		}

		String primaryAddressZip = (String)attributes.get("primaryAddressZip");

		if (primaryAddressZip != null) {
			setPrimaryAddressZip(primaryAddressZip);
		}

		String primaryAddressCounty = (String)attributes.get(
				"primaryAddressCounty");

		if (primaryAddressCounty != null) {
			setPrimaryAddressCounty(primaryAddressCounty);
		}

		String primaryAddressCountry = (String)attributes.get(
				"primaryAddressCountry");

		if (primaryAddressCountry != null) {
			setPrimaryAddressCountry(primaryAddressCountry);
		}

		String secondaryAddress1 = (String)attributes.get("secondaryAddress1");

		if (secondaryAddress1 != null) {
			setSecondaryAddress1(secondaryAddress1);
		}

		String secondaryAddress2 = (String)attributes.get("secondaryAddress2");

		if (secondaryAddress2 != null) {
			setSecondaryAddress2(secondaryAddress2);
		}

		String secondaryAddressCity = (String)attributes.get(
				"secondaryAddressCity");

		if (secondaryAddressCity != null) {
			setSecondaryAddressCity(secondaryAddressCity);
		}

		String secondaryAddressState = (String)attributes.get(
				"secondaryAddressState");

		if (secondaryAddressState != null) {
			setSecondaryAddressState(secondaryAddressState);
		}

		String secondaryAddressZip = (String)attributes.get(
				"secondaryAddressZip");

		if (secondaryAddressZip != null) {
			setSecondaryAddressZip(secondaryAddressZip);
		}

		String secondaryAddressCounty = (String)attributes.get(
				"secondaryAddressCounty");

		if (secondaryAddressCounty != null) {
			setSecondaryAddressCounty(secondaryAddressCounty);
		}

		String secondaryAddressCountry = (String)attributes.get(
				"secondaryAddressCountry");

		if (secondaryAddressCountry != null) {
			setSecondaryAddressCountry(secondaryAddressCountry);
		}

		String primaryPhone = (String)attributes.get("primaryPhone");

		if (primaryPhone != null) {
			setPrimaryPhone(primaryPhone);
		}

		String primaryPhoneExtension = (String)attributes.get(
				"primaryPhoneExtension");

		if (primaryPhoneExtension != null) {
			setPrimaryPhoneExtension(primaryPhoneExtension);
		}

		String primaryFax = (String)attributes.get("primaryFax");

		if (primaryFax != null) {
			setPrimaryFax(primaryFax);
		}

		String primaryCell = (String)attributes.get("primaryCell");

		if (primaryCell != null) {
			setPrimaryCell(primaryCell);
		}

		String primaryEmailAddress = (String)attributes.get(
				"primaryEmailAddress");

		if (primaryEmailAddress != null) {
			setPrimaryEmailAddress(primaryEmailAddress);
		}

		String alternateContact = (String)attributes.get("alternateContact");

		if (alternateContact != null) {
			setAlternateContact(alternateContact);
		}

		String alternateEmail = (String)attributes.get("alternateEmail");

		if (alternateEmail != null) {
			setAlternateEmail(alternateEmail);
		}

		Boolean isVip = (Boolean)attributes.get("isVip");

		if (isVip != null) {
			setIsVip(isVip);
		}

		String facebookId = (String)attributes.get("facebookId");

		if (facebookId != null) {
			setFacebookId(facebookId);
		}

		String twitterHandle = (String)attributes.get("twitterHandle");

		if (twitterHandle != null) {
			setTwitterHandle(twitterHandle);
		}

		String linkedInUrl = (String)attributes.get("linkedInUrl");

		if (linkedInUrl != null) {
			setLinkedInUrl(linkedInUrl);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String kioskUuid = (String)attributes.get("kioskUuid");

		if (kioskUuid != null) {
			setKioskUuid(kioskUuid);
		}

		Long imageFileEntryId = (Long)attributes.get("imageFileEntryId");

		if (imageFileEntryId != null) {
			setImageFileEntryId(imageFileEntryId);
		}

		String tagsList = (String)attributes.get("tagsList");

		if (tagsList != null) {
			setTagsList(tagsList);
		}

		String groupsList = (String)attributes.get("groupsList");

		if (groupsList != null) {
			setGroupsList(groupsList);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCrmContactId() {
		return _crmContactId;
	}

	@Override
	public void setCrmContactId(long crmContactId) {
		_crmContactId = crmContactId;
	}

	@JSON
	@Override
	public long getConstantContactId() {
		return _constantContactId;
	}

	@Override
	public void setConstantContactId(long constantContactId) {
		_columnBitmask |= CONSTANTCONTACTID_COLUMN_BITMASK;

		if (!_setOriginalConstantContactId) {
			_setOriginalConstantContactId = true;

			_originalConstantContactId = _constantContactId;
		}

		_constantContactId = constantContactId;
	}

	public long getOriginalConstantContactId() {
		return _originalConstantContactId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getPrefix() {
		if (_prefix == null) {
			return StringPool.BLANK;
		}
		else {
			return _prefix;
		}
	}

	@Override
	public void setPrefix(String prefix) {
		_prefix = prefix;
	}

	@JSON
	@Override
	public String getSalutation() {
		if (_salutation == null) {
			return StringPool.BLANK;
		}
		else {
			return _salutation;
		}
	}

	@Override
	public void setSalutation(String salutation) {
		_salutation = salutation;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return StringPool.BLANK;
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@JSON
	@Override
	public String getMiddleName() {
		if (_middleName == null) {
			return StringPool.BLANK;
		}
		else {
			return _middleName;
		}
	}

	@Override
	public void setMiddleName(String middleName) {
		_middleName = middleName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_columnBitmask = -1L;

		_lastName = lastName;
	}

	@JSON
	@Override
	public String getOrganization() {
		if (_organization == null) {
			return StringPool.BLANK;
		}
		else {
			return _organization;
		}
	}

	@Override
	public void setOrganization(String organization) {
		_organization = organization;
	}

	@JSON
	@Override
	public String getJobTitle() {
		if (_jobTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _jobTitle;
		}
	}

	@Override
	public void setJobTitle(String jobTitle) {
		_jobTitle = jobTitle;
	}

	@JSON
	@Override
	public String getPrimaryAddress1() {
		if (_primaryAddress1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddress1;
		}
	}

	@Override
	public void setPrimaryAddress1(String primaryAddress1) {
		_primaryAddress1 = primaryAddress1;
	}

	@JSON
	@Override
	public String getPrimaryAddress2() {
		if (_primaryAddress2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddress2;
		}
	}

	@Override
	public void setPrimaryAddress2(String primaryAddress2) {
		_primaryAddress2 = primaryAddress2;
	}

	@JSON
	@Override
	public String getPrimaryAddressCity() {
		if (_primaryAddressCity == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressCity;
		}
	}

	@Override
	public void setPrimaryAddressCity(String primaryAddressCity) {
		_primaryAddressCity = primaryAddressCity;
	}

	@JSON
	@Override
	public String getPrimaryAddressState() {
		if (_primaryAddressState == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressState;
		}
	}

	@Override
	public void setPrimaryAddressState(String primaryAddressState) {
		_primaryAddressState = primaryAddressState;
	}

	@JSON
	@Override
	public String getPrimaryAddressZip() {
		if (_primaryAddressZip == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressZip;
		}
	}

	@Override
	public void setPrimaryAddressZip(String primaryAddressZip) {
		_primaryAddressZip = primaryAddressZip;
	}

	@JSON
	@Override
	public String getPrimaryAddressCounty() {
		if (_primaryAddressCounty == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressCounty;
		}
	}

	@Override
	public void setPrimaryAddressCounty(String primaryAddressCounty) {
		_primaryAddressCounty = primaryAddressCounty;
	}

	@JSON
	@Override
	public String getPrimaryAddressCountry() {
		if (_primaryAddressCountry == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressCountry;
		}
	}

	@Override
	public void setPrimaryAddressCountry(String primaryAddressCountry) {
		_primaryAddressCountry = primaryAddressCountry;
	}

	@JSON
	@Override
	public String getSecondaryAddress1() {
		if (_secondaryAddress1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddress1;
		}
	}

	@Override
	public void setSecondaryAddress1(String secondaryAddress1) {
		_secondaryAddress1 = secondaryAddress1;
	}

	@JSON
	@Override
	public String getSecondaryAddress2() {
		if (_secondaryAddress2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddress2;
		}
	}

	@Override
	public void setSecondaryAddress2(String secondaryAddress2) {
		_secondaryAddress2 = secondaryAddress2;
	}

	@JSON
	@Override
	public String getSecondaryAddressCity() {
		if (_secondaryAddressCity == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressCity;
		}
	}

	@Override
	public void setSecondaryAddressCity(String secondaryAddressCity) {
		_secondaryAddressCity = secondaryAddressCity;
	}

	@JSON
	@Override
	public String getSecondaryAddressState() {
		if (_secondaryAddressState == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressState;
		}
	}

	@Override
	public void setSecondaryAddressState(String secondaryAddressState) {
		_secondaryAddressState = secondaryAddressState;
	}

	@JSON
	@Override
	public String getSecondaryAddressZip() {
		if (_secondaryAddressZip == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressZip;
		}
	}

	@Override
	public void setSecondaryAddressZip(String secondaryAddressZip) {
		_secondaryAddressZip = secondaryAddressZip;
	}

	@JSON
	@Override
	public String getSecondaryAddressCounty() {
		if (_secondaryAddressCounty == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressCounty;
		}
	}

	@Override
	public void setSecondaryAddressCounty(String secondaryAddressCounty) {
		_secondaryAddressCounty = secondaryAddressCounty;
	}

	@JSON
	@Override
	public String getSecondaryAddressCountry() {
		if (_secondaryAddressCountry == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressCountry;
		}
	}

	@Override
	public void setSecondaryAddressCountry(String secondaryAddressCountry) {
		_secondaryAddressCountry = secondaryAddressCountry;
	}

	@JSON
	@Override
	public String getPrimaryPhone() {
		if (_primaryPhone == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryPhone;
		}
	}

	@Override
	public void setPrimaryPhone(String primaryPhone) {
		_primaryPhone = primaryPhone;
	}

	@JSON
	@Override
	public String getPrimaryPhoneExtension() {
		if (_primaryPhoneExtension == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryPhoneExtension;
		}
	}

	@Override
	public void setPrimaryPhoneExtension(String primaryPhoneExtension) {
		_primaryPhoneExtension = primaryPhoneExtension;
	}

	@JSON
	@Override
	public String getPrimaryFax() {
		if (_primaryFax == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryFax;
		}
	}

	@Override
	public void setPrimaryFax(String primaryFax) {
		_primaryFax = primaryFax;
	}

	@JSON
	@Override
	public String getPrimaryCell() {
		if (_primaryCell == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryCell;
		}
	}

	@Override
	public void setPrimaryCell(String primaryCell) {
		_primaryCell = primaryCell;
	}

	@JSON
	@Override
	public String getPrimaryEmailAddress() {
		if (_primaryEmailAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryEmailAddress;
		}
	}

	@Override
	public void setPrimaryEmailAddress(String primaryEmailAddress) {
		_columnBitmask |= PRIMARYEMAILADDRESS_COLUMN_BITMASK;

		if (_originalPrimaryEmailAddress == null) {
			_originalPrimaryEmailAddress = _primaryEmailAddress;
		}

		_primaryEmailAddress = primaryEmailAddress;
	}

	public String getOriginalPrimaryEmailAddress() {
		return GetterUtil.getString(_originalPrimaryEmailAddress);
	}

	@JSON
	@Override
	public String getAlternateContact() {
		if (_alternateContact == null) {
			return StringPool.BLANK;
		}
		else {
			return _alternateContact;
		}
	}

	@Override
	public void setAlternateContact(String alternateContact) {
		_alternateContact = alternateContact;
	}

	@JSON
	@Override
	public String getAlternateEmail() {
		if (_alternateEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _alternateEmail;
		}
	}

	@Override
	public void setAlternateEmail(String alternateEmail) {
		_alternateEmail = alternateEmail;
	}

	@JSON
	@Override
	public boolean getIsVip() {
		return _isVip;
	}

	@JSON
	@Override
	public boolean isIsVip() {
		return _isVip;
	}

	@Override
	public void setIsVip(boolean isVip) {
		_columnBitmask |= ISVIP_COLUMN_BITMASK;

		if (!_setOriginalIsVip) {
			_setOriginalIsVip = true;

			_originalIsVip = _isVip;
		}

		_isVip = isVip;
	}

	public boolean getOriginalIsVip() {
		return _originalIsVip;
	}

	@JSON
	@Override
	public String getFacebookId() {
		if (_facebookId == null) {
			return StringPool.BLANK;
		}
		else {
			return _facebookId;
		}
	}

	@Override
	public void setFacebookId(String facebookId) {
		_facebookId = facebookId;
	}

	@JSON
	@Override
	public String getTwitterHandle() {
		if (_twitterHandle == null) {
			return StringPool.BLANK;
		}
		else {
			return _twitterHandle;
		}
	}

	@Override
	public void setTwitterHandle(String twitterHandle) {
		_twitterHandle = twitterHandle;
	}

	@JSON
	@Override
	public String getLinkedInUrl() {
		if (_linkedInUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _linkedInUrl;
		}
	}

	@Override
	public void setLinkedInUrl(String linkedInUrl) {
		_linkedInUrl = linkedInUrl;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (_originalStatus == null) {
			_originalStatus = _status;
		}

		_status = status;
	}

	public String getOriginalStatus() {
		return GetterUtil.getString(_originalStatus);
	}

	@JSON
	@Override
	public String getKioskUuid() {
		if (_kioskUuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _kioskUuid;
		}
	}

	@Override
	public void setKioskUuid(String kioskUuid) {
		_kioskUuid = kioskUuid;
	}

	@JSON
	@Override
	public long getImageFileEntryId() {
		return _imageFileEntryId;
	}

	@Override
	public void setImageFileEntryId(long imageFileEntryId) {
		_imageFileEntryId = imageFileEntryId;
	}

	@JSON
	@Override
	public String getTagsList() {
		if (_tagsList == null) {
			return StringPool.BLANK;
		}
		else {
			return _tagsList;
		}
	}

	@Override
	public void setTagsList(String tagsList) {
		_tagsList = tagsList;
	}

	@JSON
	@Override
	public String getGroupsList() {
		if (_groupsList == null) {
			return StringPool.BLANK;
		}
		else {
			return _groupsList;
		}
	}

	@Override
	public void setGroupsList(String groupsList) {
		_groupsList = groupsList;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				CrmContact.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CrmContact.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CrmContact toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CrmContact)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CrmContactImpl crmContactImpl = new CrmContactImpl();

		crmContactImpl.setUuid(getUuid());
		crmContactImpl.setCrmContactId(getCrmContactId());
		crmContactImpl.setConstantContactId(getConstantContactId());
		crmContactImpl.setGroupId(getGroupId());
		crmContactImpl.setCompanyId(getCompanyId());
		crmContactImpl.setUserId(getUserId());
		crmContactImpl.setUserName(getUserName());
		crmContactImpl.setCreateDate(getCreateDate());
		crmContactImpl.setModifiedDate(getModifiedDate());
		crmContactImpl.setPrefix(getPrefix());
		crmContactImpl.setSalutation(getSalutation());
		crmContactImpl.setFirstName(getFirstName());
		crmContactImpl.setMiddleName(getMiddleName());
		crmContactImpl.setLastName(getLastName());
		crmContactImpl.setOrganization(getOrganization());
		crmContactImpl.setJobTitle(getJobTitle());
		crmContactImpl.setPrimaryAddress1(getPrimaryAddress1());
		crmContactImpl.setPrimaryAddress2(getPrimaryAddress2());
		crmContactImpl.setPrimaryAddressCity(getPrimaryAddressCity());
		crmContactImpl.setPrimaryAddressState(getPrimaryAddressState());
		crmContactImpl.setPrimaryAddressZip(getPrimaryAddressZip());
		crmContactImpl.setPrimaryAddressCounty(getPrimaryAddressCounty());
		crmContactImpl.setPrimaryAddressCountry(getPrimaryAddressCountry());
		crmContactImpl.setSecondaryAddress1(getSecondaryAddress1());
		crmContactImpl.setSecondaryAddress2(getSecondaryAddress2());
		crmContactImpl.setSecondaryAddressCity(getSecondaryAddressCity());
		crmContactImpl.setSecondaryAddressState(getSecondaryAddressState());
		crmContactImpl.setSecondaryAddressZip(getSecondaryAddressZip());
		crmContactImpl.setSecondaryAddressCounty(getSecondaryAddressCounty());
		crmContactImpl.setSecondaryAddressCountry(getSecondaryAddressCountry());
		crmContactImpl.setPrimaryPhone(getPrimaryPhone());
		crmContactImpl.setPrimaryPhoneExtension(getPrimaryPhoneExtension());
		crmContactImpl.setPrimaryFax(getPrimaryFax());
		crmContactImpl.setPrimaryCell(getPrimaryCell());
		crmContactImpl.setPrimaryEmailAddress(getPrimaryEmailAddress());
		crmContactImpl.setAlternateContact(getAlternateContact());
		crmContactImpl.setAlternateEmail(getAlternateEmail());
		crmContactImpl.setIsVip(getIsVip());
		crmContactImpl.setFacebookId(getFacebookId());
		crmContactImpl.setTwitterHandle(getTwitterHandle());
		crmContactImpl.setLinkedInUrl(getLinkedInUrl());
		crmContactImpl.setStatus(getStatus());
		crmContactImpl.setKioskUuid(getKioskUuid());
		crmContactImpl.setImageFileEntryId(getImageFileEntryId());
		crmContactImpl.setTagsList(getTagsList());
		crmContactImpl.setGroupsList(getGroupsList());

		crmContactImpl.resetOriginalValues();

		return crmContactImpl;
	}

	@Override
	public int compareTo(CrmContact crmContact) {
		int value = 0;

		value = getLastName().compareTo(crmContact.getLastName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CrmContact)) {
			return false;
		}

		CrmContact crmContact = (CrmContact)obj;

		long primaryKey = crmContact.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CrmContactModelImpl crmContactModelImpl = this;

		crmContactModelImpl._originalUuid = crmContactModelImpl._uuid;

		crmContactModelImpl._originalConstantContactId = crmContactModelImpl._constantContactId;

		crmContactModelImpl._setOriginalConstantContactId = false;

		crmContactModelImpl._originalGroupId = crmContactModelImpl._groupId;

		crmContactModelImpl._setOriginalGroupId = false;

		crmContactModelImpl._originalCompanyId = crmContactModelImpl._companyId;

		crmContactModelImpl._setOriginalCompanyId = false;

		crmContactModelImpl._setModifiedDate = false;

		crmContactModelImpl._originalPrimaryEmailAddress = crmContactModelImpl._primaryEmailAddress;

		crmContactModelImpl._originalIsVip = crmContactModelImpl._isVip;

		crmContactModelImpl._setOriginalIsVip = false;

		crmContactModelImpl._originalStatus = crmContactModelImpl._status;

		crmContactModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CrmContact> toCacheModel() {
		CrmContactCacheModel crmContactCacheModel = new CrmContactCacheModel();

		crmContactCacheModel.uuid = getUuid();

		String uuid = crmContactCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			crmContactCacheModel.uuid = null;
		}

		crmContactCacheModel.crmContactId = getCrmContactId();

		crmContactCacheModel.constantContactId = getConstantContactId();

		crmContactCacheModel.groupId = getGroupId();

		crmContactCacheModel.companyId = getCompanyId();

		crmContactCacheModel.userId = getUserId();

		crmContactCacheModel.userName = getUserName();

		String userName = crmContactCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			crmContactCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			crmContactCacheModel.createDate = createDate.getTime();
		}
		else {
			crmContactCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			crmContactCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			crmContactCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		crmContactCacheModel.prefix = getPrefix();

		String prefix = crmContactCacheModel.prefix;

		if ((prefix != null) && (prefix.length() == 0)) {
			crmContactCacheModel.prefix = null;
		}

		crmContactCacheModel.salutation = getSalutation();

		String salutation = crmContactCacheModel.salutation;

		if ((salutation != null) && (salutation.length() == 0)) {
			crmContactCacheModel.salutation = null;
		}

		crmContactCacheModel.firstName = getFirstName();

		String firstName = crmContactCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			crmContactCacheModel.firstName = null;
		}

		crmContactCacheModel.middleName = getMiddleName();

		String middleName = crmContactCacheModel.middleName;

		if ((middleName != null) && (middleName.length() == 0)) {
			crmContactCacheModel.middleName = null;
		}

		crmContactCacheModel.lastName = getLastName();

		String lastName = crmContactCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			crmContactCacheModel.lastName = null;
		}

		crmContactCacheModel.organization = getOrganization();

		String organization = crmContactCacheModel.organization;

		if ((organization != null) && (organization.length() == 0)) {
			crmContactCacheModel.organization = null;
		}

		crmContactCacheModel.jobTitle = getJobTitle();

		String jobTitle = crmContactCacheModel.jobTitle;

		if ((jobTitle != null) && (jobTitle.length() == 0)) {
			crmContactCacheModel.jobTitle = null;
		}

		crmContactCacheModel.primaryAddress1 = getPrimaryAddress1();

		String primaryAddress1 = crmContactCacheModel.primaryAddress1;

		if ((primaryAddress1 != null) && (primaryAddress1.length() == 0)) {
			crmContactCacheModel.primaryAddress1 = null;
		}

		crmContactCacheModel.primaryAddress2 = getPrimaryAddress2();

		String primaryAddress2 = crmContactCacheModel.primaryAddress2;

		if ((primaryAddress2 != null) && (primaryAddress2.length() == 0)) {
			crmContactCacheModel.primaryAddress2 = null;
		}

		crmContactCacheModel.primaryAddressCity = getPrimaryAddressCity();

		String primaryAddressCity = crmContactCacheModel.primaryAddressCity;

		if ((primaryAddressCity != null) && (primaryAddressCity.length() == 0)) {
			crmContactCacheModel.primaryAddressCity = null;
		}

		crmContactCacheModel.primaryAddressState = getPrimaryAddressState();

		String primaryAddressState = crmContactCacheModel.primaryAddressState;

		if ((primaryAddressState != null) &&
				(primaryAddressState.length() == 0)) {
			crmContactCacheModel.primaryAddressState = null;
		}

		crmContactCacheModel.primaryAddressZip = getPrimaryAddressZip();

		String primaryAddressZip = crmContactCacheModel.primaryAddressZip;

		if ((primaryAddressZip != null) && (primaryAddressZip.length() == 0)) {
			crmContactCacheModel.primaryAddressZip = null;
		}

		crmContactCacheModel.primaryAddressCounty = getPrimaryAddressCounty();

		String primaryAddressCounty = crmContactCacheModel.primaryAddressCounty;

		if ((primaryAddressCounty != null) &&
				(primaryAddressCounty.length() == 0)) {
			crmContactCacheModel.primaryAddressCounty = null;
		}

		crmContactCacheModel.primaryAddressCountry = getPrimaryAddressCountry();

		String primaryAddressCountry = crmContactCacheModel.primaryAddressCountry;

		if ((primaryAddressCountry != null) &&
				(primaryAddressCountry.length() == 0)) {
			crmContactCacheModel.primaryAddressCountry = null;
		}

		crmContactCacheModel.secondaryAddress1 = getSecondaryAddress1();

		String secondaryAddress1 = crmContactCacheModel.secondaryAddress1;

		if ((secondaryAddress1 != null) && (secondaryAddress1.length() == 0)) {
			crmContactCacheModel.secondaryAddress1 = null;
		}

		crmContactCacheModel.secondaryAddress2 = getSecondaryAddress2();

		String secondaryAddress2 = crmContactCacheModel.secondaryAddress2;

		if ((secondaryAddress2 != null) && (secondaryAddress2.length() == 0)) {
			crmContactCacheModel.secondaryAddress2 = null;
		}

		crmContactCacheModel.secondaryAddressCity = getSecondaryAddressCity();

		String secondaryAddressCity = crmContactCacheModel.secondaryAddressCity;

		if ((secondaryAddressCity != null) &&
				(secondaryAddressCity.length() == 0)) {
			crmContactCacheModel.secondaryAddressCity = null;
		}

		crmContactCacheModel.secondaryAddressState = getSecondaryAddressState();

		String secondaryAddressState = crmContactCacheModel.secondaryAddressState;

		if ((secondaryAddressState != null) &&
				(secondaryAddressState.length() == 0)) {
			crmContactCacheModel.secondaryAddressState = null;
		}

		crmContactCacheModel.secondaryAddressZip = getSecondaryAddressZip();

		String secondaryAddressZip = crmContactCacheModel.secondaryAddressZip;

		if ((secondaryAddressZip != null) &&
				(secondaryAddressZip.length() == 0)) {
			crmContactCacheModel.secondaryAddressZip = null;
		}

		crmContactCacheModel.secondaryAddressCounty = getSecondaryAddressCounty();

		String secondaryAddressCounty = crmContactCacheModel.secondaryAddressCounty;

		if ((secondaryAddressCounty != null) &&
				(secondaryAddressCounty.length() == 0)) {
			crmContactCacheModel.secondaryAddressCounty = null;
		}

		crmContactCacheModel.secondaryAddressCountry = getSecondaryAddressCountry();

		String secondaryAddressCountry = crmContactCacheModel.secondaryAddressCountry;

		if ((secondaryAddressCountry != null) &&
				(secondaryAddressCountry.length() == 0)) {
			crmContactCacheModel.secondaryAddressCountry = null;
		}

		crmContactCacheModel.primaryPhone = getPrimaryPhone();

		String primaryPhone = crmContactCacheModel.primaryPhone;

		if ((primaryPhone != null) && (primaryPhone.length() == 0)) {
			crmContactCacheModel.primaryPhone = null;
		}

		crmContactCacheModel.primaryPhoneExtension = getPrimaryPhoneExtension();

		String primaryPhoneExtension = crmContactCacheModel.primaryPhoneExtension;

		if ((primaryPhoneExtension != null) &&
				(primaryPhoneExtension.length() == 0)) {
			crmContactCacheModel.primaryPhoneExtension = null;
		}

		crmContactCacheModel.primaryFax = getPrimaryFax();

		String primaryFax = crmContactCacheModel.primaryFax;

		if ((primaryFax != null) && (primaryFax.length() == 0)) {
			crmContactCacheModel.primaryFax = null;
		}

		crmContactCacheModel.primaryCell = getPrimaryCell();

		String primaryCell = crmContactCacheModel.primaryCell;

		if ((primaryCell != null) && (primaryCell.length() == 0)) {
			crmContactCacheModel.primaryCell = null;
		}

		crmContactCacheModel.primaryEmailAddress = getPrimaryEmailAddress();

		String primaryEmailAddress = crmContactCacheModel.primaryEmailAddress;

		if ((primaryEmailAddress != null) &&
				(primaryEmailAddress.length() == 0)) {
			crmContactCacheModel.primaryEmailAddress = null;
		}

		crmContactCacheModel.alternateContact = getAlternateContact();

		String alternateContact = crmContactCacheModel.alternateContact;

		if ((alternateContact != null) && (alternateContact.length() == 0)) {
			crmContactCacheModel.alternateContact = null;
		}

		crmContactCacheModel.alternateEmail = getAlternateEmail();

		String alternateEmail = crmContactCacheModel.alternateEmail;

		if ((alternateEmail != null) && (alternateEmail.length() == 0)) {
			crmContactCacheModel.alternateEmail = null;
		}

		crmContactCacheModel.isVip = getIsVip();

		crmContactCacheModel.facebookId = getFacebookId();

		String facebookId = crmContactCacheModel.facebookId;

		if ((facebookId != null) && (facebookId.length() == 0)) {
			crmContactCacheModel.facebookId = null;
		}

		crmContactCacheModel.twitterHandle = getTwitterHandle();

		String twitterHandle = crmContactCacheModel.twitterHandle;

		if ((twitterHandle != null) && (twitterHandle.length() == 0)) {
			crmContactCacheModel.twitterHandle = null;
		}

		crmContactCacheModel.linkedInUrl = getLinkedInUrl();

		String linkedInUrl = crmContactCacheModel.linkedInUrl;

		if ((linkedInUrl != null) && (linkedInUrl.length() == 0)) {
			crmContactCacheModel.linkedInUrl = null;
		}

		crmContactCacheModel.status = getStatus();

		String status = crmContactCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			crmContactCacheModel.status = null;
		}

		crmContactCacheModel.kioskUuid = getKioskUuid();

		String kioskUuid = crmContactCacheModel.kioskUuid;

		if ((kioskUuid != null) && (kioskUuid.length() == 0)) {
			crmContactCacheModel.kioskUuid = null;
		}

		crmContactCacheModel.imageFileEntryId = getImageFileEntryId();

		crmContactCacheModel.tagsList = getTagsList();

		String tagsList = crmContactCacheModel.tagsList;

		if ((tagsList != null) && (tagsList.length() == 0)) {
			crmContactCacheModel.tagsList = null;
		}

		crmContactCacheModel.groupsList = getGroupsList();

		String groupsList = crmContactCacheModel.groupsList;

		if ((groupsList != null) && (groupsList.length() == 0)) {
			crmContactCacheModel.groupsList = null;
		}

		return crmContactCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(93);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", crmContactId=");
		sb.append(getCrmContactId());
		sb.append(", constantContactId=");
		sb.append(getConstantContactId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", prefix=");
		sb.append(getPrefix());
		sb.append(", salutation=");
		sb.append(getSalutation());
		sb.append(", firstName=");
		sb.append(getFirstName());
		sb.append(", middleName=");
		sb.append(getMiddleName());
		sb.append(", lastName=");
		sb.append(getLastName());
		sb.append(", organization=");
		sb.append(getOrganization());
		sb.append(", jobTitle=");
		sb.append(getJobTitle());
		sb.append(", primaryAddress1=");
		sb.append(getPrimaryAddress1());
		sb.append(", primaryAddress2=");
		sb.append(getPrimaryAddress2());
		sb.append(", primaryAddressCity=");
		sb.append(getPrimaryAddressCity());
		sb.append(", primaryAddressState=");
		sb.append(getPrimaryAddressState());
		sb.append(", primaryAddressZip=");
		sb.append(getPrimaryAddressZip());
		sb.append(", primaryAddressCounty=");
		sb.append(getPrimaryAddressCounty());
		sb.append(", primaryAddressCountry=");
		sb.append(getPrimaryAddressCountry());
		sb.append(", secondaryAddress1=");
		sb.append(getSecondaryAddress1());
		sb.append(", secondaryAddress2=");
		sb.append(getSecondaryAddress2());
		sb.append(", secondaryAddressCity=");
		sb.append(getSecondaryAddressCity());
		sb.append(", secondaryAddressState=");
		sb.append(getSecondaryAddressState());
		sb.append(", secondaryAddressZip=");
		sb.append(getSecondaryAddressZip());
		sb.append(", secondaryAddressCounty=");
		sb.append(getSecondaryAddressCounty());
		sb.append(", secondaryAddressCountry=");
		sb.append(getSecondaryAddressCountry());
		sb.append(", primaryPhone=");
		sb.append(getPrimaryPhone());
		sb.append(", primaryPhoneExtension=");
		sb.append(getPrimaryPhoneExtension());
		sb.append(", primaryFax=");
		sb.append(getPrimaryFax());
		sb.append(", primaryCell=");
		sb.append(getPrimaryCell());
		sb.append(", primaryEmailAddress=");
		sb.append(getPrimaryEmailAddress());
		sb.append(", alternateContact=");
		sb.append(getAlternateContact());
		sb.append(", alternateEmail=");
		sb.append(getAlternateEmail());
		sb.append(", isVip=");
		sb.append(getIsVip());
		sb.append(", facebookId=");
		sb.append(getFacebookId());
		sb.append(", twitterHandle=");
		sb.append(getTwitterHandle());
		sb.append(", linkedInUrl=");
		sb.append(getLinkedInUrl());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", kioskUuid=");
		sb.append(getKioskUuid());
		sb.append(", imageFileEntryId=");
		sb.append(getImageFileEntryId());
		sb.append(", tagsList=");
		sb.append(getTagsList());
		sb.append(", groupsList=");
		sb.append(getGroupsList());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(142);

		sb.append("<model><model-name>");
		sb.append("contact.manager.model.CrmContact");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>crmContactId</column-name><column-value><![CDATA[");
		sb.append(getCrmContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>constantContactId</column-name><column-value><![CDATA[");
		sb.append(getConstantContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>prefix</column-name><column-value><![CDATA[");
		sb.append(getPrefix());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>salutation</column-name><column-value><![CDATA[");
		sb.append(getSalutation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>firstName</column-name><column-value><![CDATA[");
		sb.append(getFirstName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>middleName</column-name><column-value><![CDATA[");
		sb.append(getMiddleName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastName</column-name><column-value><![CDATA[");
		sb.append(getLastName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organization</column-name><column-value><![CDATA[");
		sb.append(getOrganization());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jobTitle</column-name><column-value><![CDATA[");
		sb.append(getJobTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddress1</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddress1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddress2</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddress2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressCity</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressState</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressZip</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressZip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressCounty</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressCounty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressCountry</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddress1</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddress1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddress2</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddress2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressCity</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressState</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressZip</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressZip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressCounty</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressCounty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressCountry</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryPhone</column-name><column-value><![CDATA[");
		sb.append(getPrimaryPhone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryPhoneExtension</column-name><column-value><![CDATA[");
		sb.append(getPrimaryPhoneExtension());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryFax</column-name><column-value><![CDATA[");
		sb.append(getPrimaryFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryCell</column-name><column-value><![CDATA[");
		sb.append(getPrimaryCell());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryEmailAddress</column-name><column-value><![CDATA[");
		sb.append(getPrimaryEmailAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>alternateContact</column-name><column-value><![CDATA[");
		sb.append(getAlternateContact());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>alternateEmail</column-name><column-value><![CDATA[");
		sb.append(getAlternateEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isVip</column-name><column-value><![CDATA[");
		sb.append(getIsVip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facebookId</column-name><column-value><![CDATA[");
		sb.append(getFacebookId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>twitterHandle</column-name><column-value><![CDATA[");
		sb.append(getTwitterHandle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>linkedInUrl</column-name><column-value><![CDATA[");
		sb.append(getLinkedInUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kioskUuid</column-name><column-value><![CDATA[");
		sb.append(getKioskUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageFileEntryId</column-name><column-value><![CDATA[");
		sb.append(getImageFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagsList</column-name><column-value><![CDATA[");
		sb.append(getTagsList());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupsList</column-name><column-value><![CDATA[");
		sb.append(getGroupsList());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CrmContact.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CrmContact.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _crmContactId;
	private long _constantContactId;
	private long _originalConstantContactId;
	private boolean _setOriginalConstantContactId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _prefix;
	private String _salutation;
	private String _firstName;
	private String _middleName;
	private String _lastName;
	private String _organization;
	private String _jobTitle;
	private String _primaryAddress1;
	private String _primaryAddress2;
	private String _primaryAddressCity;
	private String _primaryAddressState;
	private String _primaryAddressZip;
	private String _primaryAddressCounty;
	private String _primaryAddressCountry;
	private String _secondaryAddress1;
	private String _secondaryAddress2;
	private String _secondaryAddressCity;
	private String _secondaryAddressState;
	private String _secondaryAddressZip;
	private String _secondaryAddressCounty;
	private String _secondaryAddressCountry;
	private String _primaryPhone;
	private String _primaryPhoneExtension;
	private String _primaryFax;
	private String _primaryCell;
	private String _primaryEmailAddress;
	private String _originalPrimaryEmailAddress;
	private String _alternateContact;
	private String _alternateEmail;
	private boolean _isVip;
	private boolean _originalIsVip;
	private boolean _setOriginalIsVip;
	private String _facebookId;
	private String _twitterHandle;
	private String _linkedInUrl;
	private String _status;
	private String _originalStatus;
	private String _kioskUuid;
	private long _imageFileEntryId;
	private String _tagsList;
	private String _groupsList;
	private long _columnBitmask;
	private CrmContact _escapedModel;
}