/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import contact.manager.model.CrmCCA;
import contact.manager.model.CrmCCAModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CrmCCA service. Represents a row in the &quot;crm_cca&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CrmCCAModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CrmCCAImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmCCAImpl
 * @generated
 */
@ProviderType
public class CrmCCAModelImpl
	extends BaseModelImpl<CrmCCA> implements CrmCCAModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a CRM CCA model instance should use the <code>CrmCCA</code> interface instead.
	 */
	public static final String TABLE_NAME = "crm_cca";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"crmCCAId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"zipCode", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("crmCCAId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zipCode", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table crm_cca (uuid_ VARCHAR(75) null,crmCCAId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(500) null,zipCode VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table crm_cca";

	public static final String ORDER_BY_JPQL = " ORDER BY crmCCA.name ASC";

	public static final String ORDER_BY_SQL = " ORDER BY crm_cca.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.contact.manager.model.CrmCCA"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.contact.manager.model.CrmCCA"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.contact.manager.model.CrmCCA"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ZIPCODE_COLUMN_BITMASK = 8L;

	public static final long NAME_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		contact.manager.service.util.ServiceProps.get(
			"lock.expiration.time.contact.manager.model.CrmCCA"));

	public CrmCCAModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _crmCCAId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCrmCCAId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _crmCCAId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CrmCCA.class;
	}

	@Override
	public String getModelClassName() {
		return CrmCCA.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CrmCCA, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CrmCCA, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmCCA, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CrmCCA)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CrmCCA, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CrmCCA, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CrmCCA)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CrmCCA, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CrmCCA, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CrmCCA>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CrmCCA.class.getClassLoader(), CrmCCA.class, ModelWrapper.class);

		try {
			Constructor<CrmCCA> constructor =
				(Constructor<CrmCCA>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CrmCCA, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CrmCCA, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CrmCCA, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CrmCCA, Object>>();
		Map<String, BiConsumer<CrmCCA, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CrmCCA, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object uuid) {
					crmCCA.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"crmCCAId",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getCrmCCAId();
				}

			});
		attributeSetterBiConsumers.put(
			"crmCCAId",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object crmCCAId) {
					crmCCA.setCrmCCAId((Long)crmCCAId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object groupId) {
					crmCCA.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object companyId) {
					crmCCA.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object userId) {
					crmCCA.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object userName) {
					crmCCA.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object createDate) {
					crmCCA.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object modifiedDate) {
					crmCCA.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object name) {
					crmCCA.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"zipCode",
			new Function<CrmCCA, Object>() {

				@Override
				public Object apply(CrmCCA crmCCA) {
					return crmCCA.getZipCode();
				}

			});
		attributeSetterBiConsumers.put(
			"zipCode",
			new BiConsumer<CrmCCA, Object>() {

				@Override
				public void accept(CrmCCA crmCCA, Object zipCode) {
					crmCCA.setZipCode((String)zipCode);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCrmCCAId() {
		return _crmCCAId;
	}

	@Override
	public void setCrmCCAId(long crmCCAId) {
		_crmCCAId = crmCCAId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@Override
	public String getZipCode() {
		if (_zipCode == null) {
			return "";
		}
		else {
			return _zipCode;
		}
	}

	@Override
	public void setZipCode(String zipCode) {
		_columnBitmask |= ZIPCODE_COLUMN_BITMASK;

		if (_originalZipCode == null) {
			_originalZipCode = _zipCode;
		}

		_zipCode = zipCode;
	}

	public String getOriginalZipCode() {
		return GetterUtil.getString(_originalZipCode);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CrmCCA.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CrmCCA.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CrmCCA toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CrmCCA>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CrmCCAImpl crmCCAImpl = new CrmCCAImpl();

		crmCCAImpl.setUuid(getUuid());
		crmCCAImpl.setCrmCCAId(getCrmCCAId());
		crmCCAImpl.setGroupId(getGroupId());
		crmCCAImpl.setCompanyId(getCompanyId());
		crmCCAImpl.setUserId(getUserId());
		crmCCAImpl.setUserName(getUserName());
		crmCCAImpl.setCreateDate(getCreateDate());
		crmCCAImpl.setModifiedDate(getModifiedDate());
		crmCCAImpl.setName(getName());
		crmCCAImpl.setZipCode(getZipCode());

		crmCCAImpl.resetOriginalValues();

		return crmCCAImpl;
	}

	@Override
	public int compareTo(CrmCCA crmCCA) {
		int value = 0;

		value = getName().compareTo(crmCCA.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CrmCCA)) {
			return false;
		}

		CrmCCA crmCCA = (CrmCCA)obj;

		long primaryKey = crmCCA.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CrmCCAModelImpl crmCCAModelImpl = this;

		crmCCAModelImpl._originalUuid = crmCCAModelImpl._uuid;

		crmCCAModelImpl._originalGroupId = crmCCAModelImpl._groupId;

		crmCCAModelImpl._setOriginalGroupId = false;

		crmCCAModelImpl._originalCompanyId = crmCCAModelImpl._companyId;

		crmCCAModelImpl._setOriginalCompanyId = false;

		crmCCAModelImpl._setModifiedDate = false;

		crmCCAModelImpl._originalZipCode = crmCCAModelImpl._zipCode;

		crmCCAModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CrmCCA> toCacheModel() {
		CrmCCACacheModel crmCCACacheModel = new CrmCCACacheModel();

		crmCCACacheModel.uuid = getUuid();

		String uuid = crmCCACacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			crmCCACacheModel.uuid = null;
		}

		crmCCACacheModel.crmCCAId = getCrmCCAId();

		crmCCACacheModel.groupId = getGroupId();

		crmCCACacheModel.companyId = getCompanyId();

		crmCCACacheModel.userId = getUserId();

		crmCCACacheModel.userName = getUserName();

		String userName = crmCCACacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			crmCCACacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			crmCCACacheModel.createDate = createDate.getTime();
		}
		else {
			crmCCACacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			crmCCACacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			crmCCACacheModel.modifiedDate = Long.MIN_VALUE;
		}

		crmCCACacheModel.name = getName();

		String name = crmCCACacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			crmCCACacheModel.name = null;
		}

		crmCCACacheModel.zipCode = getZipCode();

		String zipCode = crmCCACacheModel.zipCode;

		if ((zipCode != null) && (zipCode.length() == 0)) {
			crmCCACacheModel.zipCode = null;
		}

		return crmCCACacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CrmCCA, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CrmCCA, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmCCA, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CrmCCA)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CrmCCA, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CrmCCA, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmCCA, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CrmCCA)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CrmCCA>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _crmCCAId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _zipCode;
	private String _originalZipCode;
	private long _columnBitmask;
	private CrmCCA _escapedModel;

}