/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import contact.manager.model.CrmContactAuditLog;
import contact.manager.model.CrmContactAuditLogModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CrmContactAuditLog service. Represents a row in the &quot;crm_contactauditlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CrmContactAuditLogModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CrmContactAuditLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmContactAuditLogImpl
 * @see CrmContactAuditLog
 * @see CrmContactAuditLogModel
 * @generated
 */
@ProviderType
public class CrmContactAuditLogModelImpl extends BaseModelImpl<CrmContactAuditLog>
	implements CrmContactAuditLogModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a CRM Contact Audit Log model instance should use the {@link CrmContactAuditLog} interface instead.
	 */
	public static final String TABLE_NAME = "crm_contactauditlog";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "crmContactAuditLogId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "crmContactId", Types.BIGINT },
			{ "constantContactId", Types.BIGINT },
			{ "action", Types.VARCHAR },
			{ "oldSnapshot", Types.VARCHAR },
			{ "newSnapshot", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("crmContactAuditLogId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("crmContactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("constantContactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("action", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oldSnapshot", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("newSnapshot", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table crm_contactauditlog (uuid_ VARCHAR(75) null,crmContactAuditLogId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,crmContactId LONG,constantContactId LONG,action VARCHAR(75) null,oldSnapshot TEXT null,newSnapshot TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table crm_contactauditlog";
	public static final String ORDER_BY_JPQL = " ORDER BY crmContactAuditLog.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY crm_contactauditlog.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.contact.manager.model.CrmContactAuditLog"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.contact.manager.model.CrmContactAuditLog"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(contact.manager.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.contact.manager.model.CrmContactAuditLog"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long CONSTANTCONTACTID_COLUMN_BITMASK = 2L;
	public static final long CRMCONTACTID_COLUMN_BITMASK = 4L;
	public static final long GROUPID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(contact.manager.service.util.ServiceProps.get(
				"lock.expiration.time.contact.manager.model.CrmContactAuditLog"));

	public CrmContactAuditLogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _crmContactAuditLogId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCrmContactAuditLogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _crmContactAuditLogId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CrmContactAuditLog.class;
	}

	@Override
	public String getModelClassName() {
		return CrmContactAuditLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("crmContactAuditLogId", getCrmContactAuditLogId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("crmContactId", getCrmContactId());
		attributes.put("constantContactId", getConstantContactId());
		attributes.put("action", getAction());
		attributes.put("oldSnapshot", getOldSnapshot());
		attributes.put("newSnapshot", getNewSnapshot());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long crmContactAuditLogId = (Long)attributes.get("crmContactAuditLogId");

		if (crmContactAuditLogId != null) {
			setCrmContactAuditLogId(crmContactAuditLogId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long crmContactId = (Long)attributes.get("crmContactId");

		if (crmContactId != null) {
			setCrmContactId(crmContactId);
		}

		Long constantContactId = (Long)attributes.get("constantContactId");

		if (constantContactId != null) {
			setConstantContactId(constantContactId);
		}

		String action = (String)attributes.get("action");

		if (action != null) {
			setAction(action);
		}

		String oldSnapshot = (String)attributes.get("oldSnapshot");

		if (oldSnapshot != null) {
			setOldSnapshot(oldSnapshot);
		}

		String newSnapshot = (String)attributes.get("newSnapshot");

		if (newSnapshot != null) {
			setNewSnapshot(newSnapshot);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCrmContactAuditLogId() {
		return _crmContactAuditLogId;
	}

	@Override
	public void setCrmContactAuditLogId(long crmContactAuditLogId) {
		_crmContactAuditLogId = crmContactAuditLogId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCrmContactId() {
		return _crmContactId;
	}

	@Override
	public void setCrmContactId(long crmContactId) {
		_columnBitmask |= CRMCONTACTID_COLUMN_BITMASK;

		if (!_setOriginalCrmContactId) {
			_setOriginalCrmContactId = true;

			_originalCrmContactId = _crmContactId;
		}

		_crmContactId = crmContactId;
	}

	public long getOriginalCrmContactId() {
		return _originalCrmContactId;
	}

	@Override
	public long getConstantContactId() {
		return _constantContactId;
	}

	@Override
	public void setConstantContactId(long constantContactId) {
		_columnBitmask |= CONSTANTCONTACTID_COLUMN_BITMASK;

		if (!_setOriginalConstantContactId) {
			_setOriginalConstantContactId = true;

			_originalConstantContactId = _constantContactId;
		}

		_constantContactId = constantContactId;
	}

	public long getOriginalConstantContactId() {
		return _originalConstantContactId;
	}

	@Override
	public String getAction() {
		if (_action == null) {
			return StringPool.BLANK;
		}
		else {
			return _action;
		}
	}

	@Override
	public void setAction(String action) {
		_action = action;
	}

	@Override
	public String getOldSnapshot() {
		if (_oldSnapshot == null) {
			return StringPool.BLANK;
		}
		else {
			return _oldSnapshot;
		}
	}

	@Override
	public void setOldSnapshot(String oldSnapshot) {
		_oldSnapshot = oldSnapshot;
	}

	@Override
	public String getNewSnapshot() {
		if (_newSnapshot == null) {
			return StringPool.BLANK;
		}
		else {
			return _newSnapshot;
		}
	}

	@Override
	public void setNewSnapshot(String newSnapshot) {
		_newSnapshot = newSnapshot;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				CrmContactAuditLog.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CrmContactAuditLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CrmContactAuditLog toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CrmContactAuditLog)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CrmContactAuditLogImpl crmContactAuditLogImpl = new CrmContactAuditLogImpl();

		crmContactAuditLogImpl.setUuid(getUuid());
		crmContactAuditLogImpl.setCrmContactAuditLogId(getCrmContactAuditLogId());
		crmContactAuditLogImpl.setGroupId(getGroupId());
		crmContactAuditLogImpl.setCompanyId(getCompanyId());
		crmContactAuditLogImpl.setUserId(getUserId());
		crmContactAuditLogImpl.setUserName(getUserName());
		crmContactAuditLogImpl.setCreateDate(getCreateDate());
		crmContactAuditLogImpl.setModifiedDate(getModifiedDate());
		crmContactAuditLogImpl.setCrmContactId(getCrmContactId());
		crmContactAuditLogImpl.setConstantContactId(getConstantContactId());
		crmContactAuditLogImpl.setAction(getAction());
		crmContactAuditLogImpl.setOldSnapshot(getOldSnapshot());
		crmContactAuditLogImpl.setNewSnapshot(getNewSnapshot());

		crmContactAuditLogImpl.resetOriginalValues();

		return crmContactAuditLogImpl;
	}

	@Override
	public int compareTo(CrmContactAuditLog crmContactAuditLog) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				crmContactAuditLog.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CrmContactAuditLog)) {
			return false;
		}

		CrmContactAuditLog crmContactAuditLog = (CrmContactAuditLog)obj;

		long primaryKey = crmContactAuditLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CrmContactAuditLogModelImpl crmContactAuditLogModelImpl = this;

		crmContactAuditLogModelImpl._originalUuid = crmContactAuditLogModelImpl._uuid;

		crmContactAuditLogModelImpl._originalGroupId = crmContactAuditLogModelImpl._groupId;

		crmContactAuditLogModelImpl._setOriginalGroupId = false;

		crmContactAuditLogModelImpl._originalCompanyId = crmContactAuditLogModelImpl._companyId;

		crmContactAuditLogModelImpl._setOriginalCompanyId = false;

		crmContactAuditLogModelImpl._setModifiedDate = false;

		crmContactAuditLogModelImpl._originalCrmContactId = crmContactAuditLogModelImpl._crmContactId;

		crmContactAuditLogModelImpl._setOriginalCrmContactId = false;

		crmContactAuditLogModelImpl._originalConstantContactId = crmContactAuditLogModelImpl._constantContactId;

		crmContactAuditLogModelImpl._setOriginalConstantContactId = false;

		crmContactAuditLogModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CrmContactAuditLog> toCacheModel() {
		CrmContactAuditLogCacheModel crmContactAuditLogCacheModel = new CrmContactAuditLogCacheModel();

		crmContactAuditLogCacheModel.uuid = getUuid();

		String uuid = crmContactAuditLogCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			crmContactAuditLogCacheModel.uuid = null;
		}

		crmContactAuditLogCacheModel.crmContactAuditLogId = getCrmContactAuditLogId();

		crmContactAuditLogCacheModel.groupId = getGroupId();

		crmContactAuditLogCacheModel.companyId = getCompanyId();

		crmContactAuditLogCacheModel.userId = getUserId();

		crmContactAuditLogCacheModel.userName = getUserName();

		String userName = crmContactAuditLogCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			crmContactAuditLogCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			crmContactAuditLogCacheModel.createDate = createDate.getTime();
		}
		else {
			crmContactAuditLogCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			crmContactAuditLogCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			crmContactAuditLogCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		crmContactAuditLogCacheModel.crmContactId = getCrmContactId();

		crmContactAuditLogCacheModel.constantContactId = getConstantContactId();

		crmContactAuditLogCacheModel.action = getAction();

		String action = crmContactAuditLogCacheModel.action;

		if ((action != null) && (action.length() == 0)) {
			crmContactAuditLogCacheModel.action = null;
		}

		crmContactAuditLogCacheModel.oldSnapshot = getOldSnapshot();

		String oldSnapshot = crmContactAuditLogCacheModel.oldSnapshot;

		if ((oldSnapshot != null) && (oldSnapshot.length() == 0)) {
			crmContactAuditLogCacheModel.oldSnapshot = null;
		}

		crmContactAuditLogCacheModel.newSnapshot = getNewSnapshot();

		String newSnapshot = crmContactAuditLogCacheModel.newSnapshot;

		if ((newSnapshot != null) && (newSnapshot.length() == 0)) {
			crmContactAuditLogCacheModel.newSnapshot = null;
		}

		return crmContactAuditLogCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", crmContactAuditLogId=");
		sb.append(getCrmContactAuditLogId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", crmContactId=");
		sb.append(getCrmContactId());
		sb.append(", constantContactId=");
		sb.append(getConstantContactId());
		sb.append(", action=");
		sb.append(getAction());
		sb.append(", oldSnapshot=");
		sb.append(getOldSnapshot());
		sb.append(", newSnapshot=");
		sb.append(getNewSnapshot());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("contact.manager.model.CrmContactAuditLog");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>crmContactAuditLogId</column-name><column-value><![CDATA[");
		sb.append(getCrmContactAuditLogId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>crmContactId</column-name><column-value><![CDATA[");
		sb.append(getCrmContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>constantContactId</column-name><column-value><![CDATA[");
		sb.append(getConstantContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>action</column-name><column-value><![CDATA[");
		sb.append(getAction());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>oldSnapshot</column-name><column-value><![CDATA[");
		sb.append(getOldSnapshot());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>newSnapshot</column-name><column-value><![CDATA[");
		sb.append(getNewSnapshot());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CrmContactAuditLog.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CrmContactAuditLog.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _crmContactAuditLogId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _crmContactId;
	private long _originalCrmContactId;
	private boolean _setOriginalCrmContactId;
	private long _constantContactId;
	private long _originalConstantContactId;
	private boolean _setOriginalConstantContactId;
	private String _action;
	private String _oldSnapshot;
	private String _newSnapshot;
	private long _columnBitmask;
	private CrmContactAuditLog _escapedModel;
}