/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import contact.manager.model.CrmCounty;
import contact.manager.model.CrmCountyModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CrmCounty service. Represents a row in the &quot;crm_county&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CrmCountyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CrmCountyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmCountyImpl
 * @generated
 */
@ProviderType
public class CrmCountyModelImpl
	extends BaseModelImpl<CrmCounty> implements CrmCountyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a CRM County model instance should use the <code>CrmCounty</code> interface instead.
	 */
	public static final String TABLE_NAME = "crm_county";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"crmCountyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"zipCode", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("crmCountyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zipCode", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table crm_county (uuid_ VARCHAR(75) null,crmCountyId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(500) null,zipCode VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table crm_county";

	public static final String ORDER_BY_JPQL = " ORDER BY crmCounty.name ASC";

	public static final String ORDER_BY_SQL = " ORDER BY crm_county.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.contact.manager.model.CrmCounty"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.contact.manager.model.CrmCounty"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.contact.manager.model.CrmCounty"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ZIPCODE_COLUMN_BITMASK = 8L;

	public static final long NAME_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		contact.manager.service.util.ServiceProps.get(
			"lock.expiration.time.contact.manager.model.CrmCounty"));

	public CrmCountyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _crmCountyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCrmCountyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _crmCountyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CrmCounty.class;
	}

	@Override
	public String getModelClassName() {
		return CrmCounty.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CrmCounty, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CrmCounty, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmCounty, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CrmCounty)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CrmCounty, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CrmCounty, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CrmCounty)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CrmCounty, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CrmCounty, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CrmCounty>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CrmCounty.class.getClassLoader(), CrmCounty.class,
			ModelWrapper.class);

		try {
			Constructor<CrmCounty> constructor =
				(Constructor<CrmCounty>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CrmCounty, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CrmCounty, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CrmCounty, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CrmCounty, Object>>();
		Map<String, BiConsumer<CrmCounty, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CrmCounty, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object uuid) {
					crmCounty.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"crmCountyId",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getCrmCountyId();
				}

			});
		attributeSetterBiConsumers.put(
			"crmCountyId",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object crmCountyId) {
					crmCounty.setCrmCountyId((Long)crmCountyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object groupId) {
					crmCounty.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object companyId) {
					crmCounty.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object userId) {
					crmCounty.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object userName) {
					crmCounty.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object createDate) {
					crmCounty.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object modifiedDate) {
					crmCounty.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object name) {
					crmCounty.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"zipCode",
			new Function<CrmCounty, Object>() {

				@Override
				public Object apply(CrmCounty crmCounty) {
					return crmCounty.getZipCode();
				}

			});
		attributeSetterBiConsumers.put(
			"zipCode",
			new BiConsumer<CrmCounty, Object>() {

				@Override
				public void accept(CrmCounty crmCounty, Object zipCode) {
					crmCounty.setZipCode((String)zipCode);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCrmCountyId() {
		return _crmCountyId;
	}

	@Override
	public void setCrmCountyId(long crmCountyId) {
		_crmCountyId = crmCountyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@Override
	public String getZipCode() {
		if (_zipCode == null) {
			return "";
		}
		else {
			return _zipCode;
		}
	}

	@Override
	public void setZipCode(String zipCode) {
		_columnBitmask |= ZIPCODE_COLUMN_BITMASK;

		if (_originalZipCode == null) {
			_originalZipCode = _zipCode;
		}

		_zipCode = zipCode;
	}

	public String getOriginalZipCode() {
		return GetterUtil.getString(_originalZipCode);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CrmCounty.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CrmCounty.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CrmCounty toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CrmCounty>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CrmCountyImpl crmCountyImpl = new CrmCountyImpl();

		crmCountyImpl.setUuid(getUuid());
		crmCountyImpl.setCrmCountyId(getCrmCountyId());
		crmCountyImpl.setGroupId(getGroupId());
		crmCountyImpl.setCompanyId(getCompanyId());
		crmCountyImpl.setUserId(getUserId());
		crmCountyImpl.setUserName(getUserName());
		crmCountyImpl.setCreateDate(getCreateDate());
		crmCountyImpl.setModifiedDate(getModifiedDate());
		crmCountyImpl.setName(getName());
		crmCountyImpl.setZipCode(getZipCode());

		crmCountyImpl.resetOriginalValues();

		return crmCountyImpl;
	}

	@Override
	public int compareTo(CrmCounty crmCounty) {
		int value = 0;

		value = getName().compareTo(crmCounty.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CrmCounty)) {
			return false;
		}

		CrmCounty crmCounty = (CrmCounty)obj;

		long primaryKey = crmCounty.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CrmCountyModelImpl crmCountyModelImpl = this;

		crmCountyModelImpl._originalUuid = crmCountyModelImpl._uuid;

		crmCountyModelImpl._originalGroupId = crmCountyModelImpl._groupId;

		crmCountyModelImpl._setOriginalGroupId = false;

		crmCountyModelImpl._originalCompanyId = crmCountyModelImpl._companyId;

		crmCountyModelImpl._setOriginalCompanyId = false;

		crmCountyModelImpl._setModifiedDate = false;

		crmCountyModelImpl._originalZipCode = crmCountyModelImpl._zipCode;

		crmCountyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CrmCounty> toCacheModel() {
		CrmCountyCacheModel crmCountyCacheModel = new CrmCountyCacheModel();

		crmCountyCacheModel.uuid = getUuid();

		String uuid = crmCountyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			crmCountyCacheModel.uuid = null;
		}

		crmCountyCacheModel.crmCountyId = getCrmCountyId();

		crmCountyCacheModel.groupId = getGroupId();

		crmCountyCacheModel.companyId = getCompanyId();

		crmCountyCacheModel.userId = getUserId();

		crmCountyCacheModel.userName = getUserName();

		String userName = crmCountyCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			crmCountyCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			crmCountyCacheModel.createDate = createDate.getTime();
		}
		else {
			crmCountyCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			crmCountyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			crmCountyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		crmCountyCacheModel.name = getName();

		String name = crmCountyCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			crmCountyCacheModel.name = null;
		}

		crmCountyCacheModel.zipCode = getZipCode();

		String zipCode = crmCountyCacheModel.zipCode;

		if ((zipCode != null) && (zipCode.length() == 0)) {
			crmCountyCacheModel.zipCode = null;
		}

		return crmCountyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CrmCounty, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CrmCounty, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmCounty, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CrmCounty)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CrmCounty, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CrmCounty, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmCounty, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CrmCounty)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CrmCounty>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _crmCountyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _zipCode;
	private String _originalZipCode;
	private long _columnBitmask;
	private CrmCounty _escapedModel;

}