/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import contact.manager.model.CrmGroup;
import contact.manager.model.CrmGroupModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CrmGroup service. Represents a row in the &quot;crm_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CrmGroupModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CrmGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmGroupImpl
 * @generated
 */
@ProviderType
public class CrmGroupModelImpl
	extends BaseModelImpl<CrmGroup> implements CrmGroupModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a CRM Group model instance should use the <code>CrmGroup</code> interface instead.
	 */
	public static final String TABLE_NAME = "crm_group";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"crmGroupId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"crmContactsCount", Types.BIGINT},
		{"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("crmGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("crmContactsCount", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table crm_group (uuid_ VARCHAR(75) null,crmGroupId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(500) null,crmContactsCount LONG,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table crm_group";

	public static final String ORDER_BY_JPQL = " ORDER BY crmGroup.name ASC";

	public static final String ORDER_BY_SQL = " ORDER BY crm_group.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.contact.manager.model.CrmGroup"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.contact.manager.model.CrmGroup"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.contact.manager.model.CrmGroup"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long NAME_COLUMN_BITMASK = 4L;

	public static final long STATUS_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final String MAPPING_TABLE_CRM_CONTACTS_GROUPS_NAME =
		"crm_contacts_groups";

	public static final Object[][] MAPPING_TABLE_CRM_CONTACTS_GROUPS_COLUMNS = {
		{"companyId", Types.BIGINT}, {"crmContactId", Types.BIGINT},
		{"crmGroupId", Types.BIGINT}
	};

	public static final String MAPPING_TABLE_CRM_CONTACTS_GROUPS_SQL_CREATE =
		"create table crm_contacts_groups (companyId LONG not null,crmContactId LONG not null,crmGroupId LONG not null,primary key (crmContactId, crmGroupId))";

	public static final boolean FINDER_CACHE_ENABLED_CRM_CONTACTS_GROUPS =
		GetterUtil.getBoolean(
			contact.manager.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.crm_contacts_groups"),
			true);

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		contact.manager.service.util.ServiceProps.get(
			"lock.expiration.time.contact.manager.model.CrmGroup"));

	public CrmGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _crmGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCrmGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _crmGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CrmGroup.class;
	}

	@Override
	public String getModelClassName() {
		return CrmGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CrmGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CrmGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmGroup, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CrmGroup)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CrmGroup, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CrmGroup, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CrmGroup)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CrmGroup, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CrmGroup, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CrmGroup>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CrmGroup.class.getClassLoader(), CrmGroup.class,
			ModelWrapper.class);

		try {
			Constructor<CrmGroup> constructor =
				(Constructor<CrmGroup>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CrmGroup, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CrmGroup, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CrmGroup, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CrmGroup, Object>>();
		Map<String, BiConsumer<CrmGroup, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CrmGroup, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object uuid) {
					crmGroup.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"crmGroupId",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getCrmGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"crmGroupId",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object crmGroupId) {
					crmGroup.setCrmGroupId((Long)crmGroupId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object groupId) {
					crmGroup.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object companyId) {
					crmGroup.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object userId) {
					crmGroup.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object userName) {
					crmGroup.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object createDate) {
					crmGroup.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object modifiedDate) {
					crmGroup.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object name) {
					crmGroup.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"crmContactsCount",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getCrmContactsCount();
				}

			});
		attributeSetterBiConsumers.put(
			"crmContactsCount",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object crmContactsCount) {
					crmGroup.setCrmContactsCount((Long)crmContactsCount);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<CrmGroup, Object>() {

				@Override
				public Object apply(CrmGroup crmGroup) {
					return crmGroup.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<CrmGroup, Object>() {

				@Override
				public void accept(CrmGroup crmGroup, Object status) {
					crmGroup.setStatus((String)status);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCrmGroupId() {
		return _crmGroupId;
	}

	@Override
	public void setCrmGroupId(long crmGroupId) {
		_crmGroupId = crmGroupId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public long getCrmContactsCount() {
		return _crmContactsCount;
	}

	@Override
	public void setCrmContactsCount(long crmContactsCount) {
		_crmContactsCount = crmContactsCount;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (_originalStatus == null) {
			_originalStatus = _status;
		}

		_status = status;
	}

	public String getOriginalStatus() {
		return GetterUtil.getString(_originalStatus);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CrmGroup.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CrmGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CrmGroup toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CrmGroup>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CrmGroupImpl crmGroupImpl = new CrmGroupImpl();

		crmGroupImpl.setUuid(getUuid());
		crmGroupImpl.setCrmGroupId(getCrmGroupId());
		crmGroupImpl.setGroupId(getGroupId());
		crmGroupImpl.setCompanyId(getCompanyId());
		crmGroupImpl.setUserId(getUserId());
		crmGroupImpl.setUserName(getUserName());
		crmGroupImpl.setCreateDate(getCreateDate());
		crmGroupImpl.setModifiedDate(getModifiedDate());
		crmGroupImpl.setName(getName());
		crmGroupImpl.setCrmContactsCount(getCrmContactsCount());
		crmGroupImpl.setStatus(getStatus());

		crmGroupImpl.resetOriginalValues();

		return crmGroupImpl;
	}

	@Override
	public int compareTo(CrmGroup crmGroup) {
		int value = 0;

		value = getName().compareTo(crmGroup.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CrmGroup)) {
			return false;
		}

		CrmGroup crmGroup = (CrmGroup)obj;

		long primaryKey = crmGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CrmGroupModelImpl crmGroupModelImpl = this;

		crmGroupModelImpl._originalUuid = crmGroupModelImpl._uuid;

		crmGroupModelImpl._originalGroupId = crmGroupModelImpl._groupId;

		crmGroupModelImpl._setOriginalGroupId = false;

		crmGroupModelImpl._originalCompanyId = crmGroupModelImpl._companyId;

		crmGroupModelImpl._setOriginalCompanyId = false;

		crmGroupModelImpl._setModifiedDate = false;

		crmGroupModelImpl._originalName = crmGroupModelImpl._name;

		crmGroupModelImpl._originalStatus = crmGroupModelImpl._status;

		crmGroupModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CrmGroup> toCacheModel() {
		CrmGroupCacheModel crmGroupCacheModel = new CrmGroupCacheModel();

		crmGroupCacheModel.uuid = getUuid();

		String uuid = crmGroupCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			crmGroupCacheModel.uuid = null;
		}

		crmGroupCacheModel.crmGroupId = getCrmGroupId();

		crmGroupCacheModel.groupId = getGroupId();

		crmGroupCacheModel.companyId = getCompanyId();

		crmGroupCacheModel.userId = getUserId();

		crmGroupCacheModel.userName = getUserName();

		String userName = crmGroupCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			crmGroupCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			crmGroupCacheModel.createDate = createDate.getTime();
		}
		else {
			crmGroupCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			crmGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			crmGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		crmGroupCacheModel.name = getName();

		String name = crmGroupCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			crmGroupCacheModel.name = null;
		}

		crmGroupCacheModel.crmContactsCount = getCrmContactsCount();

		crmGroupCacheModel.status = getStatus();

		String status = crmGroupCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			crmGroupCacheModel.status = null;
		}

		return crmGroupCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CrmGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CrmGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CrmGroup)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CrmGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CrmGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CrmGroup)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CrmGroup>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _crmGroupId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private long _crmContactsCount;
	private String _status;
	private String _originalStatus;
	private long _columnBitmask;
	private CrmGroup _escapedModel;

}