/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import contact.manager.model.CrmOutreachLog;
import contact.manager.model.CrmOutreachLogModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CrmOutreachLog service. Represents a row in the &quot;crm_outreachlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CrmOutreachLogModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CrmOutreachLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmOutreachLogImpl
 * @generated
 */
@ProviderType
public class CrmOutreachLogModelImpl
	extends BaseModelImpl<CrmOutreachLog> implements CrmOutreachLogModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a CRM Outreach Log model instance should use the <code>CrmOutreachLog</code> interface instead.
	 */
	public static final String TABLE_NAME = "crm_outreachlog";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"crmOutreachLogId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"crmContactId", Types.BIGINT}, {"note", Types.VARCHAR},
		{"medium", Types.VARCHAR}, {"activityType", Types.VARCHAR},
		{"outreachDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("crmOutreachLogId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("crmContactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("note", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("medium", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("activityType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("outreachDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table crm_outreachlog (uuid_ VARCHAR(75) null,crmOutreachLogId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,crmContactId LONG,note TEXT null,medium VARCHAR(75) null,activityType VARCHAR(75) null,outreachDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table crm_outreachlog";

	public static final String ORDER_BY_JPQL =
		" ORDER BY crmOutreachLog.crmOutreachLogId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY crm_outreachlog.crmOutreachLogId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.contact.manager.model.CrmOutreachLog"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.contact.manager.model.CrmOutreachLog"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.contact.manager.model.CrmOutreachLog"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long CRMCONTACTID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long CRMOUTREACHLOGID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		contact.manager.service.util.ServiceProps.get(
			"lock.expiration.time.contact.manager.model.CrmOutreachLog"));

	public CrmOutreachLogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _crmOutreachLogId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCrmOutreachLogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _crmOutreachLogId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CrmOutreachLog.class;
	}

	@Override
	public String getModelClassName() {
		return CrmOutreachLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CrmOutreachLog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CrmOutreachLog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmOutreachLog, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CrmOutreachLog)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CrmOutreachLog, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CrmOutreachLog, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CrmOutreachLog)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CrmOutreachLog, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CrmOutreachLog, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CrmOutreachLog>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CrmOutreachLog.class.getClassLoader(), CrmOutreachLog.class,
			ModelWrapper.class);

		try {
			Constructor<CrmOutreachLog> constructor =
				(Constructor<CrmOutreachLog>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CrmOutreachLog, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CrmOutreachLog, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CrmOutreachLog, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CrmOutreachLog, Object>>();
		Map<String, BiConsumer<CrmOutreachLog, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CrmOutreachLog, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(CrmOutreachLog crmOutreachLog, Object uuid) {
					crmOutreachLog.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"crmOutreachLogId",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getCrmOutreachLogId();
				}

			});
		attributeSetterBiConsumers.put(
			"crmOutreachLogId",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object crmOutreachLogId) {

					crmOutreachLog.setCrmOutreachLogId((Long)crmOutreachLogId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object groupId) {

					crmOutreachLog.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object companyId) {

					crmOutreachLog.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object userId) {

					crmOutreachLog.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object userName) {

					crmOutreachLog.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object createDate) {

					crmOutreachLog.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object modifiedDate) {

					crmOutreachLog.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"crmContactId",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getCrmContactId();
				}

			});
		attributeSetterBiConsumers.put(
			"crmContactId",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object crmContactId) {

					crmOutreachLog.setCrmContactId((Long)crmContactId);
				}

			});
		attributeGetterFunctions.put(
			"note",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getNote();
				}

			});
		attributeSetterBiConsumers.put(
			"note",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(CrmOutreachLog crmOutreachLog, Object note) {
					crmOutreachLog.setNote((String)note);
				}

			});
		attributeGetterFunctions.put(
			"medium",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getMedium();
				}

			});
		attributeSetterBiConsumers.put(
			"medium",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object medium) {

					crmOutreachLog.setMedium((String)medium);
				}

			});
		attributeGetterFunctions.put(
			"activityType",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getActivityType();
				}

			});
		attributeSetterBiConsumers.put(
			"activityType",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object activityType) {

					crmOutreachLog.setActivityType((String)activityType);
				}

			});
		attributeGetterFunctions.put(
			"outreachDate",
			new Function<CrmOutreachLog, Object>() {

				@Override
				public Object apply(CrmOutreachLog crmOutreachLog) {
					return crmOutreachLog.getOutreachDate();
				}

			});
		attributeSetterBiConsumers.put(
			"outreachDate",
			new BiConsumer<CrmOutreachLog, Object>() {

				@Override
				public void accept(
					CrmOutreachLog crmOutreachLog, Object outreachDate) {

					crmOutreachLog.setOutreachDate((Date)outreachDate);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCrmOutreachLogId() {
		return _crmOutreachLogId;
	}

	@Override
	public void setCrmOutreachLogId(long crmOutreachLogId) {
		_crmOutreachLogId = crmOutreachLogId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCrmContactId() {
		return _crmContactId;
	}

	@Override
	public void setCrmContactId(long crmContactId) {
		_columnBitmask |= CRMCONTACTID_COLUMN_BITMASK;

		if (!_setOriginalCrmContactId) {
			_setOriginalCrmContactId = true;

			_originalCrmContactId = _crmContactId;
		}

		_crmContactId = crmContactId;
	}

	public long getOriginalCrmContactId() {
		return _originalCrmContactId;
	}

	@Override
	public String getNote() {
		if (_note == null) {
			return "";
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		_note = note;
	}

	@Override
	public String getMedium() {
		if (_medium == null) {
			return "";
		}
		else {
			return _medium;
		}
	}

	@Override
	public void setMedium(String medium) {
		_medium = medium;
	}

	@Override
	public String getActivityType() {
		if (_activityType == null) {
			return "";
		}
		else {
			return _activityType;
		}
	}

	@Override
	public void setActivityType(String activityType) {
		_activityType = activityType;
	}

	@Override
	public Date getOutreachDate() {
		return _outreachDate;
	}

	@Override
	public void setOutreachDate(Date outreachDate) {
		_outreachDate = outreachDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CrmOutreachLog.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CrmOutreachLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CrmOutreachLog toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CrmOutreachLog>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CrmOutreachLogImpl crmOutreachLogImpl = new CrmOutreachLogImpl();

		crmOutreachLogImpl.setUuid(getUuid());
		crmOutreachLogImpl.setCrmOutreachLogId(getCrmOutreachLogId());
		crmOutreachLogImpl.setGroupId(getGroupId());
		crmOutreachLogImpl.setCompanyId(getCompanyId());
		crmOutreachLogImpl.setUserId(getUserId());
		crmOutreachLogImpl.setUserName(getUserName());
		crmOutreachLogImpl.setCreateDate(getCreateDate());
		crmOutreachLogImpl.setModifiedDate(getModifiedDate());
		crmOutreachLogImpl.setCrmContactId(getCrmContactId());
		crmOutreachLogImpl.setNote(getNote());
		crmOutreachLogImpl.setMedium(getMedium());
		crmOutreachLogImpl.setActivityType(getActivityType());
		crmOutreachLogImpl.setOutreachDate(getOutreachDate());

		crmOutreachLogImpl.resetOriginalValues();

		return crmOutreachLogImpl;
	}

	@Override
	public int compareTo(CrmOutreachLog crmOutreachLog) {
		long primaryKey = crmOutreachLog.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CrmOutreachLog)) {
			return false;
		}

		CrmOutreachLog crmOutreachLog = (CrmOutreachLog)obj;

		long primaryKey = crmOutreachLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CrmOutreachLogModelImpl crmOutreachLogModelImpl = this;

		crmOutreachLogModelImpl._originalUuid = crmOutreachLogModelImpl._uuid;

		crmOutreachLogModelImpl._originalGroupId =
			crmOutreachLogModelImpl._groupId;

		crmOutreachLogModelImpl._setOriginalGroupId = false;

		crmOutreachLogModelImpl._originalCompanyId =
			crmOutreachLogModelImpl._companyId;

		crmOutreachLogModelImpl._setOriginalCompanyId = false;

		crmOutreachLogModelImpl._setModifiedDate = false;

		crmOutreachLogModelImpl._originalCrmContactId =
			crmOutreachLogModelImpl._crmContactId;

		crmOutreachLogModelImpl._setOriginalCrmContactId = false;

		crmOutreachLogModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CrmOutreachLog> toCacheModel() {
		CrmOutreachLogCacheModel crmOutreachLogCacheModel =
			new CrmOutreachLogCacheModel();

		crmOutreachLogCacheModel.uuid = getUuid();

		String uuid = crmOutreachLogCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			crmOutreachLogCacheModel.uuid = null;
		}

		crmOutreachLogCacheModel.crmOutreachLogId = getCrmOutreachLogId();

		crmOutreachLogCacheModel.groupId = getGroupId();

		crmOutreachLogCacheModel.companyId = getCompanyId();

		crmOutreachLogCacheModel.userId = getUserId();

		crmOutreachLogCacheModel.userName = getUserName();

		String userName = crmOutreachLogCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			crmOutreachLogCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			crmOutreachLogCacheModel.createDate = createDate.getTime();
		}
		else {
			crmOutreachLogCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			crmOutreachLogCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			crmOutreachLogCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		crmOutreachLogCacheModel.crmContactId = getCrmContactId();

		crmOutreachLogCacheModel.note = getNote();

		String note = crmOutreachLogCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			crmOutreachLogCacheModel.note = null;
		}

		crmOutreachLogCacheModel.medium = getMedium();

		String medium = crmOutreachLogCacheModel.medium;

		if ((medium != null) && (medium.length() == 0)) {
			crmOutreachLogCacheModel.medium = null;
		}

		crmOutreachLogCacheModel.activityType = getActivityType();

		String activityType = crmOutreachLogCacheModel.activityType;

		if ((activityType != null) && (activityType.length() == 0)) {
			crmOutreachLogCacheModel.activityType = null;
		}

		Date outreachDate = getOutreachDate();

		if (outreachDate != null) {
			crmOutreachLogCacheModel.outreachDate = outreachDate.getTime();
		}
		else {
			crmOutreachLogCacheModel.outreachDate = Long.MIN_VALUE;
		}

		return crmOutreachLogCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CrmOutreachLog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CrmOutreachLog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmOutreachLog, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CrmOutreachLog)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CrmOutreachLog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CrmOutreachLog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmOutreachLog, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CrmOutreachLog)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CrmOutreachLog>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _crmOutreachLogId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _crmContactId;
	private long _originalCrmContactId;
	private boolean _setOriginalCrmContactId;
	private String _note;
	private String _medium;
	private String _activityType;
	private Date _outreachDate;
	private long _columnBitmask;
	private CrmOutreachLog _escapedModel;

}