/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import contact.manager.model.CrmTag;
import contact.manager.model.CrmTagModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CrmTag service. Represents a row in the &quot;crm_tag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CrmTagModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CrmTagImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmTagImpl
 * @generated
 */
@ProviderType
public class CrmTagModelImpl
	extends BaseModelImpl<CrmTag> implements CrmTagModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a CRM Tag model instance should use the <code>CrmTag</code> interface instead.
	 */
	public static final String TABLE_NAME = "crm_tag";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"crmTagId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("crmTagId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table crm_tag (uuid_ VARCHAR(75) null,crmTagId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(500) null)";

	public static final String TABLE_SQL_DROP = "drop table crm_tag";

	public static final String ORDER_BY_JPQL = " ORDER BY crmTag.crmTagId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY crm_tag.crmTagId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.contact.manager.model.CrmTag"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.contact.manager.model.CrmTag"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		contact.manager.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.contact.manager.model.CrmTag"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long CRMTAGID_COLUMN_BITMASK = 8L;

	public static final String MAPPING_TABLE_CRM_CONTACTS_TAGS_NAME =
		"crm_contacts_tags";

	public static final Object[][] MAPPING_TABLE_CRM_CONTACTS_TAGS_COLUMNS = {
		{"companyId", Types.BIGINT}, {"crmContactId", Types.BIGINT},
		{"crmTagId", Types.BIGINT}
	};

	public static final String MAPPING_TABLE_CRM_CONTACTS_TAGS_SQL_CREATE =
		"create table crm_contacts_tags (companyId LONG not null,crmContactId LONG not null,crmTagId LONG not null,primary key (crmContactId, crmTagId))";

	public static final boolean FINDER_CACHE_ENABLED_CRM_CONTACTS_TAGS =
		GetterUtil.getBoolean(
			contact.manager.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.crm_contacts_tags"),
			true);

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		contact.manager.service.util.ServiceProps.get(
			"lock.expiration.time.contact.manager.model.CrmTag"));

	public CrmTagModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _crmTagId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCrmTagId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _crmTagId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CrmTag.class;
	}

	@Override
	public String getModelClassName() {
		return CrmTag.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CrmTag, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CrmTag, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmTag, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CrmTag)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CrmTag, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CrmTag, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CrmTag)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CrmTag, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CrmTag, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CrmTag>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CrmTag.class.getClassLoader(), CrmTag.class, ModelWrapper.class);

		try {
			Constructor<CrmTag> constructor =
				(Constructor<CrmTag>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CrmTag, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CrmTag, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CrmTag, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CrmTag, Object>>();
		Map<String, BiConsumer<CrmTag, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CrmTag, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object uuid) {
					crmTag.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"crmTagId",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getCrmTagId();
				}

			});
		attributeSetterBiConsumers.put(
			"crmTagId",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object crmTagId) {
					crmTag.setCrmTagId((Long)crmTagId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object groupId) {
					crmTag.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object companyId) {
					crmTag.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object userId) {
					crmTag.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object userName) {
					crmTag.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object createDate) {
					crmTag.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object modifiedDate) {
					crmTag.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<CrmTag, Object>() {

				@Override
				public Object apply(CrmTag crmTag) {
					return crmTag.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<CrmTag, Object>() {

				@Override
				public void accept(CrmTag crmTag, Object name) {
					crmTag.setName((String)name);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCrmTagId() {
		return _crmTagId;
	}

	@Override
	public void setCrmTagId(long crmTagId) {
		_crmTagId = crmTagId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CrmTag.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CrmTag.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CrmTag toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CrmTag>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CrmTagImpl crmTagImpl = new CrmTagImpl();

		crmTagImpl.setUuid(getUuid());
		crmTagImpl.setCrmTagId(getCrmTagId());
		crmTagImpl.setGroupId(getGroupId());
		crmTagImpl.setCompanyId(getCompanyId());
		crmTagImpl.setUserId(getUserId());
		crmTagImpl.setUserName(getUserName());
		crmTagImpl.setCreateDate(getCreateDate());
		crmTagImpl.setModifiedDate(getModifiedDate());
		crmTagImpl.setName(getName());

		crmTagImpl.resetOriginalValues();

		return crmTagImpl;
	}

	@Override
	public int compareTo(CrmTag crmTag) {
		long primaryKey = crmTag.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CrmTag)) {
			return false;
		}

		CrmTag crmTag = (CrmTag)obj;

		long primaryKey = crmTag.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CrmTagModelImpl crmTagModelImpl = this;

		crmTagModelImpl._originalUuid = crmTagModelImpl._uuid;

		crmTagModelImpl._originalGroupId = crmTagModelImpl._groupId;

		crmTagModelImpl._setOriginalGroupId = false;

		crmTagModelImpl._originalCompanyId = crmTagModelImpl._companyId;

		crmTagModelImpl._setOriginalCompanyId = false;

		crmTagModelImpl._setModifiedDate = false;

		crmTagModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CrmTag> toCacheModel() {
		CrmTagCacheModel crmTagCacheModel = new CrmTagCacheModel();

		crmTagCacheModel.uuid = getUuid();

		String uuid = crmTagCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			crmTagCacheModel.uuid = null;
		}

		crmTagCacheModel.crmTagId = getCrmTagId();

		crmTagCacheModel.groupId = getGroupId();

		crmTagCacheModel.companyId = getCompanyId();

		crmTagCacheModel.userId = getUserId();

		crmTagCacheModel.userName = getUserName();

		String userName = crmTagCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			crmTagCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			crmTagCacheModel.createDate = createDate.getTime();
		}
		else {
			crmTagCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			crmTagCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			crmTagCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		crmTagCacheModel.name = getName();

		String name = crmTagCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			crmTagCacheModel.name = null;
		}

		return crmTagCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CrmTag, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CrmTag, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmTag, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CrmTag)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CrmTag, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CrmTag, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CrmTag, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CrmTag)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CrmTag>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _crmTagId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private long _columnBitmask;
	private CrmTag _escapedModel;

}