/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CrmContactAuditLogChange service. Represents a row in the &quot;crm_contactauditlogchange&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link contact.manager.model.impl.CrmContactAuditLogChangeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link contact.manager.model.impl.CrmContactAuditLogChangeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmContactAuditLogChange
 * @see contact.manager.model.impl.CrmContactAuditLogChangeImpl
 * @see contact.manager.model.impl.CrmContactAuditLogChangeModelImpl
 * @generated
 */
@ProviderType
public interface CrmContactAuditLogChangeModel extends BaseModel<CrmContactAuditLogChange>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a CRM Contact Audit Log Change model instance should use the {@link CrmContactAuditLogChange} interface instead.
	 */

	/**
	 * Returns the primary key of this CRM Contact Audit Log Change.
	 *
	 * @return the primary key of this CRM Contact Audit Log Change
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this CRM Contact Audit Log Change.
	 *
	 * @param primaryKey the primary key of this CRM Contact Audit Log Change
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this CRM Contact Audit Log Change.
	 *
	 * @return the uuid of this CRM Contact Audit Log Change
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this CRM Contact Audit Log Change.
	 *
	 * @param uuid the uuid of this CRM Contact Audit Log Change
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the crm contact audit log change ID of this CRM Contact Audit Log Change.
	 *
	 * @return the crm contact audit log change ID of this CRM Contact Audit Log Change
	 */
	public long getCrmContactAuditLogChangeId();

	/**
	 * Sets the crm contact audit log change ID of this CRM Contact Audit Log Change.
	 *
	 * @param crmContactAuditLogChangeId the crm contact audit log change ID of this CRM Contact Audit Log Change
	 */
	public void setCrmContactAuditLogChangeId(long crmContactAuditLogChangeId);

	/**
	 * Returns the group ID of this CRM Contact Audit Log Change.
	 *
	 * @return the group ID of this CRM Contact Audit Log Change
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this CRM Contact Audit Log Change.
	 *
	 * @param groupId the group ID of this CRM Contact Audit Log Change
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this CRM Contact Audit Log Change.
	 *
	 * @return the company ID of this CRM Contact Audit Log Change
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this CRM Contact Audit Log Change.
	 *
	 * @param companyId the company ID of this CRM Contact Audit Log Change
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this CRM Contact Audit Log Change.
	 *
	 * @return the user ID of this CRM Contact Audit Log Change
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this CRM Contact Audit Log Change.
	 *
	 * @param userId the user ID of this CRM Contact Audit Log Change
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this CRM Contact Audit Log Change.
	 *
	 * @return the user uuid of this CRM Contact Audit Log Change
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this CRM Contact Audit Log Change.
	 *
	 * @param userUuid the user uuid of this CRM Contact Audit Log Change
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this CRM Contact Audit Log Change.
	 *
	 * @return the user name of this CRM Contact Audit Log Change
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this CRM Contact Audit Log Change.
	 *
	 * @param userName the user name of this CRM Contact Audit Log Change
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this CRM Contact Audit Log Change.
	 *
	 * @return the create date of this CRM Contact Audit Log Change
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this CRM Contact Audit Log Change.
	 *
	 * @param createDate the create date of this CRM Contact Audit Log Change
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this CRM Contact Audit Log Change.
	 *
	 * @return the modified date of this CRM Contact Audit Log Change
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this CRM Contact Audit Log Change.
	 *
	 * @param modifiedDate the modified date of this CRM Contact Audit Log Change
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the crm contact audit log ID of this CRM Contact Audit Log Change.
	 *
	 * @return the crm contact audit log ID of this CRM Contact Audit Log Change
	 */
	public long getCrmContactAuditLogId();

	/**
	 * Sets the crm contact audit log ID of this CRM Contact Audit Log Change.
	 *
	 * @param crmContactAuditLogId the crm contact audit log ID of this CRM Contact Audit Log Change
	 */
	public void setCrmContactAuditLogId(long crmContactAuditLogId);

	/**
	 * Returns the field name of this CRM Contact Audit Log Change.
	 *
	 * @return the field name of this CRM Contact Audit Log Change
	 */
	@AutoEscape
	public String getFieldName();

	/**
	 * Sets the field name of this CRM Contact Audit Log Change.
	 *
	 * @param fieldName the field name of this CRM Contact Audit Log Change
	 */
	public void setFieldName(String fieldName);

	/**
	 * Returns the old value of this CRM Contact Audit Log Change.
	 *
	 * @return the old value of this CRM Contact Audit Log Change
	 */
	@AutoEscape
	public String getOldValue();

	/**
	 * Sets the old value of this CRM Contact Audit Log Change.
	 *
	 * @param oldValue the old value of this CRM Contact Audit Log Change
	 */
	public void setOldValue(String oldValue);

	/**
	 * Returns the new value of this CRM Contact Audit Log Change.
	 *
	 * @return the new value of this CRM Contact Audit Log Change
	 */
	@AutoEscape
	public String getNewValue();

	/**
	 * Sets the new value of this CRM Contact Audit Log Change.
	 *
	 * @param newValue the new value of this CRM Contact Audit Log Change
	 */
	public void setNewValue(String newValue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		contact.manager.model.CrmContactAuditLogChange crmContactAuditLogChange);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.model.CrmContactAuditLogChange> toCacheModel();

	@Override
	public contact.manager.model.CrmContactAuditLogChange toEscapedModel();

	@Override
	public contact.manager.model.CrmContactAuditLogChange toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}