/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CrmOutreachLog service. Represents a row in the &quot;crm_outreachlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>contact.manager.model.impl.CrmOutreachLogModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>contact.manager.model.impl.CrmOutreachLogImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CrmOutreachLog
 * @generated
 */
@ProviderType
public interface CrmOutreachLogModel
	extends BaseModel<CrmOutreachLog>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a CRM Outreach Log model instance should use the {@link CrmOutreachLog} interface instead.
	 */

	/**
	 * Returns the primary key of this CRM Outreach Log.
	 *
	 * @return the primary key of this CRM Outreach Log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this CRM Outreach Log.
	 *
	 * @param primaryKey the primary key of this CRM Outreach Log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this CRM Outreach Log.
	 *
	 * @return the uuid of this CRM Outreach Log
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this CRM Outreach Log.
	 *
	 * @param uuid the uuid of this CRM Outreach Log
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the crm outreach log ID of this CRM Outreach Log.
	 *
	 * @return the crm outreach log ID of this CRM Outreach Log
	 */
	public long getCrmOutreachLogId();

	/**
	 * Sets the crm outreach log ID of this CRM Outreach Log.
	 *
	 * @param crmOutreachLogId the crm outreach log ID of this CRM Outreach Log
	 */
	public void setCrmOutreachLogId(long crmOutreachLogId);

	/**
	 * Returns the group ID of this CRM Outreach Log.
	 *
	 * @return the group ID of this CRM Outreach Log
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this CRM Outreach Log.
	 *
	 * @param groupId the group ID of this CRM Outreach Log
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this CRM Outreach Log.
	 *
	 * @return the company ID of this CRM Outreach Log
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this CRM Outreach Log.
	 *
	 * @param companyId the company ID of this CRM Outreach Log
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this CRM Outreach Log.
	 *
	 * @return the user ID of this CRM Outreach Log
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this CRM Outreach Log.
	 *
	 * @param userId the user ID of this CRM Outreach Log
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this CRM Outreach Log.
	 *
	 * @return the user uuid of this CRM Outreach Log
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this CRM Outreach Log.
	 *
	 * @param userUuid the user uuid of this CRM Outreach Log
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this CRM Outreach Log.
	 *
	 * @return the user name of this CRM Outreach Log
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this CRM Outreach Log.
	 *
	 * @param userName the user name of this CRM Outreach Log
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this CRM Outreach Log.
	 *
	 * @return the create date of this CRM Outreach Log
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this CRM Outreach Log.
	 *
	 * @param createDate the create date of this CRM Outreach Log
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this CRM Outreach Log.
	 *
	 * @return the modified date of this CRM Outreach Log
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this CRM Outreach Log.
	 *
	 * @param modifiedDate the modified date of this CRM Outreach Log
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the crm contact ID of this CRM Outreach Log.
	 *
	 * @return the crm contact ID of this CRM Outreach Log
	 */
	public long getCrmContactId();

	/**
	 * Sets the crm contact ID of this CRM Outreach Log.
	 *
	 * @param crmContactId the crm contact ID of this CRM Outreach Log
	 */
	public void setCrmContactId(long crmContactId);

	/**
	 * Returns the note of this CRM Outreach Log.
	 *
	 * @return the note of this CRM Outreach Log
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this CRM Outreach Log.
	 *
	 * @param note the note of this CRM Outreach Log
	 */
	public void setNote(String note);

	/**
	 * Returns the medium of this CRM Outreach Log.
	 *
	 * @return the medium of this CRM Outreach Log
	 */
	@AutoEscape
	public String getMedium();

	/**
	 * Sets the medium of this CRM Outreach Log.
	 *
	 * @param medium the medium of this CRM Outreach Log
	 */
	public void setMedium(String medium);

	/**
	 * Returns the activity type of this CRM Outreach Log.
	 *
	 * @return the activity type of this CRM Outreach Log
	 */
	@AutoEscape
	public String getActivityType();

	/**
	 * Sets the activity type of this CRM Outreach Log.
	 *
	 * @param activityType the activity type of this CRM Outreach Log
	 */
	public void setActivityType(String activityType);

	/**
	 * Returns the outreach date of this CRM Outreach Log.
	 *
	 * @return the outreach date of this CRM Outreach Log
	 */
	public Date getOutreachDate();

	/**
	 * Sets the outreach date of this CRM Outreach Log.
	 *
	 * @param outreachDate the outreach date of this CRM Outreach Log
	 */
	public void setOutreachDate(Date outreachDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(contact.manager.model.CrmOutreachLog crmOutreachLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.model.CrmOutreachLog> toCacheModel();

	@Override
	public contact.manager.model.CrmOutreachLog toEscapedModel();

	@Override
	public contact.manager.model.CrmOutreachLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}