/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model.impl;

import aQute.bnd.annotation.ProviderType;

import ucc.portal.model.CExtOrganization;

import ucc.portal.service.CExtOrganizationLocalServiceUtil;

/**
 * The extended model base implementation for the CExtOrganization service. Represents a row in the &quot;UCC_CExtOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CExtOrganizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CExtOrganizationImpl
 * @see CExtOrganization
 * @generated
 */
@ProviderType
public abstract class CExtOrganizationBaseImpl extends CExtOrganizationModelImpl
	implements CExtOrganization {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a c ext organization model instance should use the {@link CExtOrganization} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CExtOrganizationLocalServiceUtil.addCExtOrganization(this);
		}
		else {
			CExtOrganizationLocalServiceUtil.updateCExtOrganization(this);
		}
	}
}