/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import ucc.portal.model.ExtVocationalHistory;
import ucc.portal.model.ExtVocationalHistoryModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ExtVocationalHistory service. Represents a row in the &quot;UCC_ExtVocationalHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ExtVocationalHistoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExtVocationalHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtVocationalHistoryImpl
 * @see ExtVocationalHistory
 * @see ExtVocationalHistoryModel
 * @generated
 */
@ProviderType
public class ExtVocationalHistoryModelImpl extends BaseModelImpl<ExtVocationalHistory>
	implements ExtVocationalHistoryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ext vocational history model instance should use the {@link ExtVocationalHistory} interface instead.
	 */
	public static final String TABLE_NAME = "UCC_ExtVocationalHistory";
	public static final Object[][] TABLE_COLUMNS = {
			{ "extVocationalHistoryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "locationOrSetting", Types.VARCHAR },
			{ "city", Types.VARCHAR },
			{ "regionId", Types.BIGINT },
			{ "countryId", Types.BIGINT },
			{ "startDateOfService", Types.TIMESTAMP },
			{ "endDateOfService", Types.TIMESTAMP },
			{ "titleOrPosition", Types.VARCHAR },
			{ "jobTypeId", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("extVocationalHistoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("locationOrSetting", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("regionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("countryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startDateOfService", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDateOfService", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("titleOrPosition", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobTypeId", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table UCC_ExtVocationalHistory (extVocationalHistoryId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,locationOrSetting VARCHAR(75) null,city VARCHAR(75) null,regionId LONG,countryId LONG,startDateOfService DATE null,endDateOfService DATE null,titleOrPosition VARCHAR(75) null,jobTypeId INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table UCC_ExtVocationalHistory";
	public static final String ORDER_BY_JPQL = " ORDER BY extVocationalHistory.startDateOfService DESC, extVocationalHistory.endDateOfService DESC";
	public static final String ORDER_BY_SQL = " ORDER BY UCC_ExtVocationalHistory.startDateOfService DESC, UCC_ExtVocationalHistory.endDateOfService DESC";
	public static final String DATA_SOURCE = "extDataSource";
	public static final String SESSION_FACTORY = "extSessionFactory";
	public static final String TX_MANAGER = "extTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(ucc.portal.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.ucc.portal.model.ExtVocationalHistory"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(ucc.portal.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.ucc.portal.model.ExtVocationalHistory"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(ucc.portal.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.ucc.portal.model.ExtVocationalHistory"),
			true);
	public static final long USERID_COLUMN_BITMASK = 1L;
	public static final long STARTDATEOFSERVICE_COLUMN_BITMASK = 2L;
	public static final long ENDDATEOFSERVICE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(ucc.portal.service.util.ServiceProps.get(
				"lock.expiration.time.ucc.portal.model.ExtVocationalHistory"));

	public ExtVocationalHistoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _extVocationalHistoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setExtVocationalHistoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _extVocationalHistoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExtVocationalHistory.class;
	}

	@Override
	public String getModelClassName() {
		return ExtVocationalHistory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("extVocationalHistoryId", getExtVocationalHistoryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("locationOrSetting", getLocationOrSetting());
		attributes.put("city", getCity());
		attributes.put("regionId", getRegionId());
		attributes.put("countryId", getCountryId());
		attributes.put("startDateOfService", getStartDateOfService());
		attributes.put("endDateOfService", getEndDateOfService());
		attributes.put("titleOrPosition", getTitleOrPosition());
		attributes.put("jobTypeId", getJobTypeId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long extVocationalHistoryId = (Long)attributes.get(
				"extVocationalHistoryId");

		if (extVocationalHistoryId != null) {
			setExtVocationalHistoryId(extVocationalHistoryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String locationOrSetting = (String)attributes.get("locationOrSetting");

		if (locationOrSetting != null) {
			setLocationOrSetting(locationOrSetting);
		}

		String city = (String)attributes.get("city");

		if (city != null) {
			setCity(city);
		}

		Long regionId = (Long)attributes.get("regionId");

		if (regionId != null) {
			setRegionId(regionId);
		}

		Long countryId = (Long)attributes.get("countryId");

		if (countryId != null) {
			setCountryId(countryId);
		}

		Date startDateOfService = (Date)attributes.get("startDateOfService");

		if (startDateOfService != null) {
			setStartDateOfService(startDateOfService);
		}

		Date endDateOfService = (Date)attributes.get("endDateOfService");

		if (endDateOfService != null) {
			setEndDateOfService(endDateOfService);
		}

		String titleOrPosition = (String)attributes.get("titleOrPosition");

		if (titleOrPosition != null) {
			setTitleOrPosition(titleOrPosition);
		}

		Integer jobTypeId = (Integer)attributes.get("jobTypeId");

		if (jobTypeId != null) {
			setJobTypeId(jobTypeId);
		}
	}

	@Override
	public long getExtVocationalHistoryId() {
		return _extVocationalHistoryId;
	}

	@Override
	public void setExtVocationalHistoryId(long extVocationalHistoryId) {
		_extVocationalHistoryId = extVocationalHistoryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getLocationOrSetting() {
		if (_locationOrSetting == null) {
			return "";
		}
		else {
			return _locationOrSetting;
		}
	}

	@Override
	public void setLocationOrSetting(String locationOrSetting) {
		_locationOrSetting = locationOrSetting;
	}

	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		_city = city;
	}

	@Override
	public long getRegionId() {
		return _regionId;
	}

	@Override
	public void setRegionId(long regionId) {
		_regionId = regionId;
	}

	@Override
	public long getCountryId() {
		return _countryId;
	}

	@Override
	public void setCountryId(long countryId) {
		_countryId = countryId;
	}

	@Override
	public Date getStartDateOfService() {
		return _startDateOfService;
	}

	@Override
	public void setStartDateOfService(Date startDateOfService) {
		_columnBitmask = -1L;

		_startDateOfService = startDateOfService;
	}

	@Override
	public Date getEndDateOfService() {
		return _endDateOfService;
	}

	@Override
	public void setEndDateOfService(Date endDateOfService) {
		_columnBitmask = -1L;

		_endDateOfService = endDateOfService;
	}

	@Override
	public String getTitleOrPosition() {
		if (_titleOrPosition == null) {
			return "";
		}
		else {
			return _titleOrPosition;
		}
	}

	@Override
	public void setTitleOrPosition(String titleOrPosition) {
		_titleOrPosition = titleOrPosition;
	}

	@Override
	public int getJobTypeId() {
		return _jobTypeId;
	}

	@Override
	public void setJobTypeId(int jobTypeId) {
		_jobTypeId = jobTypeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ExtVocationalHistory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExtVocationalHistory toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ExtVocationalHistory)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExtVocationalHistoryImpl extVocationalHistoryImpl = new ExtVocationalHistoryImpl();

		extVocationalHistoryImpl.setExtVocationalHistoryId(getExtVocationalHistoryId());
		extVocationalHistoryImpl.setCompanyId(getCompanyId());
		extVocationalHistoryImpl.setUserId(getUserId());
		extVocationalHistoryImpl.setCreateDate(getCreateDate());
		extVocationalHistoryImpl.setModifiedDate(getModifiedDate());
		extVocationalHistoryImpl.setLocationOrSetting(getLocationOrSetting());
		extVocationalHistoryImpl.setCity(getCity());
		extVocationalHistoryImpl.setRegionId(getRegionId());
		extVocationalHistoryImpl.setCountryId(getCountryId());
		extVocationalHistoryImpl.setStartDateOfService(getStartDateOfService());
		extVocationalHistoryImpl.setEndDateOfService(getEndDateOfService());
		extVocationalHistoryImpl.setTitleOrPosition(getTitleOrPosition());
		extVocationalHistoryImpl.setJobTypeId(getJobTypeId());

		extVocationalHistoryImpl.resetOriginalValues();

		return extVocationalHistoryImpl;
	}

	@Override
	public int compareTo(ExtVocationalHistory extVocationalHistory) {
		int value = 0;

		value = DateUtil.compareTo(getStartDateOfService(),
				extVocationalHistory.getStartDateOfService());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getEndDateOfService(),
				extVocationalHistory.getEndDateOfService());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ExtVocationalHistory)) {
			return false;
		}

		ExtVocationalHistory extVocationalHistory = (ExtVocationalHistory)obj;

		long primaryKey = extVocationalHistory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ExtVocationalHistoryModelImpl extVocationalHistoryModelImpl = this;

		extVocationalHistoryModelImpl._originalUserId = extVocationalHistoryModelImpl._userId;

		extVocationalHistoryModelImpl._setOriginalUserId = false;

		extVocationalHistoryModelImpl._setModifiedDate = false;

		extVocationalHistoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ExtVocationalHistory> toCacheModel() {
		ExtVocationalHistoryCacheModel extVocationalHistoryCacheModel = new ExtVocationalHistoryCacheModel();

		extVocationalHistoryCacheModel.extVocationalHistoryId = getExtVocationalHistoryId();

		extVocationalHistoryCacheModel.companyId = getCompanyId();

		extVocationalHistoryCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			extVocationalHistoryCacheModel.createDate = createDate.getTime();
		}
		else {
			extVocationalHistoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			extVocationalHistoryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			extVocationalHistoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		extVocationalHistoryCacheModel.locationOrSetting = getLocationOrSetting();

		String locationOrSetting = extVocationalHistoryCacheModel.locationOrSetting;

		if ((locationOrSetting != null) && (locationOrSetting.length() == 0)) {
			extVocationalHistoryCacheModel.locationOrSetting = null;
		}

		extVocationalHistoryCacheModel.city = getCity();

		String city = extVocationalHistoryCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			extVocationalHistoryCacheModel.city = null;
		}

		extVocationalHistoryCacheModel.regionId = getRegionId();

		extVocationalHistoryCacheModel.countryId = getCountryId();

		Date startDateOfService = getStartDateOfService();

		if (startDateOfService != null) {
			extVocationalHistoryCacheModel.startDateOfService = startDateOfService.getTime();
		}
		else {
			extVocationalHistoryCacheModel.startDateOfService = Long.MIN_VALUE;
		}

		Date endDateOfService = getEndDateOfService();

		if (endDateOfService != null) {
			extVocationalHistoryCacheModel.endDateOfService = endDateOfService.getTime();
		}
		else {
			extVocationalHistoryCacheModel.endDateOfService = Long.MIN_VALUE;
		}

		extVocationalHistoryCacheModel.titleOrPosition = getTitleOrPosition();

		String titleOrPosition = extVocationalHistoryCacheModel.titleOrPosition;

		if ((titleOrPosition != null) && (titleOrPosition.length() == 0)) {
			extVocationalHistoryCacheModel.titleOrPosition = null;
		}

		extVocationalHistoryCacheModel.jobTypeId = getJobTypeId();

		return extVocationalHistoryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{extVocationalHistoryId=");
		sb.append(getExtVocationalHistoryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", locationOrSetting=");
		sb.append(getLocationOrSetting());
		sb.append(", city=");
		sb.append(getCity());
		sb.append(", regionId=");
		sb.append(getRegionId());
		sb.append(", countryId=");
		sb.append(getCountryId());
		sb.append(", startDateOfService=");
		sb.append(getStartDateOfService());
		sb.append(", endDateOfService=");
		sb.append(getEndDateOfService());
		sb.append(", titleOrPosition=");
		sb.append(getTitleOrPosition());
		sb.append(", jobTypeId=");
		sb.append(getJobTypeId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("ucc.portal.model.ExtVocationalHistory");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>extVocationalHistoryId</column-name><column-value><![CDATA[");
		sb.append(getExtVocationalHistoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>locationOrSetting</column-name><column-value><![CDATA[");
		sb.append(getLocationOrSetting());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>city</column-name><column-value><![CDATA[");
		sb.append(getCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>regionId</column-name><column-value><![CDATA[");
		sb.append(getRegionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>countryId</column-name><column-value><![CDATA[");
		sb.append(getCountryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDateOfService</column-name><column-value><![CDATA[");
		sb.append(getStartDateOfService());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDateOfService</column-name><column-value><![CDATA[");
		sb.append(getEndDateOfService());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>titleOrPosition</column-name><column-value><![CDATA[");
		sb.append(getTitleOrPosition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jobTypeId</column-name><column-value><![CDATA[");
		sb.append(getJobTypeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ExtVocationalHistory.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ExtVocationalHistory.class, ModelWrapper.class
		};
	private long _extVocationalHistoryId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _locationOrSetting;
	private String _city;
	private long _regionId;
	private long _countryId;
	private Date _startDateOfService;
	private Date _endDateOfService;
	private String _titleOrPosition;
	private int _jobTypeId;
	private long _columnBitmask;
	private ExtVocationalHistory _escapedModel;
}