/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model.impl;

import aQute.bnd.annotation.ProviderType;

import ucc.portal.model.UccConference;

import ucc.portal.service.UccConferenceLocalServiceUtil;

/**
 * The extended model base implementation for the UccConference service. Represents a row in the &quot;UCC_Data_Warehouse.dbo.Conference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UccConferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UccConferenceImpl
 * @see UccConference
 * @generated
 */
@ProviderType
public abstract class UccConferenceBaseImpl extends UccConferenceModelImpl
	implements UccConference {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ucc conference model instance should use the {@link UccConference} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UccConferenceLocalServiceUtil.addUccConference(this);
		}
		else {
			UccConferenceLocalServiceUtil.updateUccConference(this);
		}
	}
}