/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import ucc.portal.service.persistence.CExtChurchFinancesIncomeOtherPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CExtChurchFinancesIncomeOther service. Represents a row in the &quot;UCC_CExtChurchFinancesIncomeOther&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.CExtChurchFinancesIncomeOtherModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.CExtChurchFinancesIncomeOtherImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CExtChurchFinancesIncomeOther
 * @see ucc.portal.model.impl.CExtChurchFinancesIncomeOtherImpl
 * @see ucc.portal.model.impl.CExtChurchFinancesIncomeOtherModelImpl
 * @generated
 */
@ProviderType
public interface CExtChurchFinancesIncomeOtherModel extends BaseModel<CExtChurchFinancesIncomeOther>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c ext church finances income other model instance should use the {@link CExtChurchFinancesIncomeOther} interface instead.
	 */

	/**
	 * Returns the primary key of this c ext church finances income other.
	 *
	 * @return the primary key of this c ext church finances income other
	 */
	public CExtChurchFinancesIncomeOtherPK getPrimaryKey();

	/**
	 * Sets the primary key of this c ext church finances income other.
	 *
	 * @param primaryKey the primary key of this c ext church finances income other
	 */
	public void setPrimaryKey(CExtChurchFinancesIncomeOtherPK primaryKey);

	/**
	 * Returns the organization ID of this c ext church finances income other.
	 *
	 * @return the organization ID of this c ext church finances income other
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this c ext church finances income other.
	 *
	 * @param organizationId the organization ID of this c ext church finances income other
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the cext church finances income other ID of this c ext church finances income other.
	 *
	 * @return the cext church finances income other ID of this c ext church finances income other
	 */
	public long getCextChurchFinancesIncomeOtherId();

	/**
	 * Sets the cext church finances income other ID of this c ext church finances income other.
	 *
	 * @param cextChurchFinancesIncomeOtherId the cext church finances income other ID of this c ext church finances income other
	 */
	public void setCextChurchFinancesIncomeOtherId(
		long cextChurchFinancesIncomeOtherId);

	/**
	 * Returns the company ID of this c ext church finances income other.
	 *
	 * @return the company ID of this c ext church finances income other
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this c ext church finances income other.
	 *
	 * @param companyId the company ID of this c ext church finances income other
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this c ext church finances income other.
	 *
	 * @return the user ID of this c ext church finances income other
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this c ext church finances income other.
	 *
	 * @param userId the user ID of this c ext church finances income other
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c ext church finances income other.
	 *
	 * @return the user uuid of this c ext church finances income other
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this c ext church finances income other.
	 *
	 * @param userUuid the user uuid of this c ext church finances income other
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this c ext church finances income other.
	 *
	 * @return the create date of this c ext church finances income other
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this c ext church finances income other.
	 *
	 * @param createDate the create date of this c ext church finances income other
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c ext church finances income other.
	 *
	 * @return the modified date of this c ext church finances income other
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c ext church finances income other.
	 *
	 * @param modifiedDate the modified date of this c ext church finances income other
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fn income other of this c ext church finances income other.
	 *
	 * @return the fn income other of this c ext church finances income other
	 */
	public int getFnIncomeOther();

	/**
	 * Sets the fn income other of this c ext church finances income other.
	 *
	 * @param fnIncomeOther the fn income other of this c ext church finances income other
	 */
	public void setFnIncomeOther(int fnIncomeOther);

	/**
	 * Returns the fn income other description of this c ext church finances income other.
	 *
	 * @return the fn income other description of this c ext church finances income other
	 */
	@AutoEscape
	public String getFnIncomeOtherDescription();

	/**
	 * Sets the fn income other description of this c ext church finances income other.
	 *
	 * @param fnIncomeOtherDescription the fn income other description of this c ext church finances income other
	 */
	public void setFnIncomeOtherDescription(String fnIncomeOtherDescription);

	/**
	 * Returns the fn priority of this c ext church finances income other.
	 *
	 * @return the fn priority of this c ext church finances income other
	 */
	public double getFnPriority();

	/**
	 * Sets the fn priority of this c ext church finances income other.
	 *
	 * @param fnPriority the fn priority of this c ext church finances income other
	 */
	public void setFnPriority(double fnPriority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		CExtChurchFinancesIncomeOther cExtChurchFinancesIncomeOther);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CExtChurchFinancesIncomeOther> toCacheModel();

	@Override
	public CExtChurchFinancesIncomeOther toEscapedModel();

	@Override
	public CExtChurchFinancesIncomeOther toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}