/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import ucc.portal.service.persistence.CExtRealEstateCampaignPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CExtRealEstateCampaign service. Represents a row in the &quot;UCC_CExtRealEstateCampaign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.CExtRealEstateCampaignModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.CExtRealEstateCampaignImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CExtRealEstateCampaign
 * @see ucc.portal.model.impl.CExtRealEstateCampaignImpl
 * @see ucc.portal.model.impl.CExtRealEstateCampaignModelImpl
 * @generated
 */
@ProviderType
public interface CExtRealEstateCampaignModel extends BaseModel<CExtRealEstateCampaign>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c ext real estate campaign model instance should use the {@link CExtRealEstateCampaign} interface instead.
	 */

	/**
	 * Returns the primary key of this c ext real estate campaign.
	 *
	 * @return the primary key of this c ext real estate campaign
	 */
	public CExtRealEstateCampaignPK getPrimaryKey();

	/**
	 * Sets the primary key of this c ext real estate campaign.
	 *
	 * @param primaryKey the primary key of this c ext real estate campaign
	 */
	public void setPrimaryKey(CExtRealEstateCampaignPK primaryKey);

	/**
	 * Returns the organization ID of this c ext real estate campaign.
	 *
	 * @return the organization ID of this c ext real estate campaign
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this c ext real estate campaign.
	 *
	 * @param organizationId the organization ID of this c ext real estate campaign
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the cext real estate campaign ID of this c ext real estate campaign.
	 *
	 * @return the cext real estate campaign ID of this c ext real estate campaign
	 */
	public long getCextRealEstateCampaignId();

	/**
	 * Sets the cext real estate campaign ID of this c ext real estate campaign.
	 *
	 * @param cextRealEstateCampaignId the cext real estate campaign ID of this c ext real estate campaign
	 */
	public void setCextRealEstateCampaignId(long cextRealEstateCampaignId);

	/**
	 * Returns the company ID of this c ext real estate campaign.
	 *
	 * @return the company ID of this c ext real estate campaign
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this c ext real estate campaign.
	 *
	 * @param companyId the company ID of this c ext real estate campaign
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this c ext real estate campaign.
	 *
	 * @return the user ID of this c ext real estate campaign
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this c ext real estate campaign.
	 *
	 * @param userId the user ID of this c ext real estate campaign
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c ext real estate campaign.
	 *
	 * @return the user uuid of this c ext real estate campaign
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this c ext real estate campaign.
	 *
	 * @param userUuid the user uuid of this c ext real estate campaign
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this c ext real estate campaign.
	 *
	 * @return the create date of this c ext real estate campaign
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this c ext real estate campaign.
	 *
	 * @param createDate the create date of this c ext real estate campaign
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c ext real estate campaign.
	 *
	 * @return the modified date of this c ext real estate campaign
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c ext real estate campaign.
	 *
	 * @param modifiedDate the modified date of this c ext real estate campaign
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the re year of this c ext real estate campaign.
	 *
	 * @return the re year of this c ext real estate campaign
	 */
	public int getReYear();

	/**
	 * Sets the re year of this c ext real estate campaign.
	 *
	 * @param reYear the re year of this c ext real estate campaign
	 */
	public void setReYear(int reYear);

	/**
	 * Returns the re underway anticipated of this c ext real estate campaign.
	 *
	 * @return the re underway anticipated of this c ext real estate campaign
	 */
	public boolean getReUnderwayAnticipated();

	/**
	 * Returns <code>true</code> if this c ext real estate campaign is re underway anticipated.
	 *
	 * @return <code>true</code> if this c ext real estate campaign is re underway anticipated; <code>false</code> otherwise
	 */
	public boolean isReUnderwayAnticipated();

	/**
	 * Sets whether this c ext real estate campaign is re underway anticipated.
	 *
	 * @param reUnderwayAnticipated the re underway anticipated of this c ext real estate campaign
	 */
	public void setReUnderwayAnticipated(boolean reUnderwayAnticipated);

	/**
	 * Returns the re goal of this c ext real estate campaign.
	 *
	 * @return the re goal of this c ext real estate campaign
	 */
	public int getReGoal();

	/**
	 * Sets the re goal of this c ext real estate campaign.
	 *
	 * @param reGoal the re goal of this c ext real estate campaign
	 */
	public void setReGoal(int reGoal);

	/**
	 * Returns the re result of this c ext real estate campaign.
	 *
	 * @return the re result of this c ext real estate campaign
	 */
	public int getReResult();

	/**
	 * Sets the re result of this c ext real estate campaign.
	 *
	 * @param reResult the re result of this c ext real estate campaign
	 */
	public void setReResult(int reResult);

	/**
	 * Returns the re purpose of this c ext real estate campaign.
	 *
	 * @return the re purpose of this c ext real estate campaign
	 */
	@AutoEscape
	public String getRePurpose();

	/**
	 * Sets the re purpose of this c ext real estate campaign.
	 *
	 * @param rePurpose the re purpose of this c ext real estate campaign
	 */
	public void setRePurpose(String rePurpose);

	/**
	 * Returns the re impact of this c ext real estate campaign.
	 *
	 * @return the re impact of this c ext real estate campaign
	 */
	@AutoEscape
	public String getReImpact();

	/**
	 * Sets the re impact of this c ext real estate campaign.
	 *
	 * @param reImpact the re impact of this c ext real estate campaign
	 */
	public void setReImpact(String reImpact);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CExtRealEstateCampaign cExtRealEstateCampaign);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CExtRealEstateCampaign> toCacheModel();

	@Override
	public CExtRealEstateCampaign toEscapedModel();

	@Override
	public CExtRealEstateCampaign toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}