/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import ucc.portal.service.persistence.CExtStaffingChurchPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CExtStaffingChurch service. Represents a row in the &quot;UCC_CExtStaffingChurch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.CExtStaffingChurchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.CExtStaffingChurchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CExtStaffingChurch
 * @see ucc.portal.model.impl.CExtStaffingChurchImpl
 * @see ucc.portal.model.impl.CExtStaffingChurchModelImpl
 * @generated
 */
@ProviderType
public interface CExtStaffingChurchModel extends BaseModel<CExtStaffingChurch>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c ext staffing church model instance should use the {@link CExtStaffingChurch} interface instead.
	 */

	/**
	 * Returns the primary key of this c ext staffing church.
	 *
	 * @return the primary key of this c ext staffing church
	 */
	public CExtStaffingChurchPK getPrimaryKey();

	/**
	 * Sets the primary key of this c ext staffing church.
	 *
	 * @param primaryKey the primary key of this c ext staffing church
	 */
	public void setPrimaryKey(CExtStaffingChurchPK primaryKey);

	/**
	 * Returns the organization ID of this c ext staffing church.
	 *
	 * @return the organization ID of this c ext staffing church
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this c ext staffing church.
	 *
	 * @param organizationId the organization ID of this c ext staffing church
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the cext staffing church ID of this c ext staffing church.
	 *
	 * @return the cext staffing church ID of this c ext staffing church
	 */
	public long getCextStaffingChurchId();

	/**
	 * Sets the cext staffing church ID of this c ext staffing church.
	 *
	 * @param cextStaffingChurchId the cext staffing church ID of this c ext staffing church
	 */
	public void setCextStaffingChurchId(long cextStaffingChurchId);

	/**
	 * Returns the company ID of this c ext staffing church.
	 *
	 * @return the company ID of this c ext staffing church
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this c ext staffing church.
	 *
	 * @param companyId the company ID of this c ext staffing church
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this c ext staffing church.
	 *
	 * @return the user ID of this c ext staffing church
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this c ext staffing church.
	 *
	 * @param userId the user ID of this c ext staffing church
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c ext staffing church.
	 *
	 * @return the user uuid of this c ext staffing church
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this c ext staffing church.
	 *
	 * @param userUuid the user uuid of this c ext staffing church
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this c ext staffing church.
	 *
	 * @return the create date of this c ext staffing church
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this c ext staffing church.
	 *
	 * @param createDate the create date of this c ext staffing church
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c ext staffing church.
	 *
	 * @return the modified date of this c ext staffing church
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c ext staffing church.
	 *
	 * @param modifiedDate the modified date of this c ext staffing church
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the sf position of this c ext staffing church.
	 *
	 * @return the sf position of this c ext staffing church
	 */
	@AutoEscape
	public String getSfPosition();

	/**
	 * Sets the sf position of this c ext staffing church.
	 *
	 * @param sfPosition the sf position of this c ext staffing church
	 */
	public void setSfPosition(String sfPosition);

	/**
	 * Returns the sf head of staff of this c ext staffing church.
	 *
	 * @return the sf head of staff of this c ext staffing church
	 */
	public boolean getSfHeadOfStaff();

	/**
	 * Returns <code>true</code> if this c ext staffing church is sf head of staff.
	 *
	 * @return <code>true</code> if this c ext staffing church is sf head of staff; <code>false</code> otherwise
	 */
	public boolean isSfHeadOfStaff();

	/**
	 * Sets whether this c ext staffing church is sf head of staff.
	 *
	 * @param sfHeadOfStaff the sf head of staff of this c ext staffing church
	 */
	public void setSfHeadOfStaff(boolean sfHeadOfStaff);

	/**
	 * Returns the sf compensation of this c ext staffing church.
	 *
	 * @return the sf compensation of this c ext staffing church
	 */
	@AutoEscape
	public String getSfCompensation();

	/**
	 * Sets the sf compensation of this c ext staffing church.
	 *
	 * @param sfCompensation the sf compensation of this c ext staffing church
	 */
	public void setSfCompensation(String sfCompensation);

	/**
	 * Returns the sf supervised by of this c ext staffing church.
	 *
	 * @return the sf supervised by of this c ext staffing church
	 */
	@AutoEscape
	public String getSfSupervisedBy();

	/**
	 * Sets the sf supervised by of this c ext staffing church.
	 *
	 * @param sfSupervisedBy the sf supervised by of this c ext staffing church
	 */
	public void setSfSupervisedBy(String sfSupervisedBy);

	/**
	 * Returns the sf current tenure of this c ext staffing church.
	 *
	 * @return the sf current tenure of this c ext staffing church
	 */
	@AutoEscape
	public String getSfCurrentTenure();

	/**
	 * Sets the sf current tenure of this c ext staffing church.
	 *
	 * @param sfCurrentTenure the sf current tenure of this c ext staffing church
	 */
	public void setSfCurrentTenure(String sfCurrentTenure);

	/**
	 * Returns the sf priority of this c ext staffing church.
	 *
	 * @return the sf priority of this c ext staffing church
	 */
	public double getSfPriority();

	/**
	 * Sets the sf priority of this c ext staffing church.
	 *
	 * @param sfPriority the sf priority of this c ext staffing church
	 */
	public void setSfPriority(double sfPriority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CExtStaffingChurch cExtStaffingChurch);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CExtStaffingChurch> toCacheModel();

	@Override
	public CExtStaffingChurch toEscapedModel();

	@Override
	public CExtStaffingChurch toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}