/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import ucc.portal.service.persistence.CExtStaffingCongregationPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CExtStaffingCongregation service. Represents a row in the &quot;UCC_CExtStaffingCongregation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.CExtStaffingCongregationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.CExtStaffingCongregationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CExtStaffingCongregation
 * @see ucc.portal.model.impl.CExtStaffingCongregationImpl
 * @see ucc.portal.model.impl.CExtStaffingCongregationModelImpl
 * @generated
 */
@ProviderType
public interface CExtStaffingCongregationModel extends BaseModel<CExtStaffingCongregation>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c ext staffing congregation model instance should use the {@link CExtStaffingCongregation} interface instead.
	 */

	/**
	 * Returns the primary key of this c ext staffing congregation.
	 *
	 * @return the primary key of this c ext staffing congregation
	 */
	public CExtStaffingCongregationPK getPrimaryKey();

	/**
	 * Sets the primary key of this c ext staffing congregation.
	 *
	 * @param primaryKey the primary key of this c ext staffing congregation
	 */
	public void setPrimaryKey(CExtStaffingCongregationPK primaryKey);

	/**
	 * Returns the organization ID of this c ext staffing congregation.
	 *
	 * @return the organization ID of this c ext staffing congregation
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this c ext staffing congregation.
	 *
	 * @param organizationId the organization ID of this c ext staffing congregation
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the cext staffing congregation ID of this c ext staffing congregation.
	 *
	 * @return the cext staffing congregation ID of this c ext staffing congregation
	 */
	public long getCextStaffingCongregationId();

	/**
	 * Sets the cext staffing congregation ID of this c ext staffing congregation.
	 *
	 * @param cextStaffingCongregationId the cext staffing congregation ID of this c ext staffing congregation
	 */
	public void setCextStaffingCongregationId(long cextStaffingCongregationId);

	/**
	 * Returns the company ID of this c ext staffing congregation.
	 *
	 * @return the company ID of this c ext staffing congregation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this c ext staffing congregation.
	 *
	 * @param companyId the company ID of this c ext staffing congregation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this c ext staffing congregation.
	 *
	 * @return the user ID of this c ext staffing congregation
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this c ext staffing congregation.
	 *
	 * @param userId the user ID of this c ext staffing congregation
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c ext staffing congregation.
	 *
	 * @return the user uuid of this c ext staffing congregation
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this c ext staffing congregation.
	 *
	 * @param userUuid the user uuid of this c ext staffing congregation
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this c ext staffing congregation.
	 *
	 * @return the create date of this c ext staffing congregation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this c ext staffing congregation.
	 *
	 * @param createDate the create date of this c ext staffing congregation
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c ext staffing congregation.
	 *
	 * @return the modified date of this c ext staffing congregation
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c ext staffing congregation.
	 *
	 * @param modifiedDate the modified date of this c ext staffing congregation
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the sf minister name of this c ext staffing congregation.
	 *
	 * @return the sf minister name of this c ext staffing congregation
	 */
	@AutoEscape
	public String getSfMinisterName();

	/**
	 * Sets the sf minister name of this c ext staffing congregation.
	 *
	 * @param sfMinisterName the sf minister name of this c ext staffing congregation
	 */
	public void setSfMinisterName(String sfMinisterName);

	/**
	 * Returns the sf minister retired of this c ext staffing congregation.
	 *
	 * @return the sf minister retired of this c ext staffing congregation
	 */
	public boolean getSfMinisterRetired();

	/**
	 * Returns <code>true</code> if this c ext staffing congregation is sf minister retired.
	 *
	 * @return <code>true</code> if this c ext staffing congregation is sf minister retired; <code>false</code> otherwise
	 */
	public boolean isSfMinisterRetired();

	/**
	 * Sets whether this c ext staffing congregation is sf minister retired.
	 *
	 * @param sfMinisterRetired the sf minister retired of this c ext staffing congregation
	 */
	public void setSfMinisterRetired(boolean sfMinisterRetired);

	/**
	 * Returns the sf minister covenant of this c ext staffing congregation.
	 *
	 * @return the sf minister covenant of this c ext staffing congregation
	 */
	@AutoEscape
	public String getSfMinisterCovenant();

	/**
	 * Sets the sf minister covenant of this c ext staffing congregation.
	 *
	 * @param sfMinisterCovenant the sf minister covenant of this c ext staffing congregation
	 */
	public void setSfMinisterCovenant(String sfMinisterCovenant);

	/**
	 * Returns the sf ministry setting of this c ext staffing congregation.
	 *
	 * @return the sf ministry setting of this c ext staffing congregation
	 */
	@AutoEscape
	public String getSfMinistrySetting();

	/**
	 * Sets the sf ministry setting of this c ext staffing congregation.
	 *
	 * @param sfMinistrySetting the sf ministry setting of this c ext staffing congregation
	 */
	public void setSfMinistrySetting(String sfMinistrySetting);

	/**
	 * Returns the sf ministry role of this c ext staffing congregation.
	 *
	 * @return the sf ministry role of this c ext staffing congregation
	 */
	@AutoEscape
	public String getSfMinistryRole();

	/**
	 * Sets the sf ministry role of this c ext staffing congregation.
	 *
	 * @param sfMinistryRole the sf ministry role of this c ext staffing congregation
	 */
	public void setSfMinistryRole(String sfMinistryRole);

	/**
	 * Returns the sf priority of this c ext staffing congregation.
	 *
	 * @return the sf priority of this c ext staffing congregation
	 */
	public double getSfPriority();

	/**
	 * Sets the sf priority of this c ext staffing congregation.
	 *
	 * @param sfPriority the sf priority of this c ext staffing congregation
	 */
	public void setSfPriority(double sfPriority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CExtStaffingCongregation cExtStaffingCongregation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CExtStaffingCongregation> toCacheModel();

	@Override
	public CExtStaffingCongregation toEscapedModel();

	@Override
	public CExtStaffingCongregation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}