/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CExtOrganization service. Represents a row in the &quot;UCC_CExtOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.CExtOrganizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.CExtOrganizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CExtOrganization
 * @see ucc.portal.model.impl.CExtOrganizationImpl
 * @see ucc.portal.model.impl.CExtOrganizationModelImpl
 * @generated
 */
@ProviderType
public interface CExtOrganizationModel extends BaseModel<CExtOrganization>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c ext organization model instance should use the {@link CExtOrganization} interface instead.
	 */

	/**
	 * Returns the primary key of this c ext organization.
	 *
	 * @return the primary key of this c ext organization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this c ext organization.
	 *
	 * @param primaryKey the primary key of this c ext organization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the organization ID of this c ext organization.
	 *
	 * @return the organization ID of this c ext organization
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this c ext organization.
	 *
	 * @param organizationId the organization ID of this c ext organization
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the company ID of this c ext organization.
	 *
	 * @return the company ID of this c ext organization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this c ext organization.
	 *
	 * @param companyId the company ID of this c ext organization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this c ext organization.
	 *
	 * @return the user ID of this c ext organization
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this c ext organization.
	 *
	 * @param userId the user ID of this c ext organization
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c ext organization.
	 *
	 * @return the user uuid of this c ext organization
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this c ext organization.
	 *
	 * @param userUuid the user uuid of this c ext organization
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this c ext organization.
	 *
	 * @return the create date of this c ext organization
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this c ext organization.
	 *
	 * @param createDate the create date of this c ext organization
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c ext organization.
	 *
	 * @return the modified date of this c ext organization
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c ext organization.
	 *
	 * @param modifiedDate the modified date of this c ext organization
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the di title of this c ext organization.
	 *
	 * @return the di title of this c ext organization
	 */
	@AutoEscape
	public String getDiTitle();

	/**
	 * Sets the di title of this c ext organization.
	 *
	 * @param diTitle the di title of this c ext organization
	 */
	public void setDiTitle(String diTitle);

	/**
	 * Returns the di description of this c ext organization.
	 *
	 * @return the di description of this c ext organization
	 */
	@AutoEscape
	public String getDiDescription();

	/**
	 * Sets the di description of this c ext organization.
	 *
	 * @param diDescription the di description of this c ext organization
	 */
	public void setDiDescription(String diDescription);

	/**
	 * Returns the di complete of this c ext organization.
	 *
	 * @return the di complete of this c ext organization
	 */
	public boolean getDiComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is di complete.
	 *
	 * @return <code>true</code> if this c ext organization is di complete; <code>false</code> otherwise
	 */
	public boolean isDiComplete();

	/**
	 * Sets whether this c ext organization is di complete.
	 *
	 * @param diComplete the di complete of this c ext organization
	 */
	public void setDiComplete(boolean diComplete);

	/**
	 * Returns the rf life of faith of this c ext organization.
	 *
	 * @return the rf life of faith of this c ext organization
	 */
	@AutoEscape
	public String getRfLifeOfFaith();

	/**
	 * Sets the rf life of faith of this c ext organization.
	 *
	 * @param rfLifeOfFaith the rf life of faith of this c ext organization
	 */
	public void setRfLifeOfFaith(String rfLifeOfFaith);

	/**
	 * Returns the rf strengths qualities of this c ext organization.
	 *
	 * @return the rf strengths qualities of this c ext organization
	 */
	@AutoEscape
	public String getRfStrengthsQualities();

	/**
	 * Sets the rf strengths qualities of this c ext organization.
	 *
	 * @param rfStrengthsQualities the rf strengths qualities of this c ext organization
	 */
	public void setRfStrengthsQualities(String rfStrengthsQualities);

	/**
	 * Returns the rf worship of this c ext organization.
	 *
	 * @return the rf worship of this c ext organization
	 */
	@AutoEscape
	public String getRfWorship();

	/**
	 * Sets the rf worship of this c ext organization.
	 *
	 * @param rfWorship the rf worship of this c ext organization
	 */
	public void setRfWorship(String rfWorship);

	/**
	 * Returns the rf education faith vision of this c ext organization.
	 *
	 * @return the rf education faith vision of this c ext organization
	 */
	@AutoEscape
	public String getRfEducationFaithVision();

	/**
	 * Sets the rf education faith vision of this c ext organization.
	 *
	 * @param rfEducationFaithVision the rf education faith vision of this c ext organization
	 */
	public void setRfEducationFaithVision(String rfEducationFaithVision);

	/**
	 * Returns the rf ministry mission of this c ext organization.
	 *
	 * @return the rf ministry mission of this c ext organization
	 */
	@AutoEscape
	public String getRfMinistryMission();

	/**
	 * Sets the rf ministry mission of this c ext organization.
	 *
	 * @param rfMinistryMission the rf ministry mission of this c ext organization
	 */
	public void setRfMinistryMission(String rfMinistryMission);

	/**
	 * Returns the rf meeting hours per month of this c ext organization.
	 *
	 * @return the rf meeting hours per month of this c ext organization
	 */
	@AutoEscape
	public String getRfMeetingHoursPerMonth();

	/**
	 * Sets the rf meeting hours per month of this c ext organization.
	 *
	 * @param rfMeetingHoursPerMonth the rf meeting hours per month of this c ext organization
	 */
	public void setRfMeetingHoursPerMonth(String rfMeetingHoursPerMonth);

	/**
	 * Returns the rf crisis disaster action of this c ext organization.
	 *
	 * @return the rf crisis disaster action of this c ext organization
	 */
	@AutoEscape
	public String getRfCrisisDisasterAction();

	/**
	 * Sets the rf crisis disaster action of this c ext organization.
	 *
	 * @param rfCrisisDisasterAction the rf crisis disaster action of this c ext organization
	 */
	public void setRfCrisisDisasterAction(String rfCrisisDisasterAction);

	/**
	 * Returns the rf minister governance copy of this c ext organization.
	 *
	 * @return the rf minister governance copy of this c ext organization
	 */
	public boolean getRfMinisterGovernanceCopy();

	/**
	 * Returns <code>true</code> if this c ext organization is rf minister governance copy.
	 *
	 * @return <code>true</code> if this c ext organization is rf minister governance copy; <code>false</code> otherwise
	 */
	public boolean isRfMinisterGovernanceCopy();

	/**
	 * Sets whether this c ext organization is rf minister governance copy.
	 *
	 * @param rfMinisterGovernanceCopy the rf minister governance copy of this c ext organization
	 */
	public void setRfMinisterGovernanceCopy(boolean rfMinisterGovernanceCopy);

	/**
	 * Returns the rf complete of this c ext organization.
	 *
	 * @return the rf complete of this c ext organization
	 */
	public boolean getRfComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is rf complete.
	 *
	 * @return <code>true</code> if this c ext organization is rf complete; <code>false</code> otherwise
	 */
	public boolean isRfComplete();

	/**
	 * Sets whether this c ext organization is rf complete.
	 *
	 * @param rfComplete the rf complete of this c ext organization
	 */
	public void setRfComplete(boolean rfComplete);

	/**
	 * Returns the yr file entry ID of this c ext organization.
	 *
	 * @return the yr file entry ID of this c ext organization
	 */
	public long getYrFileEntryId();

	/**
	 * Sets the yr file entry ID of this c ext organization.
	 *
	 * @param yrFileEntryId the yr file entry ID of this c ext organization
	 */
	public void setYrFileEntryId(long yrFileEntryId);

	/**
	 * Returns the yr church response of this c ext organization.
	 *
	 * @return the yr church response of this c ext organization
	 */
	@AutoEscape
	public String getYrChurchResponse();

	/**
	 * Sets the yr church response of this c ext organization.
	 *
	 * @param yrChurchResponse the yr church response of this c ext organization
	 */
	public void setYrChurchResponse(String yrChurchResponse);

	/**
	 * Returns the yr complete of this c ext organization.
	 *
	 * @return the yr complete of this c ext organization
	 */
	public boolean getYrComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is yr complete.
	 *
	 * @return <code>true</code> if this c ext organization is yr complete; <code>false</code> otherwise
	 */
	public boolean isYrComplete();

	/**
	 * Sets whether this c ext organization is yr complete.
	 *
	 * @param yrComplete the yr complete of this c ext organization
	 */
	public void setYrComplete(boolean yrComplete);

	/**
	 * Returns the dg active members of this c ext organization.
	 *
	 * @return the dg active members of this c ext organization
	 */
	public int getDgActiveMembers();

	/**
	 * Sets the dg active members of this c ext organization.
	 *
	 * @param dgActiveMembers the dg active members of this c ext organization
	 */
	public void setDgActiveMembers(int dgActiveMembers);

	/**
	 * Returns the dg active members estimate of this c ext organization.
	 *
	 * @return the dg active members estimate of this c ext organization
	 */
	public boolean getDgActiveMembersEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg active members estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg active members estimate; <code>false</code> otherwise
	 */
	public boolean isDgActiveMembersEstimate();

	/**
	 * Sets whether this c ext organization is dg active members estimate.
	 *
	 * @param dgActiveMembersEstimate the dg active members estimate of this c ext organization
	 */
	public void setDgActiveMembersEstimate(boolean dgActiveMembersEstimate);

	/**
	 * Returns the dg active non members of this c ext organization.
	 *
	 * @return the dg active non members of this c ext organization
	 */
	public int getDgActiveNonMembers();

	/**
	 * Sets the dg active non members of this c ext organization.
	 *
	 * @param dgActiveNonMembers the dg active non members of this c ext organization
	 */
	public void setDgActiveNonMembers(int dgActiveNonMembers);

	/**
	 * Returns the dg active non members estimate of this c ext organization.
	 *
	 * @return the dg active non members estimate of this c ext organization
	 */
	public boolean getDgActiveNonMembersEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg active non members estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg active non members estimate; <code>false</code> otherwise
	 */
	public boolean isDgActiveNonMembersEstimate();

	/**
	 * Sets whether this c ext organization is dg active non members estimate.
	 *
	 * @param dgActiveNonMembersEstimate the dg active non members estimate of this c ext organization
	 */
	public void setDgActiveNonMembersEstimate(
		boolean dgActiveNonMembersEstimate);

	/**
	 * Returns the dg percent more than10 of this c ext organization.
	 *
	 * @return the dg percent more than10 of this c ext organization
	 */
	public int getDgPercentMoreThan10();

	/**
	 * Sets the dg percent more than10 of this c ext organization.
	 *
	 * @param dgPercentMoreThan10 the dg percent more than10 of this c ext organization
	 */
	public void setDgPercentMoreThan10(int dgPercentMoreThan10);

	/**
	 * Returns the dg percent more than10 estimate of this c ext organization.
	 *
	 * @return the dg percent more than10 estimate of this c ext organization
	 */
	public boolean getDgPercentMoreThan10Estimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent more than10 estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent more than10 estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentMoreThan10Estimate();

	/**
	 * Sets whether this c ext organization is dg percent more than10 estimate.
	 *
	 * @param dgPercentMoreThan10Estimate the dg percent more than10 estimate of this c ext organization
	 */
	public void setDgPercentMoreThan10Estimate(
		boolean dgPercentMoreThan10Estimate);

	/**
	 * Returns the dg percent5 to10 of this c ext organization.
	 *
	 * @return the dg percent5 to10 of this c ext organization
	 */
	public int getDgPercent5To10();

	/**
	 * Sets the dg percent5 to10 of this c ext organization.
	 *
	 * @param dgPercent5To10 the dg percent5 to10 of this c ext organization
	 */
	public void setDgPercent5To10(int dgPercent5To10);

	/**
	 * Returns the dg percent5 to10 estimate of this c ext organization.
	 *
	 * @return the dg percent5 to10 estimate of this c ext organization
	 */
	public boolean getDgPercent5To10Estimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent5 to10 estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent5 to10 estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercent5To10Estimate();

	/**
	 * Sets whether this c ext organization is dg percent5 to10 estimate.
	 *
	 * @param dgPercent5To10Estimate the dg percent5 to10 estimate of this c ext organization
	 */
	public void setDgPercent5To10Estimate(boolean dgPercent5To10Estimate);

	/**
	 * Returns the dg percent less than5 of this c ext organization.
	 *
	 * @return the dg percent less than5 of this c ext organization
	 */
	public int getDgPercentLessThan5();

	/**
	 * Sets the dg percent less than5 of this c ext organization.
	 *
	 * @param dgPercentLessThan5 the dg percent less than5 of this c ext organization
	 */
	public void setDgPercentLessThan5(int dgPercentLessThan5);

	/**
	 * Returns the dg percent less than5 estimate of this c ext organization.
	 *
	 * @return the dg percent less than5 estimate of this c ext organization
	 */
	public boolean getDgPercentLessThan5Estimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent less than5 estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent less than5 estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentLessThan5Estimate();

	/**
	 * Sets whether this c ext organization is dg percent less than5 estimate.
	 *
	 * @param dgPercentLessThan5Estimate the dg percent less than5 estimate of this c ext organization
	 */
	public void setDgPercentLessThan5Estimate(
		boolean dgPercentLessThan5Estimate);

	/**
	 * Returns the dg age11 and under of this c ext organization.
	 *
	 * @return the dg age11 and under of this c ext organization
	 */
	public int getDgAge11AndUnder();

	/**
	 * Sets the dg age11 and under of this c ext organization.
	 *
	 * @param dgAge11AndUnder the dg age11 and under of this c ext organization
	 */
	public void setDgAge11AndUnder(int dgAge11AndUnder);

	/**
	 * Returns the dg age12 to17 of this c ext organization.
	 *
	 * @return the dg age12 to17 of this c ext organization
	 */
	public int getDgAge12To17();

	/**
	 * Sets the dg age12 to17 of this c ext organization.
	 *
	 * @param dgAge12To17 the dg age12 to17 of this c ext organization
	 */
	public void setDgAge12To17(int dgAge12To17);

	/**
	 * Returns the dg age18 to24 of this c ext organization.
	 *
	 * @return the dg age18 to24 of this c ext organization
	 */
	public int getDgAge18To24();

	/**
	 * Sets the dg age18 to24 of this c ext organization.
	 *
	 * @param dgAge18To24 the dg age18 to24 of this c ext organization
	 */
	public void setDgAge18To24(int dgAge18To24);

	/**
	 * Returns the dg age25 to34 of this c ext organization.
	 *
	 * @return the dg age25 to34 of this c ext organization
	 */
	public int getDgAge25To34();

	/**
	 * Sets the dg age25 to34 of this c ext organization.
	 *
	 * @param dgAge25To34 the dg age25 to34 of this c ext organization
	 */
	public void setDgAge25To34(int dgAge25To34);

	/**
	 * Returns the dg age35 to44 of this c ext organization.
	 *
	 * @return the dg age35 to44 of this c ext organization
	 */
	public int getDgAge35To44();

	/**
	 * Sets the dg age35 to44 of this c ext organization.
	 *
	 * @param dgAge35To44 the dg age35 to44 of this c ext organization
	 */
	public void setDgAge35To44(int dgAge35To44);

	/**
	 * Returns the dg age45 to54 of this c ext organization.
	 *
	 * @return the dg age45 to54 of this c ext organization
	 */
	public int getDgAge45To54();

	/**
	 * Sets the dg age45 to54 of this c ext organization.
	 *
	 * @param dgAge45To54 the dg age45 to54 of this c ext organization
	 */
	public void setDgAge45To54(int dgAge45To54);

	/**
	 * Returns the dg age55 to64 of this c ext organization.
	 *
	 * @return the dg age55 to64 of this c ext organization
	 */
	public int getDgAge55To64();

	/**
	 * Sets the dg age55 to64 of this c ext organization.
	 *
	 * @param dgAge55To64 the dg age55 to64 of this c ext organization
	 */
	public void setDgAge55To64(int dgAge55To64);

	/**
	 * Returns the dg age65 to74 of this c ext organization.
	 *
	 * @return the dg age65 to74 of this c ext organization
	 */
	public int getDgAge65To74();

	/**
	 * Sets the dg age65 to74 of this c ext organization.
	 *
	 * @param dgAge65To74 the dg age65 to74 of this c ext organization
	 */
	public void setDgAge65To74(int dgAge65To74);

	/**
	 * Returns the dg age75 and over of this c ext organization.
	 *
	 * @return the dg age75 and over of this c ext organization
	 */
	public int getDgAge75AndOver();

	/**
	 * Sets the dg age75 and over of this c ext organization.
	 *
	 * @param dgAge75AndOver the dg age75 and over of this c ext organization
	 */
	public void setDgAge75AndOver(int dgAge75AndOver);

	/**
	 * Returns the dg all ages estimate of this c ext organization.
	 *
	 * @return the dg all ages estimate of this c ext organization
	 */
	public boolean getDgAllAgesEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg all ages estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg all ages estimate; <code>false</code> otherwise
	 */
	public boolean isDgAllAgesEstimate();

	/**
	 * Sets whether this c ext organization is dg all ages estimate.
	 *
	 * @param dgAllAgesEstimate the dg all ages estimate of this c ext organization
	 */
	public void setDgAllAgesEstimate(boolean dgAllAgesEstimate);

	/**
	 * Returns the dg percent single under35 of this c ext organization.
	 *
	 * @return the dg percent single under35 of this c ext organization
	 */
	public int getDgPercentSingleUnder35();

	/**
	 * Sets the dg percent single under35 of this c ext organization.
	 *
	 * @param dgPercentSingleUnder35 the dg percent single under35 of this c ext organization
	 */
	public void setDgPercentSingleUnder35(int dgPercentSingleUnder35);

	/**
	 * Returns the dg percent single under35 estimate of this c ext organization.
	 *
	 * @return the dg percent single under35 estimate of this c ext organization
	 */
	public boolean getDgPercentSingleUnder35Estimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent single under35 estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent single under35 estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentSingleUnder35Estimate();

	/**
	 * Sets whether this c ext organization is dg percent single under35 estimate.
	 *
	 * @param dgPercentSingleUnder35Estimate the dg percent single under35 estimate of this c ext organization
	 */
	public void setDgPercentSingleUnder35Estimate(
		boolean dgPercentSingleUnder35Estimate);

	/**
	 * Returns the dg percent with minors of this c ext organization.
	 *
	 * @return the dg percent with minors of this c ext organization
	 */
	public int getDgPercentWithMinors();

	/**
	 * Sets the dg percent with minors of this c ext organization.
	 *
	 * @param dgPercentWithMinors the dg percent with minors of this c ext organization
	 */
	public void setDgPercentWithMinors(int dgPercentWithMinors);

	/**
	 * Returns the dg percent with minors estimate of this c ext organization.
	 *
	 * @return the dg percent with minors estimate of this c ext organization
	 */
	public boolean getDgPercentWithMinorsEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent with minors estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent with minors estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentWithMinorsEstimate();

	/**
	 * Sets whether this c ext organization is dg percent with minors estimate.
	 *
	 * @param dgPercentWithMinorsEstimate the dg percent with minors estimate of this c ext organization
	 */
	public void setDgPercentWithMinorsEstimate(
		boolean dgPercentWithMinorsEstimate);

	/**
	 * Returns the dg percent single35 to65 of this c ext organization.
	 *
	 * @return the dg percent single35 to65 of this c ext organization
	 */
	public int getDgPercentSingle35To65();

	/**
	 * Sets the dg percent single35 to65 of this c ext organization.
	 *
	 * @param dgPercentSingle35To65 the dg percent single35 to65 of this c ext organization
	 */
	public void setDgPercentSingle35To65(int dgPercentSingle35To65);

	/**
	 * Returns the dg percent single35 to65 estimate of this c ext organization.
	 *
	 * @return the dg percent single35 to65 estimate of this c ext organization
	 */
	public boolean getDgPercentSingle35To65Estimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent single35 to65 estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent single35 to65 estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentSingle35To65Estimate();

	/**
	 * Sets whether this c ext organization is dg percent single35 to65 estimate.
	 *
	 * @param dgPercentSingle35To65Estimate the dg percent single35 to65 estimate of this c ext organization
	 */
	public void setDgPercentSingle35To65Estimate(
		boolean dgPercentSingle35To65Estimate);

	/**
	 * Returns the dg percent joint no minors of this c ext organization.
	 *
	 * @return the dg percent joint no minors of this c ext organization
	 */
	public int getDgPercentJointNoMinors();

	/**
	 * Sets the dg percent joint no minors of this c ext organization.
	 *
	 * @param dgPercentJointNoMinors the dg percent joint no minors of this c ext organization
	 */
	public void setDgPercentJointNoMinors(int dgPercentJointNoMinors);

	/**
	 * Returns the dg percent joint no minors estimate of this c ext organization.
	 *
	 * @return the dg percent joint no minors estimate of this c ext organization
	 */
	public boolean getDgPercentJointNoMinorsEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent joint no minors estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent joint no minors estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentJointNoMinorsEstimate();

	/**
	 * Sets whether this c ext organization is dg percent joint no minors estimate.
	 *
	 * @param dgPercentJointNoMinorsEstimate the dg percent joint no minors estimate of this c ext organization
	 */
	public void setDgPercentJointNoMinorsEstimate(
		boolean dgPercentJointNoMinorsEstimate);

	/**
	 * Returns the dg percent single over65 of this c ext organization.
	 *
	 * @return the dg percent single over65 of this c ext organization
	 */
	public int getDgPercentSingleOver65();

	/**
	 * Sets the dg percent single over65 of this c ext organization.
	 *
	 * @param dgPercentSingleOver65 the dg percent single over65 of this c ext organization
	 */
	public void setDgPercentSingleOver65(int dgPercentSingleOver65);

	/**
	 * Returns the dg percent single over65 estimate of this c ext organization.
	 *
	 * @return the dg percent single over65 estimate of this c ext organization
	 */
	public boolean getDgPercentSingleOver65Estimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent single over65 estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent single over65 estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentSingleOver65Estimate();

	/**
	 * Sets whether this c ext organization is dg percent single over65 estimate.
	 *
	 * @param dgPercentSingleOver65Estimate the dg percent single over65 estimate of this c ext organization
	 */
	public void setDgPercentSingleOver65Estimate(
		boolean dgPercentSingleOver65Estimate);

	/**
	 * Returns the dg percent high school of this c ext organization.
	 *
	 * @return the dg percent high school of this c ext organization
	 */
	public int getDgPercentHighSchool();

	/**
	 * Sets the dg percent high school of this c ext organization.
	 *
	 * @param dgPercentHighSchool the dg percent high school of this c ext organization
	 */
	public void setDgPercentHighSchool(int dgPercentHighSchool);

	/**
	 * Returns the dg percent high school estimate of this c ext organization.
	 *
	 * @return the dg percent high school estimate of this c ext organization
	 */
	public boolean getDgPercentHighSchoolEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent high school estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent high school estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentHighSchoolEstimate();

	/**
	 * Sets whether this c ext organization is dg percent high school estimate.
	 *
	 * @param dgPercentHighSchoolEstimate the dg percent high school estimate of this c ext organization
	 */
	public void setDgPercentHighSchoolEstimate(
		boolean dgPercentHighSchoolEstimate);

	/**
	 * Returns the dg percent college of this c ext organization.
	 *
	 * @return the dg percent college of this c ext organization
	 */
	public int getDgPercentCollege();

	/**
	 * Sets the dg percent college of this c ext organization.
	 *
	 * @param dgPercentCollege the dg percent college of this c ext organization
	 */
	public void setDgPercentCollege(int dgPercentCollege);

	/**
	 * Returns the dg percent college estimate of this c ext organization.
	 *
	 * @return the dg percent college estimate of this c ext organization
	 */
	public boolean getDgPercentCollegeEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent college estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent college estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentCollegeEstimate();

	/**
	 * Sets whether this c ext organization is dg percent college estimate.
	 *
	 * @param dgPercentCollegeEstimate the dg percent college estimate of this c ext organization
	 */
	public void setDgPercentCollegeEstimate(boolean dgPercentCollegeEstimate);

	/**
	 * Returns the dg percent graduate school of this c ext organization.
	 *
	 * @return the dg percent graduate school of this c ext organization
	 */
	public int getDgPercentGraduateSchool();

	/**
	 * Sets the dg percent graduate school of this c ext organization.
	 *
	 * @param dgPercentGraduateSchool the dg percent graduate school of this c ext organization
	 */
	public void setDgPercentGraduateSchool(int dgPercentGraduateSchool);

	/**
	 * Returns the dg percent graduate school estimate of this c ext organization.
	 *
	 * @return the dg percent graduate school estimate of this c ext organization
	 */
	public boolean getDgPercentGraduateSchoolEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent graduate school estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent graduate school estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentGraduateSchoolEstimate();

	/**
	 * Sets whether this c ext organization is dg percent graduate school estimate.
	 *
	 * @param dgPercentGraduateSchoolEstimate the dg percent graduate school estimate of this c ext organization
	 */
	public void setDgPercentGraduateSchoolEstimate(
		boolean dgPercentGraduateSchoolEstimate);

	/**
	 * Returns the dg percent specialty training of this c ext organization.
	 *
	 * @return the dg percent specialty training of this c ext organization
	 */
	public int getDgPercentSpecialtyTraining();

	/**
	 * Sets the dg percent specialty training of this c ext organization.
	 *
	 * @param dgPercentSpecialtyTraining the dg percent specialty training of this c ext organization
	 */
	public void setDgPercentSpecialtyTraining(int dgPercentSpecialtyTraining);

	/**
	 * Returns the dg percent specialty training estimate of this c ext organization.
	 *
	 * @return the dg percent specialty training estimate of this c ext organization
	 */
	public boolean getDgPercentSpecialtyTrainingEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent specialty training estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent specialty training estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentSpecialtyTrainingEstimate();

	/**
	 * Sets whether this c ext organization is dg percent specialty training estimate.
	 *
	 * @param dgPercentSpecialtyTrainingEstimate the dg percent specialty training estimate of this c ext organization
	 */
	public void setDgPercentSpecialtyTrainingEstimate(
		boolean dgPercentSpecialtyTrainingEstimate);

	/**
	 * Returns the dg percent other education of this c ext organization.
	 *
	 * @return the dg percent other education of this c ext organization
	 */
	public int getDgPercentOtherEducation();

	/**
	 * Sets the dg percent other education of this c ext organization.
	 *
	 * @param dgPercentOtherEducation the dg percent other education of this c ext organization
	 */
	public void setDgPercentOtherEducation(int dgPercentOtherEducation);

	/**
	 * Returns the dg percent other education estimate of this c ext organization.
	 *
	 * @return the dg percent other education estimate of this c ext organization
	 */
	public boolean getDgPercentOtherEducationEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent other education estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent other education estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentOtherEducationEstimate();

	/**
	 * Sets whether this c ext organization is dg percent other education estimate.
	 *
	 * @param dgPercentOtherEducationEstimate the dg percent other education estimate of this c ext organization
	 */
	public void setDgPercentOtherEducationEstimate(
		boolean dgPercentOtherEducationEstimate);

	/**
	 * Returns the dg percent other education description of this c ext organization.
	 *
	 * @return the dg percent other education description of this c ext organization
	 */
	@AutoEscape
	public String getDgPercentOtherEducationDescription();

	/**
	 * Sets the dg percent other education description of this c ext organization.
	 *
	 * @param dgPercentOtherEducationDescription the dg percent other education description of this c ext organization
	 */
	public void setDgPercentOtherEducationDescription(
		String dgPercentOtherEducationDescription);

	/**
	 * Returns the dg percent employed of this c ext organization.
	 *
	 * @return the dg percent employed of this c ext organization
	 */
	public int getDgPercentEmployed();

	/**
	 * Sets the dg percent employed of this c ext organization.
	 *
	 * @param dgPercentEmployed the dg percent employed of this c ext organization
	 */
	public void setDgPercentEmployed(int dgPercentEmployed);

	/**
	 * Returns the dg percent employed estimate of this c ext organization.
	 *
	 * @return the dg percent employed estimate of this c ext organization
	 */
	public boolean getDgPercentEmployedEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent employed estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent employed estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentEmployedEstimate();

	/**
	 * Sets whether this c ext organization is dg percent employed estimate.
	 *
	 * @param dgPercentEmployedEstimate the dg percent employed estimate of this c ext organization
	 */
	public void setDgPercentEmployedEstimate(boolean dgPercentEmployedEstimate);

	/**
	 * Returns the dg percent not fully employed of this c ext organization.
	 *
	 * @return the dg percent not fully employed of this c ext organization
	 */
	public int getDgPercentNotFullyEmployed();

	/**
	 * Sets the dg percent not fully employed of this c ext organization.
	 *
	 * @param dgPercentNotFullyEmployed the dg percent not fully employed of this c ext organization
	 */
	public void setDgPercentNotFullyEmployed(int dgPercentNotFullyEmployed);

	/**
	 * Returns the dg percent not fully employed estimate of this c ext organization.
	 *
	 * @return the dg percent not fully employed estimate of this c ext organization
	 */
	public boolean getDgPercentNotFullyEmployedEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent not fully employed estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent not fully employed estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentNotFullyEmployedEstimate();

	/**
	 * Sets whether this c ext organization is dg percent not fully employed estimate.
	 *
	 * @param dgPercentNotFullyEmployedEstimate the dg percent not fully employed estimate of this c ext organization
	 */
	public void setDgPercentNotFullyEmployedEstimate(
		boolean dgPercentNotFullyEmployedEstimate);

	/**
	 * Returns the dg percent retired of this c ext organization.
	 *
	 * @return the dg percent retired of this c ext organization
	 */
	public int getDgPercentRetired();

	/**
	 * Sets the dg percent retired of this c ext organization.
	 *
	 * @param dgPercentRetired the dg percent retired of this c ext organization
	 */
	public void setDgPercentRetired(int dgPercentRetired);

	/**
	 * Returns the dg percent retired estimate of this c ext organization.
	 *
	 * @return the dg percent retired estimate of this c ext organization
	 */
	public boolean getDgPercentRetiredEstimate();

	/**
	 * Returns <code>true</code> if this c ext organization is dg percent retired estimate.
	 *
	 * @return <code>true</code> if this c ext organization is dg percent retired estimate; <code>false</code> otherwise
	 */
	public boolean isDgPercentRetiredEstimate();

	/**
	 * Sets whether this c ext organization is dg percent retired estimate.
	 *
	 * @param dgPercentRetiredEstimate the dg percent retired estimate of this c ext organization
	 */
	public void setDgPercentRetiredEstimate(boolean dgPercentRetiredEstimate);

	/**
	 * Returns the dg range of occupations of this c ext organization.
	 *
	 * @return the dg range of occupations of this c ext organization
	 */
	@AutoEscape
	public String getDgRangeOfOccupations();

	/**
	 * Sets the dg range of occupations of this c ext organization.
	 *
	 * @param dgRangeOfOccupations the dg range of occupations of this c ext organization
	 */
	public void setDgRangeOfOccupations(String dgRangeOfOccupations);

	/**
	 * Returns the dg complete of this c ext organization.
	 *
	 * @return the dg complete of this c ext organization
	 */
	public boolean getDgComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is dg complete.
	 *
	 * @return <code>true</code> if this c ext organization is dg complete; <code>false</code> otherwise
	 */
	public boolean isDgComplete();

	/**
	 * Sets whether this c ext organization is dg complete.
	 *
	 * @param dgComplete the dg complete of this c ext organization
	 */
	public void setDgComplete(boolean dgComplete);

	/**
	 * Returns the dv ethnic racial mix of this c ext organization.
	 *
	 * @return the dv ethnic racial mix of this c ext organization
	 */
	@AutoEscape
	public String getDvEthnicRacialMix();

	/**
	 * Sets the dv ethnic racial mix of this c ext organization.
	 *
	 * @param dvEthnicRacialMix the dv ethnic racial mix of this c ext organization
	 */
	public void setDvEthnicRacialMix(String dvEthnicRacialMix);

	/**
	 * Returns the dv welcoming conversation of this c ext organization.
	 *
	 * @return the dv welcoming conversation of this c ext organization
	 */
	@AutoEscape
	public String getDvWelcomingConversation();

	/**
	 * Sets the dv welcoming conversation of this c ext organization.
	 *
	 * @param dvWelcomingConversation the dv welcoming conversation of this c ext organization
	 */
	public void setDvWelcomingConversation(String dvWelcomingConversation);

	/**
	 * Returns the dv welcoming comments of this c ext organization.
	 *
	 * @return the dv welcoming comments of this c ext organization
	 */
	@AutoEscape
	public String getDvWelcomingComments();

	/**
	 * Sets the dv welcoming comments of this c ext organization.
	 *
	 * @param dvWelcomingComments the dv welcoming comments of this c ext organization
	 */
	public void setDvWelcomingComments(String dvWelcomingComments);

	/**
	 * Returns the dv complete of this c ext organization.
	 *
	 * @return the dv complete of this c ext organization
	 */
	public boolean getDvComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is dv complete.
	 *
	 * @return <code>true</code> if this c ext organization is dv complete; <code>false</code> otherwise
	 */
	public boolean isDvComplete();

	/**
	 * Sets whether this c ext organization is dv complete.
	 *
	 * @param dvComplete the dv complete of this c ext organization
	 */
	public void setDvComplete(boolean dvComplete);

	/**
	 * Returns the pp comments of this c ext organization.
	 *
	 * @return the pp comments of this c ext organization
	 */
	@AutoEscape
	public String getPpComments();

	/**
	 * Sets the pp comments of this c ext organization.
	 *
	 * @param ppComments the pp comments of this c ext organization
	 */
	public void setPpComments(String ppComments);

	/**
	 * Returns the pp complete of this c ext organization.
	 *
	 * @return the pp complete of this c ext organization
	 */
	public boolean getPpComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is pp complete.
	 *
	 * @return <code>true</code> if this c ext organization is pp complete; <code>false</code> otherwise
	 */
	public boolean isPpComplete();

	/**
	 * Sets whether this c ext organization is pp complete.
	 *
	 * @param ppComplete the pp complete of this c ext organization
	 */
	public void setPpComplete(boolean ppComplete);

	/**
	 * Returns the sf previous roles of this c ext organization.
	 *
	 * @return the sf previous roles of this c ext organization
	 */
	@AutoEscape
	public String getSfPreviousRoles();

	/**
	 * Sets the sf previous roles of this c ext organization.
	 *
	 * @param sfPreviousRoles the sf previous roles of this c ext organization
	 */
	public void setSfPreviousRoles(String sfPreviousRoles);

	/**
	 * Returns the sf complete of this c ext organization.
	 *
	 * @return the sf complete of this c ext organization
	 */
	public boolean getSfComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is sf complete.
	 *
	 * @return <code>true</code> if this c ext organization is sf complete; <code>false</code> otherwise
	 */
	public boolean isSfComplete();

	/**
	 * Sets whether this c ext organization is sf complete.
	 *
	 * @param sfComplete the sf complete of this c ext organization
	 */
	public void setSfComplete(boolean sfComplete);

	/**
	 * Returns the rv overall ministry of this c ext organization.
	 *
	 * @return the rv overall ministry of this c ext organization
	 */
	@AutoEscape
	public String getRvOverallMinistry();

	/**
	 * Sets the rv overall ministry of this c ext organization.
	 *
	 * @param rvOverallMinistry the rv overall ministry of this c ext organization
	 */
	public void setRvOverallMinistry(String rvOverallMinistry);

	/**
	 * Returns the rv complete of this c ext organization.
	 *
	 * @return the rv complete of this c ext organization
	 */
	public boolean getRvComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is rv complete.
	 *
	 * @return <code>true</code> if this c ext organization is rv complete; <code>false</code> otherwise
	 */
	public boolean isRvComplete();

	/**
	 * Sets whether this c ext organization is rv complete.
	 *
	 * @param rvComplete the rv complete of this c ext organization
	 */
	public void setRvComplete(boolean rvComplete);

	/**
	 * Returns the fn year of this c ext organization.
	 *
	 * @return the fn year of this c ext organization
	 */
	@AutoEscape
	public String getFnYear();

	/**
	 * Sets the fn year of this c ext organization.
	 *
	 * @param fnYear the fn year of this c ext organization
	 */
	public void setFnYear(String fnYear);

	/**
	 * Returns the fn income offerings pledged givings of this c ext organization.
	 *
	 * @return the fn income offerings pledged givings of this c ext organization
	 */
	public int getFnIncomeOfferingsPledgedGivings();

	/**
	 * Sets the fn income offerings pledged givings of this c ext organization.
	 *
	 * @param fnIncomeOfferingsPledgedGivings the fn income offerings pledged givings of this c ext organization
	 */
	public void setFnIncomeOfferingsPledgedGivings(
		int fnIncomeOfferingsPledgedGivings);

	/**
	 * Returns the fn income endowment proceeds of this c ext organization.
	 *
	 * @return the fn income endowment proceeds of this c ext organization
	 */
	public int getFnIncomeEndowmentProceeds();

	/**
	 * Sets the fn income endowment proceeds of this c ext organization.
	 *
	 * @param fnIncomeEndowmentProceeds the fn income endowment proceeds of this c ext organization
	 */
	public void setFnIncomeEndowmentProceeds(int fnIncomeEndowmentProceeds);

	/**
	 * Returns the fn income endowment draw of this c ext organization.
	 *
	 * @return the fn income endowment draw of this c ext organization
	 */
	public int getFnIncomeEndowmentDraw();

	/**
	 * Sets the fn income endowment draw of this c ext organization.
	 *
	 * @param fnIncomeEndowmentDraw the fn income endowment draw of this c ext organization
	 */
	public void setFnIncomeEndowmentDraw(int fnIncomeEndowmentDraw);

	/**
	 * Returns the fn income fundraising of this c ext organization.
	 *
	 * @return the fn income fundraising of this c ext organization
	 */
	public int getFnIncomeFundraising();

	/**
	 * Sets the fn income fundraising of this c ext organization.
	 *
	 * @param fnIncomeFundraising the fn income fundraising of this c ext organization
	 */
	public void setFnIncomeFundraising(int fnIncomeFundraising);

	/**
	 * Returns the fn income designated gifts of this c ext organization.
	 *
	 * @return the fn income designated gifts of this c ext organization
	 */
	public int getFnIncomeDesignatedGifts();

	/**
	 * Sets the fn income designated gifts of this c ext organization.
	 *
	 * @param fnIncomeDesignatedGifts the fn income designated gifts of this c ext organization
	 */
	public void setFnIncomeDesignatedGifts(int fnIncomeDesignatedGifts);

	/**
	 * Returns the fn income grants of this c ext organization.
	 *
	 * @return the fn income grants of this c ext organization
	 */
	public int getFnIncomeGrants();

	/**
	 * Sets the fn income grants of this c ext organization.
	 *
	 * @param fnIncomeGrants the fn income grants of this c ext organization
	 */
	public void setFnIncomeGrants(int fnIncomeGrants);

	/**
	 * Returns the fn income rental church building of this c ext organization.
	 *
	 * @return the fn income rental church building of this c ext organization
	 */
	public int getFnIncomeRentalChurchBuilding();

	/**
	 * Sets the fn income rental church building of this c ext organization.
	 *
	 * @param fnIncomeRentalChurchBuilding the fn income rental church building of this c ext organization
	 */
	public void setFnIncomeRentalChurchBuilding(
		int fnIncomeRentalChurchBuilding);

	/**
	 * Returns the fn income rental church parsonage of this c ext organization.
	 *
	 * @return the fn income rental church parsonage of this c ext organization
	 */
	public int getFnIncomeRentalChurchParsonage();

	/**
	 * Sets the fn income rental church parsonage of this c ext organization.
	 *
	 * @param fnIncomeRentalChurchParsonage the fn income rental church parsonage of this c ext organization
	 */
	public void setFnIncomeRentalChurchParsonage(
		int fnIncomeRentalChurchParsonage);

	/**
	 * Returns the fn income related organizations of this c ext organization.
	 *
	 * @return the fn income related organizations of this c ext organization
	 */
	public int getFnIncomeRelatedOrganizations();

	/**
	 * Sets the fn income related organizations of this c ext organization.
	 *
	 * @param fnIncomeRelatedOrganizations the fn income related organizations of this c ext organization
	 */
	public void setFnIncomeRelatedOrganizations(
		int fnIncomeRelatedOrganizations);

	/**
	 * Returns the fn income special accounts of this c ext organization.
	 *
	 * @return the fn income special accounts of this c ext organization
	 */
	public int getFnIncomeSpecialAccounts();

	/**
	 * Sets the fn income special accounts of this c ext organization.
	 *
	 * @param fnIncomeSpecialAccounts the fn income special accounts of this c ext organization
	 */
	public void setFnIncomeSpecialAccounts(int fnIncomeSpecialAccounts);

	/**
	 * Returns the fn expense of this c ext organization.
	 *
	 * @return the fn expense of this c ext organization
	 */
	public int getFnExpense();

	/**
	 * Sets the fn expense of this c ext organization.
	 *
	 * @param fnExpense the fn expense of this c ext organization
	 */
	public void setFnExpense(int fnExpense);

	/**
	 * Returns the fn file entry ID of this c ext organization.
	 *
	 * @return the fn file entry ID of this c ext organization
	 */
	public long getFnFileEntryId();

	/**
	 * Sets the fn file entry ID of this c ext organization.
	 *
	 * @param fnFileEntryId the fn file entry ID of this c ext organization
	 */
	public void setFnFileEntryId(long fnFileEntryId);

	/**
	 * Returns the fn expense ministerial support percent of this c ext organization.
	 *
	 * @return the fn expense ministerial support percent of this c ext organization
	 */
	public int getFnExpenseMinisterialSupportPercent();

	/**
	 * Sets the fn expense ministerial support percent of this c ext organization.
	 *
	 * @param fnExpenseMinisterialSupportPercent the fn expense ministerial support percent of this c ext organization
	 */
	public void setFnExpenseMinisterialSupportPercent(
		int fnExpenseMinisterialSupportPercent);

	/**
	 * Returns the fn fail to pay minister of this c ext organization.
	 *
	 * @return the fn fail to pay minister of this c ext organization
	 */
	public boolean getFnFailToPayMinister();

	/**
	 * Returns <code>true</code> if this c ext organization is fn fail to pay minister.
	 *
	 * @return <code>true</code> if this c ext organization is fn fail to pay minister; <code>false</code> otherwise
	 */
	public boolean isFnFailToPayMinister();

	/**
	 * Sets whether this c ext organization is fn fail to pay minister.
	 *
	 * @param fnFailToPayMinister the fn fail to pay minister of this c ext organization
	 */
	public void setFnFailToPayMinister(boolean fnFailToPayMinister);

	/**
	 * Returns the fn our church wider mission of this c ext organization.
	 *
	 * @return the fn our church wider mission of this c ext organization
	 */
	public boolean getFnOurChurchWiderMission();

	/**
	 * Returns <code>true</code> if this c ext organization is fn our church wider mission.
	 *
	 * @return <code>true</code> if this c ext organization is fn our church wider mission; <code>false</code> otherwise
	 */
	public boolean isFnOurChurchWiderMission();

	/**
	 * Sets whether this c ext organization is fn our church wider mission.
	 *
	 * @param fnOurChurchWiderMission the fn our church wider mission of this c ext organization
	 */
	public void setFnOurChurchWiderMission(boolean fnOurChurchWiderMission);

	/**
	 * Returns the fn one great hour of sharing of this c ext organization.
	 *
	 * @return the fn one great hour of sharing of this c ext organization
	 */
	public boolean getFnOneGreatHourOfSharing();

	/**
	 * Returns <code>true</code> if this c ext organization is fn one great hour of sharing.
	 *
	 * @return <code>true</code> if this c ext organization is fn one great hour of sharing; <code>false</code> otherwise
	 */
	public boolean isFnOneGreatHourOfSharing();

	/**
	 * Sets whether this c ext organization is fn one great hour of sharing.
	 *
	 * @param fnOneGreatHourOfSharing the fn one great hour of sharing of this c ext organization
	 */
	public void setFnOneGreatHourOfSharing(boolean fnOneGreatHourOfSharing);

	/**
	 * Returns the fn strenghten the church of this c ext organization.
	 *
	 * @return the fn strenghten the church of this c ext organization
	 */
	public boolean getFnStrenghtenTheChurch();

	/**
	 * Returns <code>true</code> if this c ext organization is fn strenghten the church.
	 *
	 * @return <code>true</code> if this c ext organization is fn strenghten the church; <code>false</code> otherwise
	 */
	public boolean isFnStrenghtenTheChurch();

	/**
	 * Sets whether this c ext organization is fn strenghten the church.
	 *
	 * @param fnStrenghtenTheChurch the fn strenghten the church of this c ext organization
	 */
	public void setFnStrenghtenTheChurch(boolean fnStrenghtenTheChurch);

	/**
	 * Returns the fn neighbors in need of this c ext organization.
	 *
	 * @return the fn neighbors in need of this c ext organization
	 */
	public boolean getFnNeighborsInNeed();

	/**
	 * Returns <code>true</code> if this c ext organization is fn neighbors in need.
	 *
	 * @return <code>true</code> if this c ext organization is fn neighbors in need; <code>false</code> otherwise
	 */
	public boolean isFnNeighborsInNeed();

	/**
	 * Sets whether this c ext organization is fn neighbors in need.
	 *
	 * @param fnNeighborsInNeed the fn neighbors in need of this c ext organization
	 */
	public void setFnNeighborsInNeed(boolean fnNeighborsInNeed);

	/**
	 * Returns the fn christmas fund of this c ext organization.
	 *
	 * @return the fn christmas fund of this c ext organization
	 */
	public boolean getFnChristmasFund();

	/**
	 * Returns <code>true</code> if this c ext organization is fn christmas fund.
	 *
	 * @return <code>true</code> if this c ext organization is fn christmas fund; <code>false</code> otherwise
	 */
	public boolean isFnChristmasFund();

	/**
	 * Sets whether this c ext organization is fn christmas fund.
	 *
	 * @param fnChristmasFund the fn christmas fund of this c ext organization
	 */
	public void setFnChristmasFund(boolean fnChristmasFund);

	/**
	 * Returns the fn our church wider mission how of this c ext organization.
	 *
	 * @return the fn our church wider mission how of this c ext organization
	 */
	@AutoEscape
	public String getFnOurChurchWiderMissionHow();

	/**
	 * Sets the fn our church wider mission how of this c ext organization.
	 *
	 * @param fnOurChurchWiderMissionHow the fn our church wider mission how of this c ext organization
	 */
	public void setFnOurChurchWiderMissionHow(String fnOurChurchWiderMissionHow);

	/**
	 * Returns the fn debt current of this c ext organization.
	 *
	 * @return the fn debt current of this c ext organization
	 */
	public int getFnDebtCurrent();

	/**
	 * Sets the fn debt current of this c ext organization.
	 *
	 * @param fnDebtCurrent the fn debt current of this c ext organization
	 */
	public void setFnDebtCurrent(int fnDebtCurrent);

	/**
	 * Returns the fn debt current loan of this c ext organization.
	 *
	 * @return the fn debt current loan of this c ext organization
	 */
	public int getFnDebtCurrentLoan();

	/**
	 * Sets the fn debt current loan of this c ext organization.
	 *
	 * @param fnDebtCurrentLoan the fn debt current loan of this c ext organization
	 */
	public void setFnDebtCurrentLoan(int fnDebtCurrentLoan);

	/**
	 * Returns the fn debt reason for of this c ext organization.
	 *
	 * @return the fn debt reason for of this c ext organization
	 */
	@AutoEscape
	public String getFnDebtReasonFor();

	/**
	 * Sets the fn debt reason for of this c ext organization.
	 *
	 * @param fnDebtReasonFor the fn debt reason for of this c ext organization
	 */
	public void setFnDebtReasonFor(String fnDebtReasonFor);

	/**
	 * Returns the fn debt payments current of this c ext organization.
	 *
	 * @return the fn debt payments current of this c ext organization
	 */
	public boolean getFnDebtPaymentsCurrent();

	/**
	 * Returns <code>true</code> if this c ext organization is fn debt payments current.
	 *
	 * @return <code>true</code> if this c ext organization is fn debt payments current; <code>false</code> otherwise
	 */
	public boolean isFnDebtPaymentsCurrent();

	/**
	 * Sets whether this c ext organization is fn debt payments current.
	 *
	 * @param fnDebtPaymentsCurrent the fn debt payments current of this c ext organization
	 */
	public void setFnDebtPaymentsCurrent(boolean fnDebtPaymentsCurrent);

	/**
	 * Returns the fn endowment of this c ext organization.
	 *
	 * @return the fn endowment of this c ext organization
	 */
	public boolean getFnEndowment();

	/**
	 * Returns <code>true</code> if this c ext organization is fn endowment.
	 *
	 * @return <code>true</code> if this c ext organization is fn endowment; <code>false</code> otherwise
	 */
	public boolean isFnEndowment();

	/**
	 * Sets whether this c ext organization is fn endowment.
	 *
	 * @param fnEndowment the fn endowment of this c ext organization
	 */
	public void setFnEndowment(boolean fnEndowment);

	/**
	 * Returns the fn endowment market value of this c ext organization.
	 *
	 * @return the fn endowment market value of this c ext organization
	 */
	public int getFnEndowmentMarketValue();

	/**
	 * Sets the fn endowment market value of this c ext organization.
	 *
	 * @param fnEndowmentMarketValue the fn endowment market value of this c ext organization
	 */
	public void setFnEndowmentMarketValue(int fnEndowmentMarketValue);

	/**
	 * Returns the fn endowment draw when of this c ext organization.
	 *
	 * @return the fn endowment draw when of this c ext organization
	 */
	@AutoEscape
	public String getFnEndowmentDrawWhen();

	/**
	 * Sets the fn endowment draw when of this c ext organization.
	 *
	 * @param fnEndowmentDrawWhen the fn endowment draw when of this c ext organization
	 */
	public void setFnEndowmentDrawWhen(String fnEndowmentDrawWhen);

	/**
	 * Returns the fn endowment draw5 year percent of this c ext organization.
	 *
	 * @return the fn endowment draw5 year percent of this c ext organization
	 */
	public int getFnEndowmentDraw5YearPercent();

	/**
	 * Sets the fn endowment draw5 year percent of this c ext organization.
	 *
	 * @param fnEndowmentDraw5YearPercent the fn endowment draw5 year percent of this c ext organization
	 */
	public void setFnEndowmentDraw5YearPercent(int fnEndowmentDraw5YearPercent);

	/**
	 * Returns the fn endowment draw5 year to expense of this c ext organization.
	 *
	 * @return the fn endowment draw5 year to expense of this c ext organization
	 */
	@AutoEscape
	public String getFnEndowmentDraw5YearToExpense();

	/**
	 * Sets the fn endowment draw5 year to expense of this c ext organization.
	 *
	 * @param fnEndowmentDraw5YearToExpense the fn endowment draw5 year to expense of this c ext organization
	 */
	public void setFnEndowmentDraw5YearToExpense(
		String fnEndowmentDraw5YearToExpense);

	/**
	 * Returns the fn endowment draw current rate last of this c ext organization.
	 *
	 * @return the fn endowment draw current rate last of this c ext organization
	 */
	@AutoEscape
	public String getFnEndowmentDrawCurrentRateLast();

	/**
	 * Sets the fn endowment draw current rate last of this c ext organization.
	 *
	 * @param fnEndowmentDrawCurrentRateLast the fn endowment draw current rate last of this c ext organization
	 */
	public void setFnEndowmentDrawCurrentRateLast(
		String fnEndowmentDrawCurrentRateLast);

	/**
	 * Returns the fn endowment comment of this c ext organization.
	 *
	 * @return the fn endowment comment of this c ext organization
	 */
	@AutoEscape
	public String getFnEndowmentComment();

	/**
	 * Sets the fn endowment comment of this c ext organization.
	 *
	 * @param fnEndowmentComment the fn endowment comment of this c ext organization
	 */
	public void setFnEndowmentComment(String fnEndowmentComment);

	/**
	 * Returns the fn reserves of this c ext organization.
	 *
	 * @return the fn reserves of this c ext organization
	 */
	public int getFnReserves();

	/**
	 * Sets the fn reserves of this c ext organization.
	 *
	 * @param fnReserves the fn reserves of this c ext organization
	 */
	public void setFnReserves(int fnReserves);

	/**
	 * Returns the fn investments of this c ext organization.
	 *
	 * @return the fn investments of this c ext organization
	 */
	public int getFnInvestments();

	/**
	 * Sets the fn investments of this c ext organization.
	 *
	 * @param fnInvestments the fn investments of this c ext organization
	 */
	public void setFnInvestments(int fnInvestments);

	/**
	 * Returns the fn complete of this c ext organization.
	 *
	 * @return the fn complete of this c ext organization
	 */
	public boolean getFnComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is fn complete.
	 *
	 * @return <code>true</code> if this c ext organization is fn complete; <code>false</code> otherwise
	 */
	public boolean isFnComplete();

	/**
	 * Sets whether this c ext organization is fn complete.
	 *
	 * @param fnComplete the fn complete of this c ext organization
	 */
	public void setFnComplete(boolean fnComplete);

	/**
	 * Returns the re building program of this c ext organization.
	 *
	 * @return the re building program of this c ext organization
	 */
	@AutoEscape
	public String getReBuildingProgram();

	/**
	 * Sets the re building program of this c ext organization.
	 *
	 * @param reBuildingProgram the re building program of this c ext organization
	 */
	public void setReBuildingProgram(String reBuildingProgram);

	/**
	 * Returns the re campaign mission components of this c ext organization.
	 *
	 * @return the re campaign mission components of this c ext organization
	 */
	@AutoEscape
	public String getReCampaignMissionComponents();

	/**
	 * Sets the re campaign mission components of this c ext organization.
	 *
	 * @param reCampaignMissionComponents the re campaign mission components of this c ext organization
	 */
	public void setReCampaignMissionComponents(
		String reCampaignMissionComponents);

	/**
	 * Returns the re parsonage of this c ext organization.
	 *
	 * @return the re parsonage of this c ext organization
	 */
	public boolean getReParsonage();

	/**
	 * Returns <code>true</code> if this c ext organization is re parsonage.
	 *
	 * @return <code>true</code> if this c ext organization is re parsonage; <code>false</code> otherwise
	 */
	public boolean isReParsonage();

	/**
	 * Sets whether this c ext organization is re parsonage.
	 *
	 * @param reParsonage the re parsonage of this c ext organization
	 */
	public void setReParsonage(boolean reParsonage);

	/**
	 * Returns the re parsonage market value of this c ext organization.
	 *
	 * @return the re parsonage market value of this c ext organization
	 */
	public int getReParsonageMarketValue();

	/**
	 * Sets the re parsonage market value of this c ext organization.
	 *
	 * @param reParsonageMarketValue the re parsonage market value of this c ext organization
	 */
	public void setReParsonageMarketValue(int reParsonageMarketValue);

	/**
	 * Returns the re parsonage assessed value of this c ext organization.
	 *
	 * @return the re parsonage assessed value of this c ext organization
	 */
	public int getReParsonageAssessedValue();

	/**
	 * Sets the re parsonage assessed value of this c ext organization.
	 *
	 * @param reParsonageAssessedValue the re parsonage assessed value of this c ext organization
	 */
	public void setReParsonageAssessedValue(int reParsonageAssessedValue);

	/**
	 * Returns the re parsonage usage of this c ext organization.
	 *
	 * @return the re parsonage usage of this c ext organization
	 */
	@AutoEscape
	public String getReParsonageUsage();

	/**
	 * Sets the re parsonage usage of this c ext organization.
	 *
	 * @param reParsonageUsage the re parsonage usage of this c ext organization
	 */
	public void setReParsonageUsage(String reParsonageUsage);

	/**
	 * Returns the re parsonage street address of this c ext organization.
	 *
	 * @return the re parsonage street address of this c ext organization
	 */
	@AutoEscape
	public String getReParsonageStreetAddress();

	/**
	 * Sets the re parsonage street address of this c ext organization.
	 *
	 * @param reParsonageStreetAddress the re parsonage street address of this c ext organization
	 */
	public void setReParsonageStreetAddress(String reParsonageStreetAddress);

	/**
	 * Returns the re parsonage city of this c ext organization.
	 *
	 * @return the re parsonage city of this c ext organization
	 */
	@AutoEscape
	public String getReParsonageCity();

	/**
	 * Sets the re parsonage city of this c ext organization.
	 *
	 * @param reParsonageCity the re parsonage city of this c ext organization
	 */
	public void setReParsonageCity(String reParsonageCity);

	/**
	 * Returns the re parsonage state of this c ext organization.
	 *
	 * @return the re parsonage state of this c ext organization
	 */
	@AutoEscape
	public String getReParsonageState();

	/**
	 * Sets the re parsonage state of this c ext organization.
	 *
	 * @param reParsonageState the re parsonage state of this c ext organization
	 */
	public void setReParsonageState(String reParsonageState);

	/**
	 * Returns the re parsonage zip of this c ext organization.
	 *
	 * @return the re parsonage zip of this c ext organization
	 */
	@AutoEscape
	public String getReParsonageZip();

	/**
	 * Sets the re parsonage zip of this c ext organization.
	 *
	 * @param reParsonageZip the re parsonage zip of this c ext organization
	 */
	public void setReParsonageZip(String reParsonageZip);

	/**
	 * Returns the re parsonage footage of this c ext organization.
	 *
	 * @return the re parsonage footage of this c ext organization
	 */
	public int getReParsonageFootage();

	/**
	 * Sets the re parsonage footage of this c ext organization.
	 *
	 * @param reParsonageFootage the re parsonage footage of this c ext organization
	 */
	public void setReParsonageFootage(int reParsonageFootage);

	/**
	 * Returns the re parsonage bedrooms of this c ext organization.
	 *
	 * @return the re parsonage bedrooms of this c ext organization
	 */
	public int getReParsonageBedrooms();

	/**
	 * Sets the re parsonage bedrooms of this c ext organization.
	 *
	 * @param reParsonageBedrooms the re parsonage bedrooms of this c ext organization
	 */
	public void setReParsonageBedrooms(int reParsonageBedrooms);

	/**
	 * Returns the re parsonage bathrooms of this c ext organization.
	 *
	 * @return the re parsonage bathrooms of this c ext organization
	 */
	public int getReParsonageBathrooms();

	/**
	 * Sets the re parsonage bathrooms of this c ext organization.
	 *
	 * @param reParsonageBathrooms the re parsonage bathrooms of this c ext organization
	 */
	public void setReParsonageBathrooms(int reParsonageBathrooms);

	/**
	 * Returns the re parsonage available minister of this c ext organization.
	 *
	 * @return the re parsonage available minister of this c ext organization
	 */
	public boolean getReParsonageAvailableMinister();

	/**
	 * Returns <code>true</code> if this c ext organization is re parsonage available minister.
	 *
	 * @return <code>true</code> if this c ext organization is re parsonage available minister; <code>false</code> otherwise
	 */
	public boolean isReParsonageAvailableMinister();

	/**
	 * Sets whether this c ext organization is re parsonage available minister.
	 *
	 * @param reParsonageAvailableMinister the re parsonage available minister of this c ext organization
	 */
	public void setReParsonageAvailableMinister(
		boolean reParsonageAvailableMinister);

	/**
	 * Returns the re parsonage expected minister of this c ext organization.
	 *
	 * @return the re parsonage expected minister of this c ext organization
	 */
	public boolean getReParsonageExpectedMinister();

	/**
	 * Returns <code>true</code> if this c ext organization is re parsonage expected minister.
	 *
	 * @return <code>true</code> if this c ext organization is re parsonage expected minister; <code>false</code> otherwise
	 */
	public boolean isReParsonageExpectedMinister();

	/**
	 * Sets whether this c ext organization is re parsonage expected minister.
	 *
	 * @param reParsonageExpectedMinister the re parsonage expected minister of this c ext organization
	 */
	public void setReParsonageExpectedMinister(
		boolean reParsonageExpectedMinister);

	/**
	 * Returns the re parsonage condition of this c ext organization.
	 *
	 * @return the re parsonage condition of this c ext organization
	 */
	@AutoEscape
	public String getReParsonageCondition();

	/**
	 * Sets the re parsonage condition of this c ext organization.
	 *
	 * @param reParsonageCondition the re parsonage condition of this c ext organization
	 */
	public void setReParsonageCondition(String reParsonageCondition);

	/**
	 * Returns the re parsonage responsible entity of this c ext organization.
	 *
	 * @return the re parsonage responsible entity of this c ext organization
	 */
	@AutoEscape
	public String getReParsonageResponsibleEntity();

	/**
	 * Sets the re parsonage responsible entity of this c ext organization.
	 *
	 * @param reParsonageResponsibleEntity the re parsonage responsible entity of this c ext organization
	 */
	public void setReParsonageResponsibleEntity(
		String reParsonageResponsibleEntity);

	/**
	 * Returns the re owned buildings of this c ext organization.
	 *
	 * @return the re owned buildings of this c ext organization
	 */
	@AutoEscape
	public String getReOwnedBuildings();

	/**
	 * Sets the re owned buildings of this c ext organization.
	 *
	 * @param reOwnedBuildings the re owned buildings of this c ext organization
	 */
	public void setReOwnedBuildings(String reOwnedBuildings);

	/**
	 * Returns the re non owned buildings of this c ext organization.
	 *
	 * @return the re non owned buildings of this c ext organization
	 */
	@AutoEscape
	public String getReNonOwnedBuildings();

	/**
	 * Sets the re non owned buildings of this c ext organization.
	 *
	 * @param reNonOwnedBuildings the re non owned buildings of this c ext organization
	 */
	public void setReNonOwnedBuildings(String reNonOwnedBuildings);

	/**
	 * Returns the re wheelchair accessible of this c ext organization.
	 *
	 * @return the re wheelchair accessible of this c ext organization
	 */
	@AutoEscape
	public String getReWheelchairAccessible();

	/**
	 * Sets the re wheelchair accessible of this c ext organization.
	 *
	 * @param reWheelchairAccessible the re wheelchair accessible of this c ext organization
	 */
	public void setReWheelchairAccessible(String reWheelchairAccessible);

	/**
	 * Returns the re finances assets review of this c ext organization.
	 *
	 * @return the re finances assets review of this c ext organization
	 */
	@AutoEscape
	public String getReFinancesAssetsReview();

	/**
	 * Sets the re finances assets review of this c ext organization.
	 *
	 * @param reFinancesAssetsReview the re finances assets review of this c ext organization
	 */
	public void setReFinancesAssetsReview(String reFinancesAssetsReview);

	/**
	 * Returns the re complete of this c ext organization.
	 *
	 * @return the re complete of this c ext organization
	 */
	public boolean getReComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is re complete.
	 *
	 * @return <code>true</code> if this c ext organization is re complete; <code>false</code> otherwise
	 */
	public boolean isReComplete();

	/**
	 * Sets whether this c ext organization is re complete.
	 *
	 * @param reComplete the re complete of this c ext organization
	 */
	public void setReComplete(boolean reComplete);

	/**
	 * Returns the hi significant happenings of this c ext organization.
	 *
	 * @return the hi significant happenings of this c ext organization
	 */
	@AutoEscape
	public String getHiSignificantHappenings();

	/**
	 * Sets the hi significant happenings of this c ext organization.
	 *
	 * @param hiSignificantHappenings the hi significant happenings of this c ext organization
	 */
	public void setHiSignificantHappenings(String hiSignificantHappenings);

	/**
	 * Returns the hi managed change of this c ext organization.
	 *
	 * @return the hi managed change of this c ext organization
	 */
	@AutoEscape
	public String getHiManagedChange();

	/**
	 * Sets the hi managed change of this c ext organization.
	 *
	 * @param hiManagedChange the hi managed change of this c ext organization
	 */
	public void setHiManagedChange(String hiManagedChange);

	/**
	 * Returns the hi conflict resolution of this c ext organization.
	 *
	 * @return the hi conflict resolution of this c ext organization
	 */
	@AutoEscape
	public String getHiConflictResolution();

	/**
	 * Sets the hi conflict resolution of this c ext organization.
	 *
	 * @param hiConflictResolution the hi conflict resolution of this c ext organization
	 */
	public void setHiConflictResolution(String hiConflictResolution);

	/**
	 * Returns the hi ministerial leadership learning of this c ext organization.
	 *
	 * @return the hi ministerial leadership learning of this c ext organization
	 */
	@AutoEscape
	public String getHiMinisterialLeadershipLearning();

	/**
	 * Sets the hi ministerial leadership learning of this c ext organization.
	 *
	 * @param hiMinisterialLeadershipLearning the hi ministerial leadership learning of this c ext organization
	 */
	public void setHiMinisterialLeadershipLearning(
		String hiMinisterialLeadershipLearning);

	/**
	 * Returns the hi pressure involuntary termination of this c ext organization.
	 *
	 * @return the hi pressure involuntary termination of this c ext organization
	 */
	@AutoEscape
	public String getHiPressureInvoluntaryTermination();

	/**
	 * Sets the hi pressure involuntary termination of this c ext organization.
	 *
	 * @param hiPressureInvoluntaryTermination the hi pressure involuntary termination of this c ext organization
	 */
	public void setHiPressureInvoluntaryTermination(
		String hiPressureInvoluntaryTermination);

	/**
	 * Returns the hi situational support consultation of this c ext organization.
	 *
	 * @return the hi situational support consultation of this c ext organization
	 */
	@AutoEscape
	public String getHiSituationalSupportConsultation();

	/**
	 * Sets the hi situational support consultation of this c ext organization.
	 *
	 * @param hiSituationalSupportConsultation the hi situational support consultation of this c ext organization
	 */
	public void setHiSituationalSupportConsultation(
		String hiSituationalSupportConsultation);

	/**
	 * Returns the hi fitness review of this c ext organization.
	 *
	 * @return the hi fitness review of this c ext organization
	 */
	@AutoEscape
	public String getHiFitnessReview();

	/**
	 * Sets the hi fitness review of this c ext organization.
	 *
	 * @param hiFitnessReview the hi fitness review of this c ext organization
	 */
	public void setHiFitnessReview(String hiFitnessReview);

	/**
	 * Returns the hi complete of this c ext organization.
	 *
	 * @return the hi complete of this c ext organization
	 */
	public boolean getHiComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is hi complete.
	 *
	 * @return <code>true</code> if this c ext organization is hi complete; <code>false</code> otherwise
	 */
	public boolean isHiComplete();

	/**
	 * Sets whether this c ext organization is hi complete.
	 *
	 * @param hiComplete the hi complete of this c ext organization
	 */
	public void setHiComplete(boolean hiComplete);

	/**
	 * Returns the cm service advocacy of this c ext organization.
	 *
	 * @return the cm service advocacy of this c ext organization
	 */
	@AutoEscape
	public String getCmServiceAdvocacy();

	/**
	 * Sets the cm service advocacy of this c ext organization.
	 *
	 * @param cmServiceAdvocacy the cm service advocacy of this c ext organization
	 */
	public void setCmServiceAdvocacy(String cmServiceAdvocacy);

	/**
	 * Returns the cm meetings relationships activities of this c ext organization.
	 *
	 * @return the cm meetings relationships activities of this c ext organization
	 */
	@AutoEscape
	public String getCmMeetingsRelationshipsActivities();

	/**
	 * Sets the cm meetings relationships activities of this c ext organization.
	 *
	 * @param cmMeetingsRelationshipsActivities the cm meetings relationships activities of this c ext organization
	 */
	public void setCmMeetingsRelationshipsActivities(
		String cmMeetingsRelationshipsActivities);

	/**
	 * Returns the cm accessible to all of this c ext organization.
	 *
	 * @return the cm accessible to all of this c ext organization
	 */
	public boolean getCmAccessibleToAll();

	/**
	 * Returns <code>true</code> if this c ext organization is cm accessible to all.
	 *
	 * @return <code>true</code> if this c ext organization is cm accessible to all; <code>false</code> otherwise
	 */
	public boolean isCmAccessibleToAll();

	/**
	 * Sets whether this c ext organization is cm accessible to all.
	 *
	 * @param cmAccessibleToAll the cm accessible to all of this c ext organization
	 */
	public void setCmAccessibleToAll(boolean cmAccessibleToAll);

	/**
	 * Returns the cm creation justice of this c ext organization.
	 *
	 * @return the cm creation justice of this c ext organization
	 */
	public boolean getCmCreationJustice();

	/**
	 * Returns <code>true</code> if this c ext organization is cm creation justice.
	 *
	 * @return <code>true</code> if this c ext organization is cm creation justice; <code>false</code> otherwise
	 */
	public boolean isCmCreationJustice();

	/**
	 * Sets whether this c ext organization is cm creation justice.
	 *
	 * @param cmCreationJustice the cm creation justice of this c ext organization
	 */
	public void setCmCreationJustice(boolean cmCreationJustice);

	/**
	 * Returns the cm economic justice of this c ext organization.
	 *
	 * @return the cm economic justice of this c ext organization
	 */
	public boolean getCmEconomicJustice();

	/**
	 * Returns <code>true</code> if this c ext organization is cm economic justice.
	 *
	 * @return <code>true</code> if this c ext organization is cm economic justice; <code>false</code> otherwise
	 */
	public boolean isCmEconomicJustice();

	/**
	 * Sets whether this c ext organization is cm economic justice.
	 *
	 * @param cmEconomicJustice the cm economic justice of this c ext organization
	 */
	public void setCmEconomicJustice(boolean cmEconomicJustice);

	/**
	 * Returns the cm faithful and welcoming of this c ext organization.
	 *
	 * @return the cm faithful and welcoming of this c ext organization
	 */
	public boolean getCmFaithfulAndWelcoming();

	/**
	 * Returns <code>true</code> if this c ext organization is cm faithful and welcoming.
	 *
	 * @return <code>true</code> if this c ext organization is cm faithful and welcoming; <code>false</code> otherwise
	 */
	public boolean isCmFaithfulAndWelcoming();

	/**
	 * Sets whether this c ext organization is cm faithful and welcoming.
	 *
	 * @param cmFaithfulAndWelcoming the cm faithful and welcoming of this c ext organization
	 */
	public void setCmFaithfulAndWelcoming(boolean cmFaithfulAndWelcoming);

	/**
	 * Returns the cm god is still speaking of this c ext organization.
	 *
	 * @return the cm god is still speaking of this c ext organization
	 */
	public boolean getCmGodIsStillSpeaking();

	/**
	 * Returns <code>true</code> if this c ext organization is cm god is still speaking.
	 *
	 * @return <code>true</code> if this c ext organization is cm god is still speaking; <code>false</code> otherwise
	 */
	public boolean isCmGodIsStillSpeaking();

	/**
	 * Sets whether this c ext organization is cm god is still speaking.
	 *
	 * @param cmGodIsStillSpeaking the cm god is still speaking of this c ext organization
	 */
	public void setCmGodIsStillSpeaking(boolean cmGodIsStillSpeaking);

	/**
	 * Returns the cm border and immigrant justice of this c ext organization.
	 *
	 * @return the cm border and immigrant justice of this c ext organization
	 */
	public boolean getCmBorderAndImmigrantJustice();

	/**
	 * Returns <code>true</code> if this c ext organization is cm border and immigrant justice.
	 *
	 * @return <code>true</code> if this c ext organization is cm border and immigrant justice; <code>false</code> otherwise
	 */
	public boolean isCmBorderAndImmigrantJustice();

	/**
	 * Sets whether this c ext organization is cm border and immigrant justice.
	 *
	 * @param cmBorderAndImmigrantJustice the cm border and immigrant justice of this c ext organization
	 */
	public void setCmBorderAndImmigrantJustice(
		boolean cmBorderAndImmigrantJustice);

	/**
	 * Returns the cm inter cultural multi racial of this c ext organization.
	 *
	 * @return the cm inter cultural multi racial of this c ext organization
	 */
	public boolean getCmInterCulturalMultiRacial();

	/**
	 * Returns <code>true</code> if this c ext organization is cm inter cultural multi racial.
	 *
	 * @return <code>true</code> if this c ext organization is cm inter cultural multi racial; <code>false</code> otherwise
	 */
	public boolean isCmInterCulturalMultiRacial();

	/**
	 * Sets whether this c ext organization is cm inter cultural multi racial.
	 *
	 * @param cmInterCulturalMultiRacial the cm inter cultural multi racial of this c ext organization
	 */
	public void setCmInterCulturalMultiRacial(
		boolean cmInterCulturalMultiRacial);

	/**
	 * Returns the cm just peace of this c ext organization.
	 *
	 * @return the cm just peace of this c ext organization
	 */
	public boolean getCmJustPeace();

	/**
	 * Returns <code>true</code> if this c ext organization is cm just peace.
	 *
	 * @return <code>true</code> if this c ext organization is cm just peace; <code>false</code> otherwise
	 */
	public boolean isCmJustPeace();

	/**
	 * Sets whether this c ext organization is cm just peace.
	 *
	 * @param cmJustPeace the cm just peace of this c ext organization
	 */
	public void setCmJustPeace(boolean cmJustPeace);

	/**
	 * Returns the cm global mission church of this c ext organization.
	 *
	 * @return the cm global mission church of this c ext organization
	 */
	public boolean getCmGlobalMissionChurch();

	/**
	 * Returns <code>true</code> if this c ext organization is cm global mission church.
	 *
	 * @return <code>true</code> if this c ext organization is cm global mission church; <code>false</code> otherwise
	 */
	public boolean isCmGlobalMissionChurch();

	/**
	 * Sets whether this c ext organization is cm global mission church.
	 *
	 * @param cmGlobalMissionChurch the cm global mission church of this c ext organization
	 */
	public void setCmGlobalMissionChurch(boolean cmGlobalMissionChurch);

	/**
	 * Returns the cm open and affirming of this c ext organization.
	 *
	 * @return the cm open and affirming of this c ext organization
	 */
	public boolean getCmOpenAndAffirming();

	/**
	 * Returns <code>true</code> if this c ext organization is cm open and affirming.
	 *
	 * @return <code>true</code> if this c ext organization is cm open and affirming; <code>false</code> otherwise
	 */
	public boolean isCmOpenAndAffirming();

	/**
	 * Sets whether this c ext organization is cm open and affirming.
	 *
	 * @param cmOpenAndAffirming the cm open and affirming of this c ext organization
	 */
	public void setCmOpenAndAffirming(boolean cmOpenAndAffirming);

	/**
	 * Returns the cm wise congregation for mental health of this c ext organization.
	 *
	 * @return the cm wise congregation for mental health of this c ext organization
	 */
	public boolean getCmWISECongregationForMentalHealth();

	/**
	 * Returns <code>true</code> if this c ext organization is cm wise congregation for mental health.
	 *
	 * @return <code>true</code> if this c ext organization is cm wise congregation for mental health; <code>false</code> otherwise
	 */
	public boolean isCmWISECongregationForMentalHealth();

	/**
	 * Sets whether this c ext organization is cm wise congregation for mental health.
	 *
	 * @param cmWISECongregationForMentalHealth the cm wise congregation for mental health of this c ext organization
	 */
	public void setCmWISECongregationForMentalHealth(
		boolean cmWISECongregationForMentalHealth);

	/**
	 * Returns the cm other ucc designations of this c ext organization.
	 *
	 * @return the cm other ucc designations of this c ext organization
	 */
	public boolean getCmOtherUCCDesignations();

	/**
	 * Returns <code>true</code> if this c ext organization is cm other ucc designations.
	 *
	 * @return <code>true</code> if this c ext organization is cm other ucc designations; <code>false</code> otherwise
	 */
	public boolean isCmOtherUCCDesignations();

	/**
	 * Sets whether this c ext organization is cm other ucc designations.
	 *
	 * @param cmOtherUCCDesignations the cm other ucc designations of this c ext organization
	 */
	public void setCmOtherUCCDesignations(boolean cmOtherUCCDesignations);

	/**
	 * Returns the cm designations other denominations of this c ext organization.
	 *
	 * @return the cm designations other denominations of this c ext organization
	 */
	public boolean getCmDesignationsOtherDenominations();

	/**
	 * Returns <code>true</code> if this c ext organization is cm designations other denominations.
	 *
	 * @return <code>true</code> if this c ext organization is cm designations other denominations; <code>false</code> otherwise
	 */
	public boolean isCmDesignationsOtherDenominations();

	/**
	 * Sets whether this c ext organization is cm designations other denominations.
	 *
	 * @param cmDesignationsOtherDenominations the cm designations other denominations of this c ext organization
	 */
	public void setCmDesignationsOtherDenominations(
		boolean cmDesignationsOtherDenominations);

	/**
	 * Returns the cm statements reflection of this c ext organization.
	 *
	 * @return the cm statements reflection of this c ext organization
	 */
	@AutoEscape
	public String getCmStatementsReflection();

	/**
	 * Sets the cm statements reflection of this c ext organization.
	 *
	 * @param cmStatementsReflection the cm statements reflection of this c ext organization
	 */
	public void setCmStatementsReflection(String cmStatementsReflection);

	/**
	 * Returns the cm work toward witness future of this c ext organization.
	 *
	 * @return the cm work toward witness future of this c ext organization
	 */
	@AutoEscape
	public String getCmWorkTowardWitnessFuture();

	/**
	 * Sets the cm work toward witness future of this c ext organization.
	 *
	 * @param cmWorkTowardWitnessFuture the cm work toward witness future of this c ext organization
	 */
	public void setCmWorkTowardWitnessFuture(String cmWorkTowardWitnessFuture);

	/**
	 * Returns the cm ecumenical interfaith participation of this c ext organization.
	 *
	 * @return the cm ecumenical interfaith participation of this c ext organization
	 */
	@AutoEscape
	public String getCmEcumenicalInterfaithParticipation();

	/**
	 * Sets the cm ecumenical interfaith participation of this c ext organization.
	 *
	 * @param cmEcumenicalInterfaithParticipation the cm ecumenical interfaith participation of this c ext organization
	 */
	public void setCmEcumenicalInterfaithParticipation(
		String cmEcumenicalInterfaithParticipation);

	/**
	 * Returns the cm mission statement comparison of this c ext organization.
	 *
	 * @return the cm mission statement comparison of this c ext organization
	 */
	@AutoEscape
	public String getCmMissionStatementComparison();

	/**
	 * Sets the cm mission statement comparison of this c ext organization.
	 *
	 * @param cmMissionStatementComparison the cm mission statement comparison of this c ext organization
	 */
	public void setCmMissionStatementComparison(
		String cmMissionStatementComparison);

	/**
	 * Returns the cm pastor time expectations of this c ext organization.
	 *
	 * @return the cm pastor time expectations of this c ext organization
	 */
	@AutoEscape
	public String getCmPastorTimeExpectations();

	/**
	 * Sets the cm pastor time expectations of this c ext organization.
	 *
	 * @param cmPastorTimeExpectations the cm pastor time expectations of this c ext organization
	 */
	public void setCmPastorTimeExpectations(String cmPastorTimeExpectations);

	/**
	 * Returns the cm complete of this c ext organization.
	 *
	 * @return the cm complete of this c ext organization
	 */
	public boolean getCmComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is cm complete.
	 *
	 * @return <code>true</code> if this c ext organization is cm complete; <code>false</code> otherwise
	 */
	public boolean isCmComplete();

	/**
	 * Sets whether this c ext organization is cm complete.
	 *
	 * @param cmComplete the cm complete of this c ext organization
	 */
	public void setCmComplete(boolean cmComplete);

	/**
	 * Returns the mi mission in site trends opportunities of this c ext organization.
	 *
	 * @return the mi mission in site trends opportunities of this c ext organization
	 */
	@AutoEscape
	public String getMiMissionInSiteTrendsOpportunities();

	/**
	 * Sets the mi mission in site trends opportunities of this c ext organization.
	 *
	 * @param miMissionInSiteTrendsOpportunities the mi mission in site trends opportunities of this c ext organization
	 */
	public void setMiMissionInSiteTrendsOpportunities(
		String miMissionInSiteTrendsOpportunities);

	/**
	 * Returns the mi congregation demographics comparison of this c ext organization.
	 *
	 * @return the mi congregation demographics comparison of this c ext organization
	 */
	@AutoEscape
	public String getMiCongregationDemographicsComparison();

	/**
	 * Sets the mi congregation demographics comparison of this c ext organization.
	 *
	 * @param miCongregationDemographicsComparison the mi congregation demographics comparison of this c ext organization
	 */
	public void setMiCongregationDemographicsComparison(
		String miCongregationDemographicsComparison);

	/**
	 * Returns the mi community demographics impact of this c ext organization.
	 *
	 * @return the mi community demographics impact of this c ext organization
	 */
	@AutoEscape
	public String getMiCommunityDemographicsImpact();

	/**
	 * Sets the mi community demographics impact of this c ext organization.
	 *
	 * @param miCommunityDemographicsImpact the mi community demographics impact of this c ext organization
	 */
	public void setMiCommunityDemographicsImpact(
		String miCommunityDemographicsImpact);

	/**
	 * Returns the mi known for in community of this c ext organization.
	 *
	 * @return the mi known for in community of this c ext organization
	 */
	@AutoEscape
	public String getMiKnownForInCommunity();

	/**
	 * Sets the mi known for in community of this c ext organization.
	 *
	 * @param miKnownForInCommunity the mi known for in community of this c ext organization
	 */
	public void setMiKnownForInCommunity(String miKnownForInCommunity);

	/**
	 * Returns the mi why new people involved of this c ext organization.
	 *
	 * @return the mi why new people involved of this c ext organization
	 */
	@AutoEscape
	public String getMiWhyNewPeopleInvolved();

	/**
	 * Sets the mi why new people involved of this c ext organization.
	 *
	 * @param miWhyNewPeopleInvolved the mi why new people involved of this c ext organization
	 */
	public void setMiWhyNewPeopleInvolved(String miWhyNewPeopleInvolved);

	/**
	 * Returns the mi complete of this c ext organization.
	 *
	 * @return the mi complete of this c ext organization
	 */
	public boolean getMiComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is mi complete.
	 *
	 * @return <code>true</code> if this c ext organization is mi complete; <code>false</code> otherwise
	 */
	public boolean isMiComplete();

	/**
	 * Sets whether this c ext organization is mi complete.
	 *
	 * @param miComplete the mi complete of this c ext organization
	 */
	public void setMiComplete(boolean miComplete);

	/**
	 * Returns the vs gods call to become of this c ext organization.
	 *
	 * @return the vs gods call to become of this c ext organization
	 */
	@AutoEscape
	public String getVsGodsCallToBecome();

	/**
	 * Sets the vs gods call to become of this c ext organization.
	 *
	 * @param vsGodsCallToBecome the vs gods call to become of this c ext organization
	 */
	public void setVsGodsCallToBecome(String vsGodsCallToBecome);

	/**
	 * Returns the vs gods call to reach out of this c ext organization.
	 *
	 * @return the vs gods call to reach out of this c ext organization
	 */
	@AutoEscape
	public String getVsGodsCallToReachOut();

	/**
	 * Sets the vs gods call to reach out of this c ext organization.
	 *
	 * @param vsGodsCallToReachOut the vs gods call to reach out of this c ext organization
	 */
	public void setVsGodsCallToReachOut(String vsGodsCallToReachOut);

	/**
	 * Returns the vs complete of this c ext organization.
	 *
	 * @return the vs complete of this c ext organization
	 */
	public boolean getVsComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is vs complete.
	 *
	 * @return <code>true</code> if this c ext organization is vs complete; <code>false</code> otherwise
	 */
	public boolean isVsComplete();

	/**
	 * Sets whether this c ext organization is vs complete.
	 *
	 * @param vsComplete the vs complete of this c ext organization
	 */
	public void setVsComplete(boolean vsComplete);

	/**
	 * Returns the pv file entry ID of this c ext organization.
	 *
	 * @return the pv file entry ID of this c ext organization
	 */
	public long getPvFileEntryId();

	/**
	 * Sets the pv file entry ID of this c ext organization.
	 *
	 * @param pvFileEntryId the pv file entry ID of this c ext organization
	 */
	public void setPvFileEntryId(long pvFileEntryId);

	/**
	 * Returns the pv generated date of this c ext organization.
	 *
	 * @return the pv generated date of this c ext organization
	 */
	public Date getPvGeneratedDate();

	/**
	 * Sets the pv generated date of this c ext organization.
	 *
	 * @param pvGeneratedDate the pv generated date of this c ext organization
	 */
	public void setPvGeneratedDate(Date pvGeneratedDate);

	/**
	 * Returns the pv complete of this c ext organization.
	 *
	 * @return the pv complete of this c ext organization
	 */
	public boolean getPvComplete();

	/**
	 * Returns <code>true</code> if this c ext organization is pv complete.
	 *
	 * @return <code>true</code> if this c ext organization is pv complete; <code>false</code> otherwise
	 */
	public boolean isPvComplete();

	/**
	 * Sets whether this c ext organization is pv complete.
	 *
	 * @param pvComplete the pv complete of this c ext organization
	 */
	public void setPvComplete(boolean pvComplete);

	/**
	 * Returns the pb file entry ID of this c ext organization.
	 *
	 * @return the pb file entry ID of this c ext organization
	 */
	public long getPbFileEntryId();

	/**
	 * Sets the pb file entry ID of this c ext organization.
	 *
	 * @param pbFileEntryId the pb file entry ID of this c ext organization
	 */
	public void setPbFileEntryId(long pbFileEntryId);

	/**
	 * Returns the pb published date of this c ext organization.
	 *
	 * @return the pb published date of this c ext organization
	 */
	public Date getPbPublishedDate();

	/**
	 * Sets the pb published date of this c ext organization.
	 *
	 * @param pbPublishedDate the pb published date of this c ext organization
	 */
	public void setPbPublishedDate(Date pbPublishedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CExtOrganization cExtOrganization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CExtOrganization> toCacheModel();

	@Override
	public CExtOrganization toEscapedModel();

	@Override
	public CExtOrganization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}