/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import ucc.portal.service.persistence.CExtHistoricalInformationStaffingPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CExtHistoricalInformationStaffing service. Represents a row in the &quot;UCC_CExtHistoricalInformationStaffing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.CExtHistoricalInformationStaffingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.CExtHistoricalInformationStaffingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CExtHistoricalInformationStaffing
 * @see ucc.portal.model.impl.CExtHistoricalInformationStaffingImpl
 * @see ucc.portal.model.impl.CExtHistoricalInformationStaffingModelImpl
 * @generated
 */
@ProviderType
public interface CExtHistoricalInformationStaffingModel extends BaseModel<CExtHistoricalInformationStaffing>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c ext historical information staffing model instance should use the {@link CExtHistoricalInformationStaffing} interface instead.
	 */

	/**
	 * Returns the primary key of this c ext historical information staffing.
	 *
	 * @return the primary key of this c ext historical information staffing
	 */
	public CExtHistoricalInformationStaffingPK getPrimaryKey();

	/**
	 * Sets the primary key of this c ext historical information staffing.
	 *
	 * @param primaryKey the primary key of this c ext historical information staffing
	 */
	public void setPrimaryKey(CExtHistoricalInformationStaffingPK primaryKey);

	/**
	 * Returns the organization ID of this c ext historical information staffing.
	 *
	 * @return the organization ID of this c ext historical information staffing
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this c ext historical information staffing.
	 *
	 * @param organizationId the organization ID of this c ext historical information staffing
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the cext historical information staffing ID of this c ext historical information staffing.
	 *
	 * @return the cext historical information staffing ID of this c ext historical information staffing
	 */
	public long getCextHistoricalInformationStaffingId();

	/**
	 * Sets the cext historical information staffing ID of this c ext historical information staffing.
	 *
	 * @param cextHistoricalInformationStaffingId the cext historical information staffing ID of this c ext historical information staffing
	 */
	public void setCextHistoricalInformationStaffingId(
		long cextHistoricalInformationStaffingId);

	/**
	 * Returns the company ID of this c ext historical information staffing.
	 *
	 * @return the company ID of this c ext historical information staffing
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this c ext historical information staffing.
	 *
	 * @param companyId the company ID of this c ext historical information staffing
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this c ext historical information staffing.
	 *
	 * @return the user ID of this c ext historical information staffing
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this c ext historical information staffing.
	 *
	 * @param userId the user ID of this c ext historical information staffing
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c ext historical information staffing.
	 *
	 * @return the user uuid of this c ext historical information staffing
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this c ext historical information staffing.
	 *
	 * @param userUuid the user uuid of this c ext historical information staffing
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this c ext historical information staffing.
	 *
	 * @return the create date of this c ext historical information staffing
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this c ext historical information staffing.
	 *
	 * @param createDate the create date of this c ext historical information staffing
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c ext historical information staffing.
	 *
	 * @return the modified date of this c ext historical information staffing
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c ext historical information staffing.
	 *
	 * @param modifiedDate the modified date of this c ext historical information staffing
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the hi minister name of this c ext historical information staffing.
	 *
	 * @return the hi minister name of this c ext historical information staffing
	 */
	@AutoEscape
	public String getHiMinisterName();

	/**
	 * Sets the hi minister name of this c ext historical information staffing.
	 *
	 * @param hiMinisterName the hi minister name of this c ext historical information staffing
	 */
	public void setHiMinisterName(String hiMinisterName);

	/**
	 * Returns the hi minister ucc standing of this c ext historical information staffing.
	 *
	 * @return the hi minister ucc standing of this c ext historical information staffing
	 */
	public boolean getHiMinisterUCCStanding();

	/**
	 * Returns <code>true</code> if this c ext historical information staffing is hi minister ucc standing.
	 *
	 * @return <code>true</code> if this c ext historical information staffing is hi minister ucc standing; <code>false</code> otherwise
	 */
	public boolean isHiMinisterUCCStanding();

	/**
	 * Sets whether this c ext historical information staffing is hi minister ucc standing.
	 *
	 * @param hiMinisterUCCStanding the hi minister ucc standing of this c ext historical information staffing
	 */
	public void setHiMinisterUCCStanding(boolean hiMinisterUCCStanding);

	/**
	 * Returns the hi minister start year of service of this c ext historical information staffing.
	 *
	 * @return the hi minister start year of service of this c ext historical information staffing
	 */
	public int getHiMinisterStartYearOfService();

	/**
	 * Sets the hi minister start year of service of this c ext historical information staffing.
	 *
	 * @param hiMinisterStartYearOfService the hi minister start year of service of this c ext historical information staffing
	 */
	public void setHiMinisterStartYearOfService(
		int hiMinisterStartYearOfService);

	/**
	 * Returns the hi minister end year of service of this c ext historical information staffing.
	 *
	 * @return the hi minister end year of service of this c ext historical information staffing
	 */
	public int getHiMinisterEndYearOfService();

	/**
	 * Sets the hi minister end year of service of this c ext historical information staffing.
	 *
	 * @param hiMinisterEndYearOfService the hi minister end year of service of this c ext historical information staffing
	 */
	public void setHiMinisterEndYearOfService(int hiMinisterEndYearOfService);

	/**
	 * Returns the hi priority of this c ext historical information staffing.
	 *
	 * @return the hi priority of this c ext historical information staffing
	 */
	public double getHiPriority();

	/**
	 * Sets the hi priority of this c ext historical information staffing.
	 *
	 * @param hiPriority the hi priority of this c ext historical information staffing
	 */
	public void setHiPriority(double hiPriority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		CExtHistoricalInformationStaffing cExtHistoricalInformationStaffing);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CExtHistoricalInformationStaffing> toCacheModel();

	@Override
	public CExtHistoricalInformationStaffing toEscapedModel();

	@Override
	public CExtHistoricalInformationStaffing toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}