/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExtContinuingEducation service. Represents a row in the &quot;UCC_ExtContinuingEducation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.ExtContinuingEducationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.ExtContinuingEducationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtContinuingEducation
 * @see ucc.portal.model.impl.ExtContinuingEducationImpl
 * @see ucc.portal.model.impl.ExtContinuingEducationModelImpl
 * @generated
 */
@ProviderType
public interface ExtContinuingEducationModel extends BaseModel<ExtContinuingEducation>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ext continuing education model instance should use the {@link ExtContinuingEducation} interface instead.
	 */

	/**
	 * Returns the primary key of this ext continuing education.
	 *
	 * @return the primary key of this ext continuing education
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ext continuing education.
	 *
	 * @param primaryKey the primary key of this ext continuing education
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ext continuing education ID of this ext continuing education.
	 *
	 * @return the ext continuing education ID of this ext continuing education
	 */
	public long getExtContinuingEducationId();

	/**
	 * Sets the ext continuing education ID of this ext continuing education.
	 *
	 * @param extContinuingEducationId the ext continuing education ID of this ext continuing education
	 */
	public void setExtContinuingEducationId(long extContinuingEducationId);

	/**
	 * Returns the company ID of this ext continuing education.
	 *
	 * @return the company ID of this ext continuing education
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ext continuing education.
	 *
	 * @param companyId the company ID of this ext continuing education
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ext continuing education.
	 *
	 * @return the user ID of this ext continuing education
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ext continuing education.
	 *
	 * @param userId the user ID of this ext continuing education
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ext continuing education.
	 *
	 * @return the user uuid of this ext continuing education
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ext continuing education.
	 *
	 * @param userUuid the user uuid of this ext continuing education
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this ext continuing education.
	 *
	 * @return the create date of this ext continuing education
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ext continuing education.
	 *
	 * @param createDate the create date of this ext continuing education
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ext continuing education.
	 *
	 * @return the modified date of this ext continuing education
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ext continuing education.
	 *
	 * @param modifiedDate the modified date of this ext continuing education
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the institution or program of this ext continuing education.
	 *
	 * @return the institution or program of this ext continuing education
	 */
	@AutoEscape
	public String getInstitutionOrProgram();

	/**
	 * Sets the institution or program of this ext continuing education.
	 *
	 * @param institutionOrProgram the institution or program of this ext continuing education
	 */
	public void setInstitutionOrProgram(String institutionOrProgram);

	/**
	 * Returns the city of this ext continuing education.
	 *
	 * @return the city of this ext continuing education
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this ext continuing education.
	 *
	 * @param city the city of this ext continuing education
	 */
	public void setCity(String city);

	/**
	 * Returns the region ID of this ext continuing education.
	 *
	 * @return the region ID of this ext continuing education
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this ext continuing education.
	 *
	 * @param regionId the region ID of this ext continuing education
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the country ID of this ext continuing education.
	 *
	 * @return the country ID of this ext continuing education
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this ext continuing education.
	 *
	 * @param countryId the country ID of this ext continuing education
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the start date of attendance of this ext continuing education.
	 *
	 * @return the start date of attendance of this ext continuing education
	 */
	public Date getStartDateOfAttendance();

	/**
	 * Sets the start date of attendance of this ext continuing education.
	 *
	 * @param startDateOfAttendance the start date of attendance of this ext continuing education
	 */
	public void setStartDateOfAttendance(Date startDateOfAttendance);

	/**
	 * Returns the end date of attendance of this ext continuing education.
	 *
	 * @return the end date of attendance of this ext continuing education
	 */
	public Date getEndDateOfAttendance();

	/**
	 * Sets the end date of attendance of this ext continuing education.
	 *
	 * @param endDateOfAttendance the end date of attendance of this ext continuing education
	 */
	public void setEndDateOfAttendance(Date endDateOfAttendance);

	/**
	 * Returns the degree or certification of this ext continuing education.
	 *
	 * @return the degree or certification of this ext continuing education
	 */
	@AutoEscape
	public String getDegreeOrCertification();

	/**
	 * Sets the degree or certification of this ext continuing education.
	 *
	 * @param degreeOrCertification the degree or certification of this ext continuing education
	 */
	public void setDegreeOrCertification(String degreeOrCertification);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExtContinuingEducation extContinuingEducation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExtContinuingEducation> toCacheModel();

	@Override
	public ExtContinuingEducation toEscapedModel();

	@Override
	public ExtContinuingEducation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}