/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExtKeyAccomplishment service. Represents a row in the &quot;UCC_ExtKeyAccomplishment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.ExtKeyAccomplishmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.ExtKeyAccomplishmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtKeyAccomplishment
 * @see ucc.portal.model.impl.ExtKeyAccomplishmentImpl
 * @see ucc.portal.model.impl.ExtKeyAccomplishmentModelImpl
 * @generated
 */
@ProviderType
public interface ExtKeyAccomplishmentModel extends BaseModel<ExtKeyAccomplishment>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ext key accomplishment model instance should use the {@link ExtKeyAccomplishment} interface instead.
	 */

	/**
	 * Returns the primary key of this ext key accomplishment.
	 *
	 * @return the primary key of this ext key accomplishment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ext key accomplishment.
	 *
	 * @param primaryKey the primary key of this ext key accomplishment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ext key accomplishment ID of this ext key accomplishment.
	 *
	 * @return the ext key accomplishment ID of this ext key accomplishment
	 */
	public long getExtKeyAccomplishmentId();

	/**
	 * Sets the ext key accomplishment ID of this ext key accomplishment.
	 *
	 * @param extKeyAccomplishmentId the ext key accomplishment ID of this ext key accomplishment
	 */
	public void setExtKeyAccomplishmentId(long extKeyAccomplishmentId);

	/**
	 * Returns the company ID of this ext key accomplishment.
	 *
	 * @return the company ID of this ext key accomplishment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ext key accomplishment.
	 *
	 * @param companyId the company ID of this ext key accomplishment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ext key accomplishment.
	 *
	 * @return the user ID of this ext key accomplishment
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ext key accomplishment.
	 *
	 * @param userId the user ID of this ext key accomplishment
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ext key accomplishment.
	 *
	 * @return the user uuid of this ext key accomplishment
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ext key accomplishment.
	 *
	 * @param userUuid the user uuid of this ext key accomplishment
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this ext key accomplishment.
	 *
	 * @return the create date of this ext key accomplishment
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ext key accomplishment.
	 *
	 * @param createDate the create date of this ext key accomplishment
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ext key accomplishment.
	 *
	 * @return the modified date of this ext key accomplishment
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ext key accomplishment.
	 *
	 * @param modifiedDate the modified date of this ext key accomplishment
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the location or setting of this ext key accomplishment.
	 *
	 * @return the location or setting of this ext key accomplishment
	 */
	@AutoEscape
	public String getLocationOrSetting();

	/**
	 * Sets the location or setting of this ext key accomplishment.
	 *
	 * @param locationOrSetting the location or setting of this ext key accomplishment
	 */
	public void setLocationOrSetting(String locationOrSetting);

	/**
	 * Returns the description of this ext key accomplishment.
	 *
	 * @return the description of this ext key accomplishment
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this ext key accomplishment.
	 *
	 * @param description the description of this ext key accomplishment
	 */
	public void setDescription(String description);

	/**
	 * Returns the priority of this ext key accomplishment.
	 *
	 * @return the priority of this ext key accomplishment
	 */
	public double getPriority();

	/**
	 * Sets the priority of this ext key accomplishment.
	 *
	 * @param priority the priority of this ext key accomplishment
	 */
	public void setPriority(double priority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExtKeyAccomplishment extKeyAccomplishment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExtKeyAccomplishment> toCacheModel();

	@Override
	public ExtKeyAccomplishment toEscapedModel();

	@Override
	public ExtKeyAccomplishment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}