/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExtReference service. Represents a row in the &quot;UCC_ExtReference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.ExtReferenceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.ExtReferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtReference
 * @see ucc.portal.model.impl.ExtReferenceImpl
 * @see ucc.portal.model.impl.ExtReferenceModelImpl
 * @generated
 */
@ProviderType
public interface ExtReferenceModel extends BaseModel<ExtReference>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ext reference model instance should use the {@link ExtReference} interface instead.
	 */

	/**
	 * Returns the primary key of this ext reference.
	 *
	 * @return the primary key of this ext reference
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ext reference.
	 *
	 * @param primaryKey the primary key of this ext reference
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ext reference ID of this ext reference.
	 *
	 * @return the ext reference ID of this ext reference
	 */
	public long getExtReferenceId();

	/**
	 * Sets the ext reference ID of this ext reference.
	 *
	 * @param extReferenceId the ext reference ID of this ext reference
	 */
	public void setExtReferenceId(long extReferenceId);

	/**
	 * Returns the company ID of this ext reference.
	 *
	 * @return the company ID of this ext reference
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ext reference.
	 *
	 * @param companyId the company ID of this ext reference
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ext reference.
	 *
	 * @return the user ID of this ext reference
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ext reference.
	 *
	 * @param userId the user ID of this ext reference
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ext reference.
	 *
	 * @return the user uuid of this ext reference
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ext reference.
	 *
	 * @param userUuid the user uuid of this ext reference
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this ext reference.
	 *
	 * @return the create date of this ext reference
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ext reference.
	 *
	 * @param createDate the create date of this ext reference
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ext reference.
	 *
	 * @return the modified date of this ext reference
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ext reference.
	 *
	 * @param modifiedDate the modified date of this ext reference
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the reference user ID of this ext reference.
	 *
	 * @return the reference user ID of this ext reference
	 */
	public long getReferenceUserId();

	/**
	 * Sets the reference user ID of this ext reference.
	 *
	 * @param referenceUserId the reference user ID of this ext reference
	 */
	public void setReferenceUserId(long referenceUserId);

	/**
	 * Returns the reference user uuid of this ext reference.
	 *
	 * @return the reference user uuid of this ext reference
	 */
	public String getReferenceUserUuid();

	/**
	 * Sets the reference user uuid of this ext reference.
	 *
	 * @param referenceUserUuid the reference user uuid of this ext reference
	 */
	public void setReferenceUserUuid(String referenceUserUuid);

	/**
	 * Returns the user created of this ext reference.
	 *
	 * @return the user created of this ext reference
	 */
	public boolean getUserCreated();

	/**
	 * Returns <code>true</code> if this ext reference is user created.
	 *
	 * @return <code>true</code> if this ext reference is user created; <code>false</code> otherwise
	 */
	public boolean isUserCreated();

	/**
	 * Sets whether this ext reference is user created.
	 *
	 * @param userCreated the user created of this ext reference
	 */
	public void setUserCreated(boolean userCreated);

	/**
	 * Returns the email date of this ext reference.
	 *
	 * @return the email date of this ext reference
	 */
	public Date getEmailDate();

	/**
	 * Sets the email date of this ext reference.
	 *
	 * @param emailDate the email date of this ext reference
	 */
	public void setEmailDate(Date emailDate);

	/**
	 * Returns the resend email of this ext reference.
	 *
	 * @return the resend email of this ext reference
	 */
	public boolean getResendEmail();

	/**
	 * Returns <code>true</code> if this ext reference is resend email.
	 *
	 * @return <code>true</code> if this ext reference is resend email; <code>false</code> otherwise
	 */
	public boolean isResendEmail();

	/**
	 * Sets whether this ext reference is resend email.
	 *
	 * @param resendEmail the resend email of this ext reference
	 */
	public void setResendEmail(boolean resendEmail);

	/**
	 * Returns the role and relationship of this ext reference.
	 *
	 * @return the role and relationship of this ext reference
	 */
	@AutoEscape
	public String getRoleAndRelationship();

	/**
	 * Sets the role and relationship of this ext reference.
	 *
	 * @param roleAndRelationship the role and relationship of this ext reference
	 */
	public void setRoleAndRelationship(String roleAndRelationship);

	/**
	 * Returns the areas of strength of this ext reference.
	 *
	 * @return the areas of strength of this ext reference
	 */
	@AutoEscape
	public String getAreasOfStrength();

	/**
	 * Sets the areas of strength of this ext reference.
	 *
	 * @param areasOfStrength the areas of strength of this ext reference
	 */
	public void setAreasOfStrength(String areasOfStrength);

	/**
	 * Returns the areas of growth of this ext reference.
	 *
	 * @return the areas of growth of this ext reference
	 */
	@AutoEscape
	public String getAreasOfGrowth();

	/**
	 * Sets the areas of growth of this ext reference.
	 *
	 * @param areasOfGrowth the areas of growth of this ext reference
	 */
	public void setAreasOfGrowth(String areasOfGrowth);

	/**
	 * Returns the significant experience of this ext reference.
	 *
	 * @return the significant experience of this ext reference
	 */
	@AutoEscape
	public String getSignificantExperience();

	/**
	 * Sets the significant experience of this ext reference.
	 *
	 * @param significantExperience the significant experience of this ext reference
	 */
	public void setSignificantExperience(String significantExperience);

	/**
	 * Returns the additional comments of this ext reference.
	 *
	 * @return the additional comments of this ext reference
	 */
	@AutoEscape
	public String getAdditionalComments();

	/**
	 * Sets the additional comments of this ext reference.
	 *
	 * @param additionalComments the additional comments of this ext reference
	 */
	public void setAdditionalComments(String additionalComments);

	/**
	 * Returns the submit date of this ext reference.
	 *
	 * @return the submit date of this ext reference
	 */
	public Date getSubmitDate();

	/**
	 * Sets the submit date of this ext reference.
	 *
	 * @param submitDate the submit date of this ext reference
	 */
	public void setSubmitDate(Date submitDate);

	/**
	 * Returns the user first name of this ext reference.
	 *
	 * @return the user first name of this ext reference
	 */
	@AutoEscape
	public String getUserFirstName();

	/**
	 * Sets the user first name of this ext reference.
	 *
	 * @param userFirstName the user first name of this ext reference
	 */
	public void setUserFirstName(String userFirstName);

	/**
	 * Returns the user middle name of this ext reference.
	 *
	 * @return the user middle name of this ext reference
	 */
	@AutoEscape
	public String getUserMiddleName();

	/**
	 * Sets the user middle name of this ext reference.
	 *
	 * @param userMiddleName the user middle name of this ext reference
	 */
	public void setUserMiddleName(String userMiddleName);

	/**
	 * Returns the user last name of this ext reference.
	 *
	 * @return the user last name of this ext reference
	 */
	@AutoEscape
	public String getUserLastName();

	/**
	 * Sets the user last name of this ext reference.
	 *
	 * @param userLastName the user last name of this ext reference
	 */
	public void setUserLastName(String userLastName);

	/**
	 * Returns the user email address of this ext reference.
	 *
	 * @return the user email address of this ext reference
	 */
	@AutoEscape
	public String getUserEmailAddress();

	/**
	 * Sets the user email address of this ext reference.
	 *
	 * @param userEmailAddress the user email address of this ext reference
	 */
	public void setUserEmailAddress(String userEmailAddress);

	/**
	 * Returns the address street1 of this ext reference.
	 *
	 * @return the address street1 of this ext reference
	 */
	@AutoEscape
	public String getAddressStreet1();

	/**
	 * Sets the address street1 of this ext reference.
	 *
	 * @param addressStreet1 the address street1 of this ext reference
	 */
	public void setAddressStreet1(String addressStreet1);

	/**
	 * Returns the address street2 of this ext reference.
	 *
	 * @return the address street2 of this ext reference
	 */
	@AutoEscape
	public String getAddressStreet2();

	/**
	 * Sets the address street2 of this ext reference.
	 *
	 * @param addressStreet2 the address street2 of this ext reference
	 */
	public void setAddressStreet2(String addressStreet2);

	/**
	 * Returns the address street3 of this ext reference.
	 *
	 * @return the address street3 of this ext reference
	 */
	@AutoEscape
	public String getAddressStreet3();

	/**
	 * Sets the address street3 of this ext reference.
	 *
	 * @param addressStreet3 the address street3 of this ext reference
	 */
	public void setAddressStreet3(String addressStreet3);

	/**
	 * Returns the address city of this ext reference.
	 *
	 * @return the address city of this ext reference
	 */
	@AutoEscape
	public String getAddressCity();

	/**
	 * Sets the address city of this ext reference.
	 *
	 * @param addressCity the address city of this ext reference
	 */
	public void setAddressCity(String addressCity);

	/**
	 * Returns the address zip of this ext reference.
	 *
	 * @return the address zip of this ext reference
	 */
	@AutoEscape
	public String getAddressZip();

	/**
	 * Sets the address zip of this ext reference.
	 *
	 * @param addressZip the address zip of this ext reference
	 */
	public void setAddressZip(String addressZip);

	/**
	 * Returns the address region ID of this ext reference.
	 *
	 * @return the address region ID of this ext reference
	 */
	public long getAddressRegionId();

	/**
	 * Sets the address region ID of this ext reference.
	 *
	 * @param addressRegionId the address region ID of this ext reference
	 */
	public void setAddressRegionId(long addressRegionId);

	/**
	 * Returns the address country ID of this ext reference.
	 *
	 * @return the address country ID of this ext reference
	 */
	public long getAddressCountryId();

	/**
	 * Sets the address country ID of this ext reference.
	 *
	 * @param addressCountryId the address country ID of this ext reference
	 */
	public void setAddressCountryId(long addressCountryId);

	/**
	 * Returns the address type ID of this ext reference.
	 *
	 * @return the address type ID of this ext reference
	 */
	public int getAddressTypeId();

	/**
	 * Sets the address type ID of this ext reference.
	 *
	 * @param addressTypeId the address type ID of this ext reference
	 */
	public void setAddressTypeId(int addressTypeId);

	/**
	 * Returns the phone number of this ext reference.
	 *
	 * @return the phone number of this ext reference
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this ext reference.
	 *
	 * @param phoneNumber the phone number of this ext reference
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the phone extension of this ext reference.
	 *
	 * @return the phone extension of this ext reference
	 */
	@AutoEscape
	public String getPhoneExtension();

	/**
	 * Sets the phone extension of this ext reference.
	 *
	 * @param phoneExtension the phone extension of this ext reference
	 */
	public void setPhoneExtension(String phoneExtension);

	/**
	 * Returns the phone type ID of this ext reference.
	 *
	 * @return the phone type ID of this ext reference
	 */
	public int getPhoneTypeId();

	/**
	 * Sets the phone type ID of this ext reference.
	 *
	 * @param phoneTypeId the phone type ID of this ext reference
	 */
	public void setPhoneTypeId(int phoneTypeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExtReference extReference);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExtReference> toCacheModel();

	@Override
	public ExtReference toEscapedModel();

	@Override
	public ExtReference toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}