/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExtValidation service. Represents a row in the &quot;UCC_ExtValidation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.ExtValidationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.ExtValidationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtValidation
 * @see ucc.portal.model.impl.ExtValidationImpl
 * @see ucc.portal.model.impl.ExtValidationModelImpl
 * @generated
 */
@ProviderType
public interface ExtValidationModel extends BaseModel<ExtValidation>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ext validation model instance should use the {@link ExtValidation} interface instead.
	 */

	/**
	 * Returns the primary key of this ext validation.
	 *
	 * @return the primary key of this ext validation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ext validation.
	 *
	 * @param primaryKey the primary key of this ext validation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ext validation ID of this ext validation.
	 *
	 * @return the ext validation ID of this ext validation
	 */
	public long getExtValidationId();

	/**
	 * Sets the ext validation ID of this ext validation.
	 *
	 * @param extValidationId the ext validation ID of this ext validation
	 */
	public void setExtValidationId(long extValidationId);

	/**
	 * Returns the company ID of this ext validation.
	 *
	 * @return the company ID of this ext validation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ext validation.
	 *
	 * @param companyId the company ID of this ext validation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ext validation.
	 *
	 * @return the user ID of this ext validation
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ext validation.
	 *
	 * @param userId the user ID of this ext validation
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ext validation.
	 *
	 * @return the user uuid of this ext validation
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ext validation.
	 *
	 * @param userUuid the user uuid of this ext validation
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this ext validation.
	 *
	 * @return the create date of this ext validation
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ext validation.
	 *
	 * @param createDate the create date of this ext validation
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ext validation.
	 *
	 * @return the modified date of this ext validation
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ext validation.
	 *
	 * @param modifiedDate the modified date of this ext validation
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the profile file entry ID of this ext validation.
	 *
	 * @return the profile file entry ID of this ext validation
	 */
	public long getProfileFileEntryId();

	/**
	 * Sets the profile file entry ID of this ext validation.
	 *
	 * @param profileFileEntryId the profile file entry ID of this ext validation
	 */
	public void setProfileFileEntryId(long profileFileEntryId);

	/**
	 * Returns the profile file version ID of this ext validation.
	 *
	 * @return the profile file version ID of this ext validation
	 */
	public long getProfileFileVersionId();

	/**
	 * Sets the profile file version ID of this ext validation.
	 *
	 * @param profileFileVersionId the profile file version ID of this ext validation
	 */
	public void setProfileFileVersionId(long profileFileVersionId);

	/**
	 * Returns the validator user ID of this ext validation.
	 *
	 * @return the validator user ID of this ext validation
	 */
	public long getValidatorUserId();

	/**
	 * Sets the validator user ID of this ext validation.
	 *
	 * @param validatorUserId the validator user ID of this ext validation
	 */
	public void setValidatorUserId(long validatorUserId);

	/**
	 * Returns the validator user uuid of this ext validation.
	 *
	 * @return the validator user uuid of this ext validation
	 */
	public String getValidatorUserUuid();

	/**
	 * Sets the validator user uuid of this ext validation.
	 *
	 * @param validatorUserUuid the validator user uuid of this ext validation
	 */
	public void setValidatorUserUuid(String validatorUserUuid);

	/**
	 * Returns the email date of this ext validation.
	 *
	 * @return the email date of this ext validation
	 */
	public Date getEmailDate();

	/**
	 * Sets the email date of this ext validation.
	 *
	 * @param emailDate the email date of this ext validation
	 */
	public void setEmailDate(Date emailDate);

	/**
	 * Returns the current standing and fitness of this ext validation.
	 *
	 * @return the current standing and fitness of this ext validation
	 */
	public boolean getCurrentStandingAndFitness();

	/**
	 * Returns <code>true</code> if this ext validation is current standing and fitness.
	 *
	 * @return <code>true</code> if this ext validation is current standing and fitness; <code>false</code> otherwise
	 */
	public boolean isCurrentStandingAndFitness();

	/**
	 * Sets whether this ext validation is current standing and fitness.
	 *
	 * @param currentStandingAndFitness the current standing and fitness of this ext validation
	 */
	public void setCurrentStandingAndFitness(boolean currentStandingAndFitness);

	/**
	 * Returns the current criminal background check of this ext validation.
	 *
	 * @return the current criminal background check of this ext validation
	 */
	public boolean getCurrentCriminalBackgroundCheck();

	/**
	 * Returns <code>true</code> if this ext validation is current criminal background check.
	 *
	 * @return <code>true</code> if this ext validation is current criminal background check; <code>false</code> otherwise
	 */
	public boolean isCurrentCriminalBackgroundCheck();

	/**
	 * Sets whether this ext validation is current criminal background check.
	 *
	 * @param currentCriminalBackgroundCheck the current criminal background check of this ext validation
	 */
	public void setCurrentCriminalBackgroundCheck(
		boolean currentCriminalBackgroundCheck);

	/**
	 * Returns the accurate current employment of this ext validation.
	 *
	 * @return the accurate current employment of this ext validation
	 */
	public boolean getAccurateCurrentEmployment();

	/**
	 * Returns <code>true</code> if this ext validation is accurate current employment.
	 *
	 * @return <code>true</code> if this ext validation is accurate current employment; <code>false</code> otherwise
	 */
	public boolean isAccurateCurrentEmployment();

	/**
	 * Sets whether this ext validation is accurate current employment.
	 *
	 * @param accurateCurrentEmployment the accurate current employment of this ext validation
	 */
	public void setAccurateCurrentEmployment(boolean accurateCurrentEmployment);

	/**
	 * Returns the accurate self disclosure of this ext validation.
	 *
	 * @return the accurate self disclosure of this ext validation
	 */
	public boolean getAccurateSelfDisclosure();

	/**
	 * Returns <code>true</code> if this ext validation is accurate self disclosure.
	 *
	 * @return <code>true</code> if this ext validation is accurate self disclosure; <code>false</code> otherwise
	 */
	public boolean isAccurateSelfDisclosure();

	/**
	 * Sets whether this ext validation is accurate self disclosure.
	 *
	 * @param accurateSelfDisclosure the accurate self disclosure of this ext validation
	 */
	public void setAccurateSelfDisclosure(boolean accurateSelfDisclosure);

	/**
	 * Returns the signature json of this ext validation.
	 *
	 * @return the signature json of this ext validation
	 */
	@AutoEscape
	public String getSignatureJson();

	/**
	 * Sets the signature json of this ext validation.
	 *
	 * @param signatureJson the signature json of this ext validation
	 */
	public void setSignatureJson(String signatureJson);

	/**
	 * Returns the signature file entry ID of this ext validation.
	 *
	 * @return the signature file entry ID of this ext validation
	 */
	public long getSignatureFileEntryId();

	/**
	 * Sets the signature file entry ID of this ext validation.
	 *
	 * @param signatureFileEntryId the signature file entry ID of this ext validation
	 */
	public void setSignatureFileEntryId(long signatureFileEntryId);

	/**
	 * Returns the signature file version ID of this ext validation.
	 *
	 * @return the signature file version ID of this ext validation
	 */
	public long getSignatureFileVersionId();

	/**
	 * Sets the signature file version ID of this ext validation.
	 *
	 * @param signatureFileVersionId the signature file version ID of this ext validation
	 */
	public void setSignatureFileVersionId(long signatureFileVersionId);

	/**
	 * Returns the signature name of this ext validation.
	 *
	 * @return the signature name of this ext validation
	 */
	@AutoEscape
	public String getSignatureName();

	/**
	 * Sets the signature name of this ext validation.
	 *
	 * @param signatureName the signature name of this ext validation
	 */
	public void setSignatureName(String signatureName);

	/**
	 * Returns the signature timestamp of this ext validation.
	 *
	 * @return the signature timestamp of this ext validation
	 */
	public Date getSignatureTimestamp();

	/**
	 * Sets the signature timestamp of this ext validation.
	 *
	 * @param signatureTimestamp the signature timestamp of this ext validation
	 */
	public void setSignatureTimestamp(Date signatureTimestamp);

	/**
	 * Returns the signature title of this ext validation.
	 *
	 * @return the signature title of this ext validation
	 */
	@AutoEscape
	public String getSignatureTitle();

	/**
	 * Sets the signature title of this ext validation.
	 *
	 * @param signatureTitle the signature title of this ext validation
	 */
	public void setSignatureTitle(String signatureTitle);

	/**
	 * Returns the conference ID of this ext validation.
	 *
	 * @return the conference ID of this ext validation
	 */
	public long getConferenceId();

	/**
	 * Sets the conference ID of this ext validation.
	 *
	 * @param conferenceId the conference ID of this ext validation
	 */
	public void setConferenceId(long conferenceId);

	/**
	 * Returns the association ID of this ext validation.
	 *
	 * @return the association ID of this ext validation
	 */
	public long getAssociationId();

	/**
	 * Sets the association ID of this ext validation.
	 *
	 * @param associationId the association ID of this ext validation
	 */
	public void setAssociationId(long associationId);

	/**
	 * Returns the withhold validation of this ext validation.
	 *
	 * @return the withhold validation of this ext validation
	 */
	public boolean getWithholdValidation();

	/**
	 * Returns <code>true</code> if this ext validation is withhold validation.
	 *
	 * @return <code>true</code> if this ext validation is withhold validation; <code>false</code> otherwise
	 */
	public boolean isWithholdValidation();

	/**
	 * Sets whether this ext validation is withhold validation.
	 *
	 * @param withholdValidation the withhold validation of this ext validation
	 */
	public void setWithholdValidation(boolean withholdValidation);

	/**
	 * Returns the additional comments of this ext validation.
	 *
	 * @return the additional comments of this ext validation
	 */
	@AutoEscape
	public String getAdditionalComments();

	/**
	 * Sets the additional comments of this ext validation.
	 *
	 * @param additionalComments the additional comments of this ext validation
	 */
	public void setAdditionalComments(String additionalComments);

	/**
	 * Returns the submit date of this ext validation.
	 *
	 * @return the submit date of this ext validation
	 */
	public Date getSubmitDate();

	/**
	 * Sets the submit date of this ext validation.
	 *
	 * @param submitDate the submit date of this ext validation
	 */
	public void setSubmitDate(Date submitDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExtValidation extValidation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExtValidation> toCacheModel();

	@Override
	public ExtValidation toEscapedModel();

	@Override
	public ExtValidation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}