/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExtVocationalHistory service. Represents a row in the &quot;UCC_ExtVocationalHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.ExtVocationalHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.ExtVocationalHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtVocationalHistory
 * @see ucc.portal.model.impl.ExtVocationalHistoryImpl
 * @see ucc.portal.model.impl.ExtVocationalHistoryModelImpl
 * @generated
 */
@ProviderType
public interface ExtVocationalHistoryModel extends BaseModel<ExtVocationalHistory>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ext vocational history model instance should use the {@link ExtVocationalHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this ext vocational history.
	 *
	 * @return the primary key of this ext vocational history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ext vocational history.
	 *
	 * @param primaryKey the primary key of this ext vocational history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ext vocational history ID of this ext vocational history.
	 *
	 * @return the ext vocational history ID of this ext vocational history
	 */
	public long getExtVocationalHistoryId();

	/**
	 * Sets the ext vocational history ID of this ext vocational history.
	 *
	 * @param extVocationalHistoryId the ext vocational history ID of this ext vocational history
	 */
	public void setExtVocationalHistoryId(long extVocationalHistoryId);

	/**
	 * Returns the company ID of this ext vocational history.
	 *
	 * @return the company ID of this ext vocational history
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ext vocational history.
	 *
	 * @param companyId the company ID of this ext vocational history
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ext vocational history.
	 *
	 * @return the user ID of this ext vocational history
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ext vocational history.
	 *
	 * @param userId the user ID of this ext vocational history
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ext vocational history.
	 *
	 * @return the user uuid of this ext vocational history
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ext vocational history.
	 *
	 * @param userUuid the user uuid of this ext vocational history
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this ext vocational history.
	 *
	 * @return the create date of this ext vocational history
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ext vocational history.
	 *
	 * @param createDate the create date of this ext vocational history
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ext vocational history.
	 *
	 * @return the modified date of this ext vocational history
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ext vocational history.
	 *
	 * @param modifiedDate the modified date of this ext vocational history
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the location or setting of this ext vocational history.
	 *
	 * @return the location or setting of this ext vocational history
	 */
	@AutoEscape
	public String getLocationOrSetting();

	/**
	 * Sets the location or setting of this ext vocational history.
	 *
	 * @param locationOrSetting the location or setting of this ext vocational history
	 */
	public void setLocationOrSetting(String locationOrSetting);

	/**
	 * Returns the city of this ext vocational history.
	 *
	 * @return the city of this ext vocational history
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this ext vocational history.
	 *
	 * @param city the city of this ext vocational history
	 */
	public void setCity(String city);

	/**
	 * Returns the region ID of this ext vocational history.
	 *
	 * @return the region ID of this ext vocational history
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this ext vocational history.
	 *
	 * @param regionId the region ID of this ext vocational history
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the country ID of this ext vocational history.
	 *
	 * @return the country ID of this ext vocational history
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this ext vocational history.
	 *
	 * @param countryId the country ID of this ext vocational history
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the start date of service of this ext vocational history.
	 *
	 * @return the start date of service of this ext vocational history
	 */
	public Date getStartDateOfService();

	/**
	 * Sets the start date of service of this ext vocational history.
	 *
	 * @param startDateOfService the start date of service of this ext vocational history
	 */
	public void setStartDateOfService(Date startDateOfService);

	/**
	 * Returns the end date of service of this ext vocational history.
	 *
	 * @return the end date of service of this ext vocational history
	 */
	public Date getEndDateOfService();

	/**
	 * Sets the end date of service of this ext vocational history.
	 *
	 * @param endDateOfService the end date of service of this ext vocational history
	 */
	public void setEndDateOfService(Date endDateOfService);

	/**
	 * Returns the title or position of this ext vocational history.
	 *
	 * @return the title or position of this ext vocational history
	 */
	@AutoEscape
	public String getTitleOrPosition();

	/**
	 * Sets the title or position of this ext vocational history.
	 *
	 * @param titleOrPosition the title or position of this ext vocational history
	 */
	public void setTitleOrPosition(String titleOrPosition);

	/**
	 * Returns the job type ID of this ext vocational history.
	 *
	 * @return the job type ID of this ext vocational history
	 */
	public int getJobTypeId();

	/**
	 * Sets the job type ID of this ext vocational history.
	 *
	 * @param jobTypeId the job type ID of this ext vocational history
	 */
	public void setJobTypeId(int jobTypeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExtVocationalHistory extVocationalHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExtVocationalHistory> toCacheModel();

	@Override
	public ExtVocationalHistory toEscapedModel();

	@Override
	public ExtVocationalHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}