/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the UccPeopleChurchStanding service. Represents a row in the &quot;UCC_Data_Warehouse.dbo.People_Church_Standing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.UccPeopleChurchStandingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.UccPeopleChurchStandingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UccPeopleChurchStanding
 * @see ucc.portal.model.impl.UccPeopleChurchStandingImpl
 * @see ucc.portal.model.impl.UccPeopleChurchStandingModelImpl
 * @generated
 */
@ProviderType
public interface UccPeopleChurchStandingModel extends BaseModel<UccPeopleChurchStanding> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ucc people church standing model instance should use the {@link UccPeopleChurchStanding} interface instead.
	 */

	/**
	 * Returns the primary key of this ucc people church standing.
	 *
	 * @return the primary key of this ucc people church standing
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ucc people church standing.
	 *
	 * @param primaryKey the primary key of this ucc people church standing
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ucc people church standing ID of this ucc people church standing.
	 *
	 * @return the ucc people church standing ID of this ucc people church standing
	 */
	public int getUccPeopleChurchStandingId();

	/**
	 * Sets the ucc people church standing ID of this ucc people church standing.
	 *
	 * @param uccPeopleChurchStandingId the ucc people church standing ID of this ucc people church standing
	 */
	public void setUccPeopleChurchStandingId(int uccPeopleChurchStandingId);

	/**
	 * Returns the ucc people ID of this ucc people church standing.
	 *
	 * @return the ucc people ID of this ucc people church standing
	 */
	public int getUccPeopleId();

	/**
	 * Sets the ucc people ID of this ucc people church standing.
	 *
	 * @param uccPeopleId the ucc people ID of this ucc people church standing
	 */
	public void setUccPeopleId(int uccPeopleId);

	/**
	 * Returns the ucc conference ID of this ucc people church standing.
	 *
	 * @return the ucc conference ID of this ucc people church standing
	 */
	public int getUccConferenceId();

	/**
	 * Sets the ucc conference ID of this ucc people church standing.
	 *
	 * @param uccConferenceId the ucc conference ID of this ucc people church standing
	 */
	public void setUccConferenceId(int uccConferenceId);

	/**
	 * Returns the ucc association ID of this ucc people church standing.
	 *
	 * @return the ucc association ID of this ucc people church standing
	 */
	public int getUccAssociationId();

	/**
	 * Sets the ucc association ID of this ucc people church standing.
	 *
	 * @param uccAssociationId the ucc association ID of this ucc people church standing
	 */
	public void setUccAssociationId(int uccAssociationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UccPeopleChurchStanding uccPeopleChurchStanding);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UccPeopleChurchStanding> toCacheModel();

	@Override
	public UccPeopleChurchStanding toEscapedModel();

	@Override
	public UccPeopleChurchStanding toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}