/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the UccPeople service. Represents a row in the &quot;UCC_Data_Warehouse.dbo.People&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.UccPeopleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.UccPeopleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UccPeople
 * @see ucc.portal.model.impl.UccPeopleImpl
 * @see ucc.portal.model.impl.UccPeopleModelImpl
 * @generated
 */
@ProviderType
public interface UccPeopleModel extends BaseModel<UccPeople> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ucc people model instance should use the {@link UccPeople} interface instead.
	 */

	/**
	 * Returns the primary key of this ucc people.
	 *
	 * @return the primary key of this ucc people
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ucc people.
	 *
	 * @param primaryKey the primary key of this ucc people
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ucc people ID of this ucc people.
	 *
	 * @return the ucc people ID of this ucc people
	 */
	public int getUccPeopleId();

	/**
	 * Sets the ucc people ID of this ucc people.
	 *
	 * @param uccPeopleId the ucc people ID of this ucc people
	 */
	public void setUccPeopleId(int uccPeopleId);

	/**
	 * Returns the first name of this ucc people.
	 *
	 * @return the first name of this ucc people
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this ucc people.
	 *
	 * @param firstName the first name of this ucc people
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this ucc people.
	 *
	 * @return the middle name of this ucc people
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this ucc people.
	 *
	 * @param middleName the middle name of this ucc people
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this ucc people.
	 *
	 * @return the last name of this ucc people
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this ucc people.
	 *
	 * @param lastName the last name of this ucc people
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the suffix of this ucc people.
	 *
	 * @return the suffix of this ucc people
	 */
	@AutoEscape
	public String getSuffix();

	/**
	 * Sets the suffix of this ucc people.
	 *
	 * @param suffix the suffix of this ucc people
	 */
	public void setSuffix(String suffix);

	/**
	 * Returns the birthday of this ucc people.
	 *
	 * @return the birthday of this ucc people
	 */
	@AutoEscape
	public String getBirthday();

	/**
	 * Sets the birthday of this ucc people.
	 *
	 * @param birthday the birthday of this ucc people
	 */
	public void setBirthday(String birthday);

	/**
	 * Returns the my active of this ucc people.
	 *
	 * @return the my active of this ucc people
	 */
	public boolean getMyActive();

	/**
	 * Returns <code>true</code> if this ucc people is my active.
	 *
	 * @return <code>true</code> if this ucc people is my active; <code>false</code> otherwise
	 */
	public boolean isMyActive();

	/**
	 * Sets whether this ucc people is my active.
	 *
	 * @param myActive the my active of this ucc people
	 */
	public void setMyActive(boolean myActive);

	/**
	 * Returns the old ucc people ID of this ucc people.
	 *
	 * @return the old ucc people ID of this ucc people
	 */
	public int getOldUccPeopleId();

	/**
	 * Sets the old ucc people ID of this ucc people.
	 *
	 * @param oldUccPeopleId the old ucc people ID of this ucc people
	 */
	public void setOldUccPeopleId(int oldUccPeopleId);

	/**
	 * Returns the phone of this ucc people.
	 *
	 * @return the phone of this ucc people
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this ucc people.
	 *
	 * @param phone the phone of this ucc people
	 */
	public void setPhone(String phone);

	/**
	 * Returns the email address of this ucc people.
	 *
	 * @return the email address of this ucc people
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this ucc people.
	 *
	 * @param emailAddress the email address of this ucc people
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the cell phone of this ucc people.
	 *
	 * @return the cell phone of this ucc people
	 */
	@AutoEscape
	public String getCellPhone();

	/**
	 * Sets the cell phone of this ucc people.
	 *
	 * @param cellPhone the cell phone of this ucc people
	 */
	public void setCellPhone(String cellPhone);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UccPeople uccPeople);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UccPeople> toCacheModel();

	@Override
	public UccPeople toEscapedModel();

	@Override
	public UccPeople toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}