/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UccPeopleAddress service. Represents a row in the &quot;UCC_Data_Warehouse.dbo.People_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ucc.portal.model.impl.UccPeopleAddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ucc.portal.model.impl.UccPeopleAddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UccPeopleAddress
 * @see ucc.portal.model.impl.UccPeopleAddressImpl
 * @see ucc.portal.model.impl.UccPeopleAddressModelImpl
 * @generated
 */
@ProviderType
public interface UccPeopleAddressModel extends BaseModel<UccPeopleAddress> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ucc people address model instance should use the {@link UccPeopleAddress} interface instead.
	 */

	/**
	 * Returns the primary key of this ucc people address.
	 *
	 * @return the primary key of this ucc people address
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ucc people address.
	 *
	 * @param primaryKey the primary key of this ucc people address
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ucc people address ID of this ucc people address.
	 *
	 * @return the ucc people address ID of this ucc people address
	 */
	public int getUccPeopleAddressId();

	/**
	 * Sets the ucc people address ID of this ucc people address.
	 *
	 * @param uccPeopleAddressId the ucc people address ID of this ucc people address
	 */
	public void setUccPeopleAddressId(int uccPeopleAddressId);

	/**
	 * Returns the ucc people ID of this ucc people address.
	 *
	 * @return the ucc people ID of this ucc people address
	 */
	public int getUccPeopleId();

	/**
	 * Sets the ucc people ID of this ucc people address.
	 *
	 * @param uccPeopleId the ucc people ID of this ucc people address
	 */
	public void setUccPeopleId(int uccPeopleId);

	/**
	 * Returns the street1 of this ucc people address.
	 *
	 * @return the street1 of this ucc people address
	 */
	@AutoEscape
	public String getStreet1();

	/**
	 * Sets the street1 of this ucc people address.
	 *
	 * @param street1 the street1 of this ucc people address
	 */
	public void setStreet1(String street1);

	/**
	 * Returns the street2 of this ucc people address.
	 *
	 * @return the street2 of this ucc people address
	 */
	@AutoEscape
	public String getStreet2();

	/**
	 * Sets the street2 of this ucc people address.
	 *
	 * @param street2 the street2 of this ucc people address
	 */
	public void setStreet2(String street2);

	/**
	 * Returns the city of this ucc people address.
	 *
	 * @return the city of this ucc people address
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this ucc people address.
	 *
	 * @param city the city of this ucc people address
	 */
	public void setCity(String city);

	/**
	 * Returns the region of this ucc people address.
	 *
	 * @return the region of this ucc people address
	 */
	@AutoEscape
	public String getRegion();

	/**
	 * Sets the region of this ucc people address.
	 *
	 * @param region the region of this ucc people address
	 */
	public void setRegion(String region);

	/**
	 * Returns the zip of this ucc people address.
	 *
	 * @return the zip of this ucc people address
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this ucc people address.
	 *
	 * @param zip the zip of this ucc people address
	 */
	public void setZip(String zip);

	/**
	 * Returns the zip plus of this ucc people address.
	 *
	 * @return the zip plus of this ucc people address
	 */
	@AutoEscape
	public String getZipPlus();

	/**
	 * Sets the zip plus of this ucc people address.
	 *
	 * @param zipPlus the zip plus of this ucc people address
	 */
	public void setZipPlus(String zipPlus);

	/**
	 * Returns the type of this ucc people address.
	 *
	 * @return the type of this ucc people address
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this ucc people address.
	 *
	 * @param type the type of this ucc people address
	 */
	public void setType(String type);

	/**
	 * Returns the country of this ucc people address.
	 *
	 * @return the country of this ucc people address
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this ucc people address.
	 *
	 * @param country the country of this ucc people address
	 */
	public void setCountry(String country);

	/**
	 * Returns the my active of this ucc people address.
	 *
	 * @return the my active of this ucc people address
	 */
	public boolean getMyActive();

	/**
	 * Returns <code>true</code> if this ucc people address is my active.
	 *
	 * @return <code>true</code> if this ucc people address is my active; <code>false</code> otherwise
	 */
	public boolean isMyActive();

	/**
	 * Sets whether this ucc people address is my active.
	 *
	 * @param myActive the my active of this ucc people address
	 */
	public void setMyActive(boolean myActive);

	/**
	 * Returns the inactive date of this ucc people address.
	 *
	 * @return the inactive date of this ucc people address
	 */
	public Date getInactiveDate();

	/**
	 * Sets the inactive date of this ucc people address.
	 *
	 * @param inactiveDate the inactive date of this ucc people address
	 */
	public void setInactiveDate(Date inactiveDate);

	/**
	 * Returns the modified by of this ucc people address.
	 *
	 * @return the modified by of this ucc people address
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this ucc people address.
	 *
	 * @param modifiedBy the modified by of this ucc people address
	 */
	public void setModifiedBy(String modifiedBy);

	/**
	 * Returns the modified date of this ucc people address.
	 *
	 * @return the modified date of this ucc people address
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ucc people address.
	 *
	 * @param modifiedDate the modified date of this ucc people address
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UccPeopleAddress uccPeopleAddress);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UccPeopleAddress> toCacheModel();

	@Override
	public UccPeopleAddress toEscapedModel();

	@Override
	public UccPeopleAddress toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}