/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import contact.manager.service.model.CCA;
import contact.manager.service.model.CCAModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CCA service. Represents a row in the &quot;contactmanager_CCA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CCAModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CCAImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CCAImpl
 * @see CCA
 * @see CCAModel
 * @generated
 */
@ProviderType
public class CCAModelImpl extends BaseModelImpl<CCA> implements CCAModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cca model instance should use the {@link CCA} interface instead.
	 */
	public static final String TABLE_NAME = "contactmanager_CCA";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ccaId", Types.BIGINT },
			{ "ccaName", Types.VARCHAR },
			{ "zipCode", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ccaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ccaName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zipCode", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table contactmanager_CCA (ccaId LONG not null primary key,ccaName VARCHAR(75) null,zipCode VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table contactmanager_CCA";
	public static final String ORDER_BY_JPQL = " ORDER BY cca.ccaName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY contactmanager_CCA.ccaName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.contact.manager.service.model.CCA"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.contact.manager.service.model.CCA"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(contact.manager.service.service.util.ServiceProps.get(
				"lock.expiration.time.contact.manager.service.model.CCA"));

	public CCAModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ccaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCcaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ccaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CCA.class;
	}

	@Override
	public String getModelClassName() {
		return CCA.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ccaId", getCcaId());
		attributes.put("ccaName", getCcaName());
		attributes.put("zipCode", getZipCode());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ccaId = (Long)attributes.get("ccaId");

		if (ccaId != null) {
			setCcaId(ccaId);
		}

		String ccaName = (String)attributes.get("ccaName");

		if (ccaName != null) {
			setCcaName(ccaName);
		}

		String zipCode = (String)attributes.get("zipCode");

		if (zipCode != null) {
			setZipCode(zipCode);
		}
	}

	@Override
	public long getCcaId() {
		return _ccaId;
	}

	@Override
	public void setCcaId(long ccaId) {
		_ccaId = ccaId;
	}

	@Override
	public String getCcaName() {
		if (_ccaName == null) {
			return StringPool.BLANK;
		}
		else {
			return _ccaName;
		}
	}

	@Override
	public void setCcaName(String ccaName) {
		_ccaName = ccaName;
	}

	@Override
	public String getZipCode() {
		if (_zipCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _zipCode;
		}
	}

	@Override
	public void setZipCode(String zipCode) {
		_zipCode = zipCode;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CCA.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CCA toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CCA)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CCAImpl ccaImpl = new CCAImpl();

		ccaImpl.setCcaId(getCcaId());
		ccaImpl.setCcaName(getCcaName());
		ccaImpl.setZipCode(getZipCode());

		ccaImpl.resetOriginalValues();

		return ccaImpl;
	}

	@Override
	public int compareTo(CCA cca) {
		int value = 0;

		value = getCcaName().compareTo(cca.getCcaName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CCA)) {
			return false;
		}

		CCA cca = (CCA)obj;

		long primaryKey = cca.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<CCA> toCacheModel() {
		CCACacheModel ccaCacheModel = new CCACacheModel();

		ccaCacheModel.ccaId = getCcaId();

		ccaCacheModel.ccaName = getCcaName();

		String ccaName = ccaCacheModel.ccaName;

		if ((ccaName != null) && (ccaName.length() == 0)) {
			ccaCacheModel.ccaName = null;
		}

		ccaCacheModel.zipCode = getZipCode();

		String zipCode = ccaCacheModel.zipCode;

		if ((zipCode != null) && (zipCode.length() == 0)) {
			ccaCacheModel.zipCode = null;
		}

		return ccaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{ccaId=");
		sb.append(getCcaId());
		sb.append(", ccaName=");
		sb.append(getCcaName());
		sb.append(", zipCode=");
		sb.append(getZipCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("contact.manager.service.model.CCA");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ccaId</column-name><column-value><![CDATA[");
		sb.append(getCcaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccaName</column-name><column-value><![CDATA[");
		sb.append(getCcaName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zipCode</column-name><column-value><![CDATA[");
		sb.append(getZipCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CCA.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CCA.class
		};
	private long _ccaId;
	private String _ccaName;
	private String _zipCode;
	private CCA _escapedModel;
}