/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import contact.manager.service.model.ContactAuditLog;
import contact.manager.service.service.ContactAuditLogLocalServiceUtil;

/**
 * The extended model base implementation for the ContactAuditLog service. Represents a row in the &quot;contactmanager_ContactAuditLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactAuditLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactAuditLogImpl
 * @see ContactAuditLog
 * @generated
 */
@ProviderType
public abstract class ContactAuditLogBaseImpl extends ContactAuditLogModelImpl
	implements ContactAuditLog {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contact audit log model instance should use the {@link ContactAuditLog} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ContactAuditLogLocalServiceUtil.addContactAuditLog(this);
		}
		else {
			ContactAuditLogLocalServiceUtil.updateContactAuditLog(this);
		}
	}
}