/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import contact.manager.service.model.Contact;
import contact.manager.service.model.ContactModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Contact service. Represents a row in the &quot;contactmanager_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ContactModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactImpl
 * @see Contact
 * @see ContactModel
 * @generated
 */
@ProviderType
public class ContactModelImpl extends BaseModelImpl<Contact>
	implements ContactModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contact model instance should use the {@link Contact} interface instead.
	 */
	public static final String TABLE_NAME = "contactmanager_Contact";
	public static final Object[][] TABLE_COLUMNS = {
			{ "contactId", Types.BIGINT },
			{ "constantContactId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "prefix", Types.VARCHAR },
			{ "salutation", Types.VARCHAR },
			{ "firstName", Types.VARCHAR },
			{ "middleName", Types.VARCHAR },
			{ "lastName", Types.VARCHAR },
			{ "organization", Types.VARCHAR },
			{ "jobTitle", Types.VARCHAR },
			{ "primaryAddress1", Types.VARCHAR },
			{ "primaryAddress2", Types.VARCHAR },
			{ "primaryAddressCity", Types.VARCHAR },
			{ "primaryAddressState", Types.VARCHAR },
			{ "primaryAddressZip", Types.VARCHAR },
			{ "primaryAddressCounty", Types.VARCHAR },
			{ "primaryAddressCountry", Types.VARCHAR },
			{ "secondaryAddress1", Types.VARCHAR },
			{ "secondaryAddress2", Types.VARCHAR },
			{ "secondaryAddressCity", Types.VARCHAR },
			{ "secondaryAddressState", Types.VARCHAR },
			{ "secondaryAddressZip", Types.VARCHAR },
			{ "secondaryAddressCounty", Types.VARCHAR },
			{ "secondaryAddressCountry", Types.VARCHAR },
			{ "primaryPhone", Types.VARCHAR },
			{ "primaryFax", Types.VARCHAR },
			{ "primaryCell", Types.VARCHAR },
			{ "primaryEmailAddress", Types.VARCHAR },
			{ "alternateContact", Types.VARCHAR },
			{ "alternateEmail", Types.VARCHAR },
			{ "isVip", Types.BOOLEAN },
			{ "facebookId", Types.VARCHAR },
			{ "twitterHandle", Types.VARCHAR },
			{ "linkedInUrl", Types.VARCHAR },
			{ "status", Types.VARCHAR },
			{ "kioskUuid", Types.VARCHAR },
			{ "imageFileEntryId", Types.BIGINT },
			{ "tagsList", Types.VARCHAR },
			{ "subGroupsList", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("contactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("constantContactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("prefix", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("salutation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("middleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("organization", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddress1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddress2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressCity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressState", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressZip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressCounty", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryAddressCountry", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddress1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddress2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressCity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressState", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressZip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressCounty", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryAddressCountry", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryPhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryFax", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryCell", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryEmailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("alternateContact", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("alternateEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isVip", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("facebookId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("twitterHandle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkedInUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kioskUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tagsList", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subGroupsList", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table contactmanager_Contact (contactId LONG not null primary key,constantContactId LONG,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,prefix VARCHAR(75) null,salutation VARCHAR(75) null,firstName VARCHAR(75) null,middleName VARCHAR(75) null,lastName VARCHAR(75) null,organization VARCHAR(75) null,jobTitle VARCHAR(75) null,primaryAddress1 VARCHAR(75) null,primaryAddress2 VARCHAR(75) null,primaryAddressCity VARCHAR(75) null,primaryAddressState VARCHAR(75) null,primaryAddressZip VARCHAR(75) null,primaryAddressCounty VARCHAR(75) null,primaryAddressCountry VARCHAR(75) null,secondaryAddress1 VARCHAR(75) null,secondaryAddress2 VARCHAR(75) null,secondaryAddressCity VARCHAR(75) null,secondaryAddressState VARCHAR(75) null,secondaryAddressZip VARCHAR(75) null,secondaryAddressCounty VARCHAR(75) null,secondaryAddressCountry VARCHAR(75) null,primaryPhone VARCHAR(75) null,primaryFax VARCHAR(75) null,primaryCell VARCHAR(75) null,primaryEmailAddress VARCHAR(75) null,alternateContact VARCHAR(75) null,alternateEmail VARCHAR(75) null,isVip BOOLEAN,facebookId VARCHAR(75) null,twitterHandle VARCHAR(75) null,linkedInUrl VARCHAR(75) null,status VARCHAR(75) null,kioskUuid VARCHAR(75) null,imageFileEntryId LONG,tagsList VARCHAR(75) null,subGroupsList VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table contactmanager_Contact";
	public static final String ORDER_BY_JPQL = " ORDER BY contact.lastName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY contactmanager_Contact.lastName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.contact.manager.service.model.Contact"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.contact.manager.service.model.Contact"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.contact.manager.service.model.Contact"),
			true);
	public static final long CONSTANTCONTACTID_COLUMN_BITMASK = 1L;
	public static final long ISVIP_COLUMN_BITMASK = 2L;
	public static final long PRIMARYEMAILADDRESS_COLUMN_BITMASK = 4L;
	public static final long STATUS_COLUMN_BITMASK = 8L;
	public static final long LASTNAME_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(contact.manager.service.service.util.ServiceProps.get(
				"lock.expiration.time.contact.manager.service.model.Contact"));

	public ContactModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contactId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContactId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contactId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Contact.class;
	}

	@Override
	public String getModelClassName() {
		return Contact.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("contactId", getContactId());
		attributes.put("constantContactId", getConstantContactId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("prefix", getPrefix());
		attributes.put("salutation", getSalutation());
		attributes.put("firstName", getFirstName());
		attributes.put("middleName", getMiddleName());
		attributes.put("lastName", getLastName());
		attributes.put("organization", getOrganization());
		attributes.put("jobTitle", getJobTitle());
		attributes.put("primaryAddress1", getPrimaryAddress1());
		attributes.put("primaryAddress2", getPrimaryAddress2());
		attributes.put("primaryAddressCity", getPrimaryAddressCity());
		attributes.put("primaryAddressState", getPrimaryAddressState());
		attributes.put("primaryAddressZip", getPrimaryAddressZip());
		attributes.put("primaryAddressCounty", getPrimaryAddressCounty());
		attributes.put("primaryAddressCountry", getPrimaryAddressCountry());
		attributes.put("secondaryAddress1", getSecondaryAddress1());
		attributes.put("secondaryAddress2", getSecondaryAddress2());
		attributes.put("secondaryAddressCity", getSecondaryAddressCity());
		attributes.put("secondaryAddressState", getSecondaryAddressState());
		attributes.put("secondaryAddressZip", getSecondaryAddressZip());
		attributes.put("secondaryAddressCounty", getSecondaryAddressCounty());
		attributes.put("secondaryAddressCountry", getSecondaryAddressCountry());
		attributes.put("primaryPhone", getPrimaryPhone());
		attributes.put("primaryFax", getPrimaryFax());
		attributes.put("primaryCell", getPrimaryCell());
		attributes.put("primaryEmailAddress", getPrimaryEmailAddress());
		attributes.put("alternateContact", getAlternateContact());
		attributes.put("alternateEmail", getAlternateEmail());
		attributes.put("isVip", getIsVip());
		attributes.put("facebookId", getFacebookId());
		attributes.put("twitterHandle", getTwitterHandle());
		attributes.put("linkedInUrl", getLinkedInUrl());
		attributes.put("status", getStatus());
		attributes.put("kioskUuid", getKioskUuid());
		attributes.put("imageFileEntryId", getImageFileEntryId());
		attributes.put("tagsList", getTagsList());
		attributes.put("subGroupsList", getSubGroupsList());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long contactId = (Long)attributes.get("contactId");

		if (contactId != null) {
			setContactId(contactId);
		}

		Long constantContactId = (Long)attributes.get("constantContactId");

		if (constantContactId != null) {
			setConstantContactId(constantContactId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String prefix = (String)attributes.get("prefix");

		if (prefix != null) {
			setPrefix(prefix);
		}

		String salutation = (String)attributes.get("salutation");

		if (salutation != null) {
			setSalutation(salutation);
		}

		String firstName = (String)attributes.get("firstName");

		if (firstName != null) {
			setFirstName(firstName);
		}

		String middleName = (String)attributes.get("middleName");

		if (middleName != null) {
			setMiddleName(middleName);
		}

		String lastName = (String)attributes.get("lastName");

		if (lastName != null) {
			setLastName(lastName);
		}

		String organization = (String)attributes.get("organization");

		if (organization != null) {
			setOrganization(organization);
		}

		String jobTitle = (String)attributes.get("jobTitle");

		if (jobTitle != null) {
			setJobTitle(jobTitle);
		}

		String primaryAddress1 = (String)attributes.get("primaryAddress1");

		if (primaryAddress1 != null) {
			setPrimaryAddress1(primaryAddress1);
		}

		String primaryAddress2 = (String)attributes.get("primaryAddress2");

		if (primaryAddress2 != null) {
			setPrimaryAddress2(primaryAddress2);
		}

		String primaryAddressCity = (String)attributes.get("primaryAddressCity");

		if (primaryAddressCity != null) {
			setPrimaryAddressCity(primaryAddressCity);
		}

		String primaryAddressState = (String)attributes.get(
				"primaryAddressState");

		if (primaryAddressState != null) {
			setPrimaryAddressState(primaryAddressState);
		}

		String primaryAddressZip = (String)attributes.get("primaryAddressZip");

		if (primaryAddressZip != null) {
			setPrimaryAddressZip(primaryAddressZip);
		}

		String primaryAddressCounty = (String)attributes.get(
				"primaryAddressCounty");

		if (primaryAddressCounty != null) {
			setPrimaryAddressCounty(primaryAddressCounty);
		}

		String primaryAddressCountry = (String)attributes.get(
				"primaryAddressCountry");

		if (primaryAddressCountry != null) {
			setPrimaryAddressCountry(primaryAddressCountry);
		}

		String secondaryAddress1 = (String)attributes.get("secondaryAddress1");

		if (secondaryAddress1 != null) {
			setSecondaryAddress1(secondaryAddress1);
		}

		String secondaryAddress2 = (String)attributes.get("secondaryAddress2");

		if (secondaryAddress2 != null) {
			setSecondaryAddress2(secondaryAddress2);
		}

		String secondaryAddressCity = (String)attributes.get(
				"secondaryAddressCity");

		if (secondaryAddressCity != null) {
			setSecondaryAddressCity(secondaryAddressCity);
		}

		String secondaryAddressState = (String)attributes.get(
				"secondaryAddressState");

		if (secondaryAddressState != null) {
			setSecondaryAddressState(secondaryAddressState);
		}

		String secondaryAddressZip = (String)attributes.get(
				"secondaryAddressZip");

		if (secondaryAddressZip != null) {
			setSecondaryAddressZip(secondaryAddressZip);
		}

		String secondaryAddressCounty = (String)attributes.get(
				"secondaryAddressCounty");

		if (secondaryAddressCounty != null) {
			setSecondaryAddressCounty(secondaryAddressCounty);
		}

		String secondaryAddressCountry = (String)attributes.get(
				"secondaryAddressCountry");

		if (secondaryAddressCountry != null) {
			setSecondaryAddressCountry(secondaryAddressCountry);
		}

		String primaryPhone = (String)attributes.get("primaryPhone");

		if (primaryPhone != null) {
			setPrimaryPhone(primaryPhone);
		}

		String primaryFax = (String)attributes.get("primaryFax");

		if (primaryFax != null) {
			setPrimaryFax(primaryFax);
		}

		String primaryCell = (String)attributes.get("primaryCell");

		if (primaryCell != null) {
			setPrimaryCell(primaryCell);
		}

		String primaryEmailAddress = (String)attributes.get(
				"primaryEmailAddress");

		if (primaryEmailAddress != null) {
			setPrimaryEmailAddress(primaryEmailAddress);
		}

		String alternateContact = (String)attributes.get("alternateContact");

		if (alternateContact != null) {
			setAlternateContact(alternateContact);
		}

		String alternateEmail = (String)attributes.get("alternateEmail");

		if (alternateEmail != null) {
			setAlternateEmail(alternateEmail);
		}

		Boolean isVip = (Boolean)attributes.get("isVip");

		if (isVip != null) {
			setIsVip(isVip);
		}

		String facebookId = (String)attributes.get("facebookId");

		if (facebookId != null) {
			setFacebookId(facebookId);
		}

		String twitterHandle = (String)attributes.get("twitterHandle");

		if (twitterHandle != null) {
			setTwitterHandle(twitterHandle);
		}

		String linkedInUrl = (String)attributes.get("linkedInUrl");

		if (linkedInUrl != null) {
			setLinkedInUrl(linkedInUrl);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String kioskUuid = (String)attributes.get("kioskUuid");

		if (kioskUuid != null) {
			setKioskUuid(kioskUuid);
		}

		Long imageFileEntryId = (Long)attributes.get("imageFileEntryId");

		if (imageFileEntryId != null) {
			setImageFileEntryId(imageFileEntryId);
		}

		String tagsList = (String)attributes.get("tagsList");

		if (tagsList != null) {
			setTagsList(tagsList);
		}

		String subGroupsList = (String)attributes.get("subGroupsList");

		if (subGroupsList != null) {
			setSubGroupsList(subGroupsList);
		}
	}

	@Override
	public long getContactId() {
		return _contactId;
	}

	@Override
	public void setContactId(long contactId) {
		_contactId = contactId;
	}

	@Override
	public long getConstantContactId() {
		return _constantContactId;
	}

	@Override
	public void setConstantContactId(long constantContactId) {
		_columnBitmask |= CONSTANTCONTACTID_COLUMN_BITMASK;

		if (!_setOriginalConstantContactId) {
			_setOriginalConstantContactId = true;

			_originalConstantContactId = _constantContactId;
		}

		_constantContactId = constantContactId;
	}

	public long getOriginalConstantContactId() {
		return _originalConstantContactId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getPrefix() {
		if (_prefix == null) {
			return StringPool.BLANK;
		}
		else {
			return _prefix;
		}
	}

	@Override
	public void setPrefix(String prefix) {
		_prefix = prefix;
	}

	@Override
	public String getSalutation() {
		if (_salutation == null) {
			return StringPool.BLANK;
		}
		else {
			return _salutation;
		}
	}

	@Override
	public void setSalutation(String salutation) {
		_salutation = salutation;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return StringPool.BLANK;
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@Override
	public String getMiddleName() {
		if (_middleName == null) {
			return StringPool.BLANK;
		}
		else {
			return _middleName;
		}
	}

	@Override
	public void setMiddleName(String middleName) {
		_middleName = middleName;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_columnBitmask = -1L;

		_lastName = lastName;
	}

	@Override
	public String getOrganization() {
		if (_organization == null) {
			return StringPool.BLANK;
		}
		else {
			return _organization;
		}
	}

	@Override
	public void setOrganization(String organization) {
		_organization = organization;
	}

	@Override
	public String getJobTitle() {
		if (_jobTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _jobTitle;
		}
	}

	@Override
	public void setJobTitle(String jobTitle) {
		_jobTitle = jobTitle;
	}

	@Override
	public String getPrimaryAddress1() {
		if (_primaryAddress1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddress1;
		}
	}

	@Override
	public void setPrimaryAddress1(String primaryAddress1) {
		_primaryAddress1 = primaryAddress1;
	}

	@Override
	public String getPrimaryAddress2() {
		if (_primaryAddress2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddress2;
		}
	}

	@Override
	public void setPrimaryAddress2(String primaryAddress2) {
		_primaryAddress2 = primaryAddress2;
	}

	@Override
	public String getPrimaryAddressCity() {
		if (_primaryAddressCity == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressCity;
		}
	}

	@Override
	public void setPrimaryAddressCity(String primaryAddressCity) {
		_primaryAddressCity = primaryAddressCity;
	}

	@Override
	public String getPrimaryAddressState() {
		if (_primaryAddressState == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressState;
		}
	}

	@Override
	public void setPrimaryAddressState(String primaryAddressState) {
		_primaryAddressState = primaryAddressState;
	}

	@Override
	public String getPrimaryAddressZip() {
		if (_primaryAddressZip == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressZip;
		}
	}

	@Override
	public void setPrimaryAddressZip(String primaryAddressZip) {
		_primaryAddressZip = primaryAddressZip;
	}

	@Override
	public String getPrimaryAddressCounty() {
		if (_primaryAddressCounty == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressCounty;
		}
	}

	@Override
	public void setPrimaryAddressCounty(String primaryAddressCounty) {
		_primaryAddressCounty = primaryAddressCounty;
	}

	@Override
	public String getPrimaryAddressCountry() {
		if (_primaryAddressCountry == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryAddressCountry;
		}
	}

	@Override
	public void setPrimaryAddressCountry(String primaryAddressCountry) {
		_primaryAddressCountry = primaryAddressCountry;
	}

	@Override
	public String getSecondaryAddress1() {
		if (_secondaryAddress1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddress1;
		}
	}

	@Override
	public void setSecondaryAddress1(String secondaryAddress1) {
		_secondaryAddress1 = secondaryAddress1;
	}

	@Override
	public String getSecondaryAddress2() {
		if (_secondaryAddress2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddress2;
		}
	}

	@Override
	public void setSecondaryAddress2(String secondaryAddress2) {
		_secondaryAddress2 = secondaryAddress2;
	}

	@Override
	public String getSecondaryAddressCity() {
		if (_secondaryAddressCity == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressCity;
		}
	}

	@Override
	public void setSecondaryAddressCity(String secondaryAddressCity) {
		_secondaryAddressCity = secondaryAddressCity;
	}

	@Override
	public String getSecondaryAddressState() {
		if (_secondaryAddressState == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressState;
		}
	}

	@Override
	public void setSecondaryAddressState(String secondaryAddressState) {
		_secondaryAddressState = secondaryAddressState;
	}

	@Override
	public String getSecondaryAddressZip() {
		if (_secondaryAddressZip == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressZip;
		}
	}

	@Override
	public void setSecondaryAddressZip(String secondaryAddressZip) {
		_secondaryAddressZip = secondaryAddressZip;
	}

	@Override
	public String getSecondaryAddressCounty() {
		if (_secondaryAddressCounty == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressCounty;
		}
	}

	@Override
	public void setSecondaryAddressCounty(String secondaryAddressCounty) {
		_secondaryAddressCounty = secondaryAddressCounty;
	}

	@Override
	public String getSecondaryAddressCountry() {
		if (_secondaryAddressCountry == null) {
			return StringPool.BLANK;
		}
		else {
			return _secondaryAddressCountry;
		}
	}

	@Override
	public void setSecondaryAddressCountry(String secondaryAddressCountry) {
		_secondaryAddressCountry = secondaryAddressCountry;
	}

	@Override
	public String getPrimaryPhone() {
		if (_primaryPhone == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryPhone;
		}
	}

	@Override
	public void setPrimaryPhone(String primaryPhone) {
		_primaryPhone = primaryPhone;
	}

	@Override
	public String getPrimaryFax() {
		if (_primaryFax == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryFax;
		}
	}

	@Override
	public void setPrimaryFax(String primaryFax) {
		_primaryFax = primaryFax;
	}

	@Override
	public String getPrimaryCell() {
		if (_primaryCell == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryCell;
		}
	}

	@Override
	public void setPrimaryCell(String primaryCell) {
		_primaryCell = primaryCell;
	}

	@Override
	public String getPrimaryEmailAddress() {
		if (_primaryEmailAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryEmailAddress;
		}
	}

	@Override
	public void setPrimaryEmailAddress(String primaryEmailAddress) {
		_columnBitmask |= PRIMARYEMAILADDRESS_COLUMN_BITMASK;

		if (_originalPrimaryEmailAddress == null) {
			_originalPrimaryEmailAddress = _primaryEmailAddress;
		}

		_primaryEmailAddress = primaryEmailAddress;
	}

	public String getOriginalPrimaryEmailAddress() {
		return GetterUtil.getString(_originalPrimaryEmailAddress);
	}

	@Override
	public String getAlternateContact() {
		if (_alternateContact == null) {
			return StringPool.BLANK;
		}
		else {
			return _alternateContact;
		}
	}

	@Override
	public void setAlternateContact(String alternateContact) {
		_alternateContact = alternateContact;
	}

	@Override
	public String getAlternateEmail() {
		if (_alternateEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _alternateEmail;
		}
	}

	@Override
	public void setAlternateEmail(String alternateEmail) {
		_alternateEmail = alternateEmail;
	}

	@Override
	public boolean getIsVip() {
		return _isVip;
	}

	@Override
	public boolean isIsVip() {
		return _isVip;
	}

	@Override
	public void setIsVip(boolean isVip) {
		_columnBitmask |= ISVIP_COLUMN_BITMASK;

		if (!_setOriginalIsVip) {
			_setOriginalIsVip = true;

			_originalIsVip = _isVip;
		}

		_isVip = isVip;
	}

	public boolean getOriginalIsVip() {
		return _originalIsVip;
	}

	@Override
	public String getFacebookId() {
		if (_facebookId == null) {
			return StringPool.BLANK;
		}
		else {
			return _facebookId;
		}
	}

	@Override
	public void setFacebookId(String facebookId) {
		_facebookId = facebookId;
	}

	@Override
	public String getTwitterHandle() {
		if (_twitterHandle == null) {
			return StringPool.BLANK;
		}
		else {
			return _twitterHandle;
		}
	}

	@Override
	public void setTwitterHandle(String twitterHandle) {
		_twitterHandle = twitterHandle;
	}

	@Override
	public String getLinkedInUrl() {
		if (_linkedInUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _linkedInUrl;
		}
	}

	@Override
	public void setLinkedInUrl(String linkedInUrl) {
		_linkedInUrl = linkedInUrl;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (_originalStatus == null) {
			_originalStatus = _status;
		}

		_status = status;
	}

	public String getOriginalStatus() {
		return GetterUtil.getString(_originalStatus);
	}

	@Override
	public String getKioskUuid() {
		if (_kioskUuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _kioskUuid;
		}
	}

	@Override
	public void setKioskUuid(String kioskUuid) {
		_kioskUuid = kioskUuid;
	}

	@Override
	public long getImageFileEntryId() {
		return _imageFileEntryId;
	}

	@Override
	public void setImageFileEntryId(long imageFileEntryId) {
		_imageFileEntryId = imageFileEntryId;
	}

	@Override
	public String getTagsList() {
		if (_tagsList == null) {
			return StringPool.BLANK;
		}
		else {
			return _tagsList;
		}
	}

	@Override
	public void setTagsList(String tagsList) {
		_tagsList = tagsList;
	}

	@Override
	public String getSubGroupsList() {
		if (_subGroupsList == null) {
			return StringPool.BLANK;
		}
		else {
			return _subGroupsList;
		}
	}

	@Override
	public void setSubGroupsList(String subGroupsList) {
		_subGroupsList = subGroupsList;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Contact.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Contact toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Contact)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContactImpl contactImpl = new ContactImpl();

		contactImpl.setContactId(getContactId());
		contactImpl.setConstantContactId(getConstantContactId());
		contactImpl.setGroupId(getGroupId());
		contactImpl.setCompanyId(getCompanyId());
		contactImpl.setUserId(getUserId());
		contactImpl.setCreateDate(getCreateDate());
		contactImpl.setModifiedDate(getModifiedDate());
		contactImpl.setPrefix(getPrefix());
		contactImpl.setSalutation(getSalutation());
		contactImpl.setFirstName(getFirstName());
		contactImpl.setMiddleName(getMiddleName());
		contactImpl.setLastName(getLastName());
		contactImpl.setOrganization(getOrganization());
		contactImpl.setJobTitle(getJobTitle());
		contactImpl.setPrimaryAddress1(getPrimaryAddress1());
		contactImpl.setPrimaryAddress2(getPrimaryAddress2());
		contactImpl.setPrimaryAddressCity(getPrimaryAddressCity());
		contactImpl.setPrimaryAddressState(getPrimaryAddressState());
		contactImpl.setPrimaryAddressZip(getPrimaryAddressZip());
		contactImpl.setPrimaryAddressCounty(getPrimaryAddressCounty());
		contactImpl.setPrimaryAddressCountry(getPrimaryAddressCountry());
		contactImpl.setSecondaryAddress1(getSecondaryAddress1());
		contactImpl.setSecondaryAddress2(getSecondaryAddress2());
		contactImpl.setSecondaryAddressCity(getSecondaryAddressCity());
		contactImpl.setSecondaryAddressState(getSecondaryAddressState());
		contactImpl.setSecondaryAddressZip(getSecondaryAddressZip());
		contactImpl.setSecondaryAddressCounty(getSecondaryAddressCounty());
		contactImpl.setSecondaryAddressCountry(getSecondaryAddressCountry());
		contactImpl.setPrimaryPhone(getPrimaryPhone());
		contactImpl.setPrimaryFax(getPrimaryFax());
		contactImpl.setPrimaryCell(getPrimaryCell());
		contactImpl.setPrimaryEmailAddress(getPrimaryEmailAddress());
		contactImpl.setAlternateContact(getAlternateContact());
		contactImpl.setAlternateEmail(getAlternateEmail());
		contactImpl.setIsVip(getIsVip());
		contactImpl.setFacebookId(getFacebookId());
		contactImpl.setTwitterHandle(getTwitterHandle());
		contactImpl.setLinkedInUrl(getLinkedInUrl());
		contactImpl.setStatus(getStatus());
		contactImpl.setKioskUuid(getKioskUuid());
		contactImpl.setImageFileEntryId(getImageFileEntryId());
		contactImpl.setTagsList(getTagsList());
		contactImpl.setSubGroupsList(getSubGroupsList());

		contactImpl.resetOriginalValues();

		return contactImpl;
	}

	@Override
	public int compareTo(Contact contact) {
		int value = 0;

		value = getLastName().compareTo(contact.getLastName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Contact)) {
			return false;
		}

		Contact contact = (Contact)obj;

		long primaryKey = contact.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ContactModelImpl contactModelImpl = this;

		contactModelImpl._originalConstantContactId = contactModelImpl._constantContactId;

		contactModelImpl._setOriginalConstantContactId = false;

		contactModelImpl._setModifiedDate = false;

		contactModelImpl._originalPrimaryEmailAddress = contactModelImpl._primaryEmailAddress;

		contactModelImpl._originalIsVip = contactModelImpl._isVip;

		contactModelImpl._setOriginalIsVip = false;

		contactModelImpl._originalStatus = contactModelImpl._status;

		contactModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Contact> toCacheModel() {
		ContactCacheModel contactCacheModel = new ContactCacheModel();

		contactCacheModel.contactId = getContactId();

		contactCacheModel.constantContactId = getConstantContactId();

		contactCacheModel.groupId = getGroupId();

		contactCacheModel.companyId = getCompanyId();

		contactCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			contactCacheModel.createDate = createDate.getTime();
		}
		else {
			contactCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			contactCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			contactCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		contactCacheModel.prefix = getPrefix();

		String prefix = contactCacheModel.prefix;

		if ((prefix != null) && (prefix.length() == 0)) {
			contactCacheModel.prefix = null;
		}

		contactCacheModel.salutation = getSalutation();

		String salutation = contactCacheModel.salutation;

		if ((salutation != null) && (salutation.length() == 0)) {
			contactCacheModel.salutation = null;
		}

		contactCacheModel.firstName = getFirstName();

		String firstName = contactCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			contactCacheModel.firstName = null;
		}

		contactCacheModel.middleName = getMiddleName();

		String middleName = contactCacheModel.middleName;

		if ((middleName != null) && (middleName.length() == 0)) {
			contactCacheModel.middleName = null;
		}

		contactCacheModel.lastName = getLastName();

		String lastName = contactCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			contactCacheModel.lastName = null;
		}

		contactCacheModel.organization = getOrganization();

		String organization = contactCacheModel.organization;

		if ((organization != null) && (organization.length() == 0)) {
			contactCacheModel.organization = null;
		}

		contactCacheModel.jobTitle = getJobTitle();

		String jobTitle = contactCacheModel.jobTitle;

		if ((jobTitle != null) && (jobTitle.length() == 0)) {
			contactCacheModel.jobTitle = null;
		}

		contactCacheModel.primaryAddress1 = getPrimaryAddress1();

		String primaryAddress1 = contactCacheModel.primaryAddress1;

		if ((primaryAddress1 != null) && (primaryAddress1.length() == 0)) {
			contactCacheModel.primaryAddress1 = null;
		}

		contactCacheModel.primaryAddress2 = getPrimaryAddress2();

		String primaryAddress2 = contactCacheModel.primaryAddress2;

		if ((primaryAddress2 != null) && (primaryAddress2.length() == 0)) {
			contactCacheModel.primaryAddress2 = null;
		}

		contactCacheModel.primaryAddressCity = getPrimaryAddressCity();

		String primaryAddressCity = contactCacheModel.primaryAddressCity;

		if ((primaryAddressCity != null) && (primaryAddressCity.length() == 0)) {
			contactCacheModel.primaryAddressCity = null;
		}

		contactCacheModel.primaryAddressState = getPrimaryAddressState();

		String primaryAddressState = contactCacheModel.primaryAddressState;

		if ((primaryAddressState != null) &&
				(primaryAddressState.length() == 0)) {
			contactCacheModel.primaryAddressState = null;
		}

		contactCacheModel.primaryAddressZip = getPrimaryAddressZip();

		String primaryAddressZip = contactCacheModel.primaryAddressZip;

		if ((primaryAddressZip != null) && (primaryAddressZip.length() == 0)) {
			contactCacheModel.primaryAddressZip = null;
		}

		contactCacheModel.primaryAddressCounty = getPrimaryAddressCounty();

		String primaryAddressCounty = contactCacheModel.primaryAddressCounty;

		if ((primaryAddressCounty != null) &&
				(primaryAddressCounty.length() == 0)) {
			contactCacheModel.primaryAddressCounty = null;
		}

		contactCacheModel.primaryAddressCountry = getPrimaryAddressCountry();

		String primaryAddressCountry = contactCacheModel.primaryAddressCountry;

		if ((primaryAddressCountry != null) &&
				(primaryAddressCountry.length() == 0)) {
			contactCacheModel.primaryAddressCountry = null;
		}

		contactCacheModel.secondaryAddress1 = getSecondaryAddress1();

		String secondaryAddress1 = contactCacheModel.secondaryAddress1;

		if ((secondaryAddress1 != null) && (secondaryAddress1.length() == 0)) {
			contactCacheModel.secondaryAddress1 = null;
		}

		contactCacheModel.secondaryAddress2 = getSecondaryAddress2();

		String secondaryAddress2 = contactCacheModel.secondaryAddress2;

		if ((secondaryAddress2 != null) && (secondaryAddress2.length() == 0)) {
			contactCacheModel.secondaryAddress2 = null;
		}

		contactCacheModel.secondaryAddressCity = getSecondaryAddressCity();

		String secondaryAddressCity = contactCacheModel.secondaryAddressCity;

		if ((secondaryAddressCity != null) &&
				(secondaryAddressCity.length() == 0)) {
			contactCacheModel.secondaryAddressCity = null;
		}

		contactCacheModel.secondaryAddressState = getSecondaryAddressState();

		String secondaryAddressState = contactCacheModel.secondaryAddressState;

		if ((secondaryAddressState != null) &&
				(secondaryAddressState.length() == 0)) {
			contactCacheModel.secondaryAddressState = null;
		}

		contactCacheModel.secondaryAddressZip = getSecondaryAddressZip();

		String secondaryAddressZip = contactCacheModel.secondaryAddressZip;

		if ((secondaryAddressZip != null) &&
				(secondaryAddressZip.length() == 0)) {
			contactCacheModel.secondaryAddressZip = null;
		}

		contactCacheModel.secondaryAddressCounty = getSecondaryAddressCounty();

		String secondaryAddressCounty = contactCacheModel.secondaryAddressCounty;

		if ((secondaryAddressCounty != null) &&
				(secondaryAddressCounty.length() == 0)) {
			contactCacheModel.secondaryAddressCounty = null;
		}

		contactCacheModel.secondaryAddressCountry = getSecondaryAddressCountry();

		String secondaryAddressCountry = contactCacheModel.secondaryAddressCountry;

		if ((secondaryAddressCountry != null) &&
				(secondaryAddressCountry.length() == 0)) {
			contactCacheModel.secondaryAddressCountry = null;
		}

		contactCacheModel.primaryPhone = getPrimaryPhone();

		String primaryPhone = contactCacheModel.primaryPhone;

		if ((primaryPhone != null) && (primaryPhone.length() == 0)) {
			contactCacheModel.primaryPhone = null;
		}

		contactCacheModel.primaryFax = getPrimaryFax();

		String primaryFax = contactCacheModel.primaryFax;

		if ((primaryFax != null) && (primaryFax.length() == 0)) {
			contactCacheModel.primaryFax = null;
		}

		contactCacheModel.primaryCell = getPrimaryCell();

		String primaryCell = contactCacheModel.primaryCell;

		if ((primaryCell != null) && (primaryCell.length() == 0)) {
			contactCacheModel.primaryCell = null;
		}

		contactCacheModel.primaryEmailAddress = getPrimaryEmailAddress();

		String primaryEmailAddress = contactCacheModel.primaryEmailAddress;

		if ((primaryEmailAddress != null) &&
				(primaryEmailAddress.length() == 0)) {
			contactCacheModel.primaryEmailAddress = null;
		}

		contactCacheModel.alternateContact = getAlternateContact();

		String alternateContact = contactCacheModel.alternateContact;

		if ((alternateContact != null) && (alternateContact.length() == 0)) {
			contactCacheModel.alternateContact = null;
		}

		contactCacheModel.alternateEmail = getAlternateEmail();

		String alternateEmail = contactCacheModel.alternateEmail;

		if ((alternateEmail != null) && (alternateEmail.length() == 0)) {
			contactCacheModel.alternateEmail = null;
		}

		contactCacheModel.isVip = getIsVip();

		contactCacheModel.facebookId = getFacebookId();

		String facebookId = contactCacheModel.facebookId;

		if ((facebookId != null) && (facebookId.length() == 0)) {
			contactCacheModel.facebookId = null;
		}

		contactCacheModel.twitterHandle = getTwitterHandle();

		String twitterHandle = contactCacheModel.twitterHandle;

		if ((twitterHandle != null) && (twitterHandle.length() == 0)) {
			contactCacheModel.twitterHandle = null;
		}

		contactCacheModel.linkedInUrl = getLinkedInUrl();

		String linkedInUrl = contactCacheModel.linkedInUrl;

		if ((linkedInUrl != null) && (linkedInUrl.length() == 0)) {
			contactCacheModel.linkedInUrl = null;
		}

		contactCacheModel.status = getStatus();

		String status = contactCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			contactCacheModel.status = null;
		}

		contactCacheModel.kioskUuid = getKioskUuid();

		String kioskUuid = contactCacheModel.kioskUuid;

		if ((kioskUuid != null) && (kioskUuid.length() == 0)) {
			contactCacheModel.kioskUuid = null;
		}

		contactCacheModel.imageFileEntryId = getImageFileEntryId();

		contactCacheModel.tagsList = getTagsList();

		String tagsList = contactCacheModel.tagsList;

		if ((tagsList != null) && (tagsList.length() == 0)) {
			contactCacheModel.tagsList = null;
		}

		contactCacheModel.subGroupsList = getSubGroupsList();

		String subGroupsList = contactCacheModel.subGroupsList;

		if ((subGroupsList != null) && (subGroupsList.length() == 0)) {
			contactCacheModel.subGroupsList = null;
		}

		return contactCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(87);

		sb.append("{contactId=");
		sb.append(getContactId());
		sb.append(", constantContactId=");
		sb.append(getConstantContactId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", prefix=");
		sb.append(getPrefix());
		sb.append(", salutation=");
		sb.append(getSalutation());
		sb.append(", firstName=");
		sb.append(getFirstName());
		sb.append(", middleName=");
		sb.append(getMiddleName());
		sb.append(", lastName=");
		sb.append(getLastName());
		sb.append(", organization=");
		sb.append(getOrganization());
		sb.append(", jobTitle=");
		sb.append(getJobTitle());
		sb.append(", primaryAddress1=");
		sb.append(getPrimaryAddress1());
		sb.append(", primaryAddress2=");
		sb.append(getPrimaryAddress2());
		sb.append(", primaryAddressCity=");
		sb.append(getPrimaryAddressCity());
		sb.append(", primaryAddressState=");
		sb.append(getPrimaryAddressState());
		sb.append(", primaryAddressZip=");
		sb.append(getPrimaryAddressZip());
		sb.append(", primaryAddressCounty=");
		sb.append(getPrimaryAddressCounty());
		sb.append(", primaryAddressCountry=");
		sb.append(getPrimaryAddressCountry());
		sb.append(", secondaryAddress1=");
		sb.append(getSecondaryAddress1());
		sb.append(", secondaryAddress2=");
		sb.append(getSecondaryAddress2());
		sb.append(", secondaryAddressCity=");
		sb.append(getSecondaryAddressCity());
		sb.append(", secondaryAddressState=");
		sb.append(getSecondaryAddressState());
		sb.append(", secondaryAddressZip=");
		sb.append(getSecondaryAddressZip());
		sb.append(", secondaryAddressCounty=");
		sb.append(getSecondaryAddressCounty());
		sb.append(", secondaryAddressCountry=");
		sb.append(getSecondaryAddressCountry());
		sb.append(", primaryPhone=");
		sb.append(getPrimaryPhone());
		sb.append(", primaryFax=");
		sb.append(getPrimaryFax());
		sb.append(", primaryCell=");
		sb.append(getPrimaryCell());
		sb.append(", primaryEmailAddress=");
		sb.append(getPrimaryEmailAddress());
		sb.append(", alternateContact=");
		sb.append(getAlternateContact());
		sb.append(", alternateEmail=");
		sb.append(getAlternateEmail());
		sb.append(", isVip=");
		sb.append(getIsVip());
		sb.append(", facebookId=");
		sb.append(getFacebookId());
		sb.append(", twitterHandle=");
		sb.append(getTwitterHandle());
		sb.append(", linkedInUrl=");
		sb.append(getLinkedInUrl());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", kioskUuid=");
		sb.append(getKioskUuid());
		sb.append(", imageFileEntryId=");
		sb.append(getImageFileEntryId());
		sb.append(", tagsList=");
		sb.append(getTagsList());
		sb.append(", subGroupsList=");
		sb.append(getSubGroupsList());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(133);

		sb.append("<model><model-name>");
		sb.append("contact.manager.service.model.Contact");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>contactId</column-name><column-value><![CDATA[");
		sb.append(getContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>constantContactId</column-name><column-value><![CDATA[");
		sb.append(getConstantContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>prefix</column-name><column-value><![CDATA[");
		sb.append(getPrefix());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>salutation</column-name><column-value><![CDATA[");
		sb.append(getSalutation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>firstName</column-name><column-value><![CDATA[");
		sb.append(getFirstName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>middleName</column-name><column-value><![CDATA[");
		sb.append(getMiddleName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastName</column-name><column-value><![CDATA[");
		sb.append(getLastName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organization</column-name><column-value><![CDATA[");
		sb.append(getOrganization());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jobTitle</column-name><column-value><![CDATA[");
		sb.append(getJobTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddress1</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddress1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddress2</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddress2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressCity</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressState</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressZip</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressZip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressCounty</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressCounty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryAddressCountry</column-name><column-value><![CDATA[");
		sb.append(getPrimaryAddressCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddress1</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddress1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddress2</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddress2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressCity</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressState</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressZip</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressZip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressCounty</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressCounty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secondaryAddressCountry</column-name><column-value><![CDATA[");
		sb.append(getSecondaryAddressCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryPhone</column-name><column-value><![CDATA[");
		sb.append(getPrimaryPhone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryFax</column-name><column-value><![CDATA[");
		sb.append(getPrimaryFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryCell</column-name><column-value><![CDATA[");
		sb.append(getPrimaryCell());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>primaryEmailAddress</column-name><column-value><![CDATA[");
		sb.append(getPrimaryEmailAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>alternateContact</column-name><column-value><![CDATA[");
		sb.append(getAlternateContact());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>alternateEmail</column-name><column-value><![CDATA[");
		sb.append(getAlternateEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isVip</column-name><column-value><![CDATA[");
		sb.append(getIsVip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facebookId</column-name><column-value><![CDATA[");
		sb.append(getFacebookId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>twitterHandle</column-name><column-value><![CDATA[");
		sb.append(getTwitterHandle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>linkedInUrl</column-name><column-value><![CDATA[");
		sb.append(getLinkedInUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kioskUuid</column-name><column-value><![CDATA[");
		sb.append(getKioskUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageFileEntryId</column-name><column-value><![CDATA[");
		sb.append(getImageFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagsList</column-name><column-value><![CDATA[");
		sb.append(getTagsList());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subGroupsList</column-name><column-value><![CDATA[");
		sb.append(getSubGroupsList());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Contact.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Contact.class
		};
	private long _contactId;
	private long _constantContactId;
	private long _originalConstantContactId;
	private boolean _setOriginalConstantContactId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _prefix;
	private String _salutation;
	private String _firstName;
	private String _middleName;
	private String _lastName;
	private String _organization;
	private String _jobTitle;
	private String _primaryAddress1;
	private String _primaryAddress2;
	private String _primaryAddressCity;
	private String _primaryAddressState;
	private String _primaryAddressZip;
	private String _primaryAddressCounty;
	private String _primaryAddressCountry;
	private String _secondaryAddress1;
	private String _secondaryAddress2;
	private String _secondaryAddressCity;
	private String _secondaryAddressState;
	private String _secondaryAddressZip;
	private String _secondaryAddressCounty;
	private String _secondaryAddressCountry;
	private String _primaryPhone;
	private String _primaryFax;
	private String _primaryCell;
	private String _primaryEmailAddress;
	private String _originalPrimaryEmailAddress;
	private String _alternateContact;
	private String _alternateEmail;
	private boolean _isVip;
	private boolean _originalIsVip;
	private boolean _setOriginalIsVip;
	private String _facebookId;
	private String _twitterHandle;
	private String _linkedInUrl;
	private String _status;
	private String _originalStatus;
	private String _kioskUuid;
	private long _imageFileEntryId;
	private String _tagsList;
	private String _subGroupsList;
	private long _columnBitmask;
	private Contact _escapedModel;
}