/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import contact.manager.service.model.LTA;
import contact.manager.service.model.LTAModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LTA service. Represents a row in the &quot;contactmanager_LTA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LTAModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LTAImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LTAImpl
 * @see LTA
 * @see LTAModel
 * @generated
 */
@ProviderType
public class LTAModelImpl extends BaseModelImpl<LTA> implements LTAModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lta model instance should use the {@link LTA} interface instead.
	 */
	public static final String TABLE_NAME = "contactmanager_LTA";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ltaId", Types.BIGINT },
			{ "ltaName", Types.VARCHAR },
			{ "zipCode", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ltaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ltaName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zipCode", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table contactmanager_LTA (ltaId LONG not null primary key,ltaName VARCHAR(75) null,zipCode VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table contactmanager_LTA";
	public static final String ORDER_BY_JPQL = " ORDER BY lta.ltaName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY contactmanager_LTA.ltaName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.contact.manager.service.model.LTA"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.contact.manager.service.model.LTA"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.contact.manager.service.model.LTA"),
			true);
	public static final long ZIPCODE_COLUMN_BITMASK = 1L;
	public static final long LTANAME_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(contact.manager.service.service.util.ServiceProps.get(
				"lock.expiration.time.contact.manager.service.model.LTA"));

	public LTAModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ltaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLtaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ltaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LTA.class;
	}

	@Override
	public String getModelClassName() {
		return LTA.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ltaId", getLtaId());
		attributes.put("ltaName", getLtaName());
		attributes.put("zipCode", getZipCode());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ltaId = (Long)attributes.get("ltaId");

		if (ltaId != null) {
			setLtaId(ltaId);
		}

		String ltaName = (String)attributes.get("ltaName");

		if (ltaName != null) {
			setLtaName(ltaName);
		}

		String zipCode = (String)attributes.get("zipCode");

		if (zipCode != null) {
			setZipCode(zipCode);
		}
	}

	@Override
	public long getLtaId() {
		return _ltaId;
	}

	@Override
	public void setLtaId(long ltaId) {
		_ltaId = ltaId;
	}

	@Override
	public String getLtaName() {
		if (_ltaName == null) {
			return StringPool.BLANK;
		}
		else {
			return _ltaName;
		}
	}

	@Override
	public void setLtaName(String ltaName) {
		_columnBitmask = -1L;

		_ltaName = ltaName;
	}

	@Override
	public String getZipCode() {
		if (_zipCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _zipCode;
		}
	}

	@Override
	public void setZipCode(String zipCode) {
		_columnBitmask |= ZIPCODE_COLUMN_BITMASK;

		if (_originalZipCode == null) {
			_originalZipCode = _zipCode;
		}

		_zipCode = zipCode;
	}

	public String getOriginalZipCode() {
		return GetterUtil.getString(_originalZipCode);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LTA.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LTA toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LTA)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LTAImpl ltaImpl = new LTAImpl();

		ltaImpl.setLtaId(getLtaId());
		ltaImpl.setLtaName(getLtaName());
		ltaImpl.setZipCode(getZipCode());

		ltaImpl.resetOriginalValues();

		return ltaImpl;
	}

	@Override
	public int compareTo(LTA lta) {
		int value = 0;

		value = getLtaName().compareTo(lta.getLtaName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LTA)) {
			return false;
		}

		LTA lta = (LTA)obj;

		long primaryKey = lta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LTAModelImpl ltaModelImpl = this;

		ltaModelImpl._originalZipCode = ltaModelImpl._zipCode;

		ltaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LTA> toCacheModel() {
		LTACacheModel ltaCacheModel = new LTACacheModel();

		ltaCacheModel.ltaId = getLtaId();

		ltaCacheModel.ltaName = getLtaName();

		String ltaName = ltaCacheModel.ltaName;

		if ((ltaName != null) && (ltaName.length() == 0)) {
			ltaCacheModel.ltaName = null;
		}

		ltaCacheModel.zipCode = getZipCode();

		String zipCode = ltaCacheModel.zipCode;

		if ((zipCode != null) && (zipCode.length() == 0)) {
			ltaCacheModel.zipCode = null;
		}

		return ltaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{ltaId=");
		sb.append(getLtaId());
		sb.append(", ltaName=");
		sb.append(getLtaName());
		sb.append(", zipCode=");
		sb.append(getZipCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("contact.manager.service.model.LTA");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ltaId</column-name><column-value><![CDATA[");
		sb.append(getLtaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ltaName</column-name><column-value><![CDATA[");
		sb.append(getLtaName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zipCode</column-name><column-value><![CDATA[");
		sb.append(getZipCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LTA.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LTA.class
		};
	private long _ltaId;
	private String _ltaName;
	private String _zipCode;
	private String _originalZipCode;
	private long _columnBitmask;
	private LTA _escapedModel;
}