/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import contact.manager.service.model.Muni;
import contact.manager.service.model.MuniModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Muni service. Represents a row in the &quot;contactmanager_Muni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MuniModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MuniImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MuniImpl
 * @see Muni
 * @see MuniModel
 * @generated
 */
@ProviderType
public class MuniModelImpl extends BaseModelImpl<Muni> implements MuniModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a muni model instance should use the {@link Muni} interface instead.
	 */
	public static final String TABLE_NAME = "contactmanager_Muni";
	public static final Object[][] TABLE_COLUMNS = {
			{ "muniId", Types.BIGINT },
			{ "muniName", Types.VARCHAR },
			{ "zipCode", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("muniId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("muniName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zipCode", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table contactmanager_Muni (muniId LONG not null primary key,muniName VARCHAR(75) null,zipCode VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table contactmanager_Muni";
	public static final String ORDER_BY_JPQL = " ORDER BY muni.muniName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY contactmanager_Muni.muniName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.contact.manager.service.model.Muni"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(contact.manager.service.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.contact.manager.service.model.Muni"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(contact.manager.service.service.util.ServiceProps.get(
				"lock.expiration.time.contact.manager.service.model.Muni"));

	public MuniModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _muniId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMuniId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _muniId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Muni.class;
	}

	@Override
	public String getModelClassName() {
		return Muni.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("muniId", getMuniId());
		attributes.put("muniName", getMuniName());
		attributes.put("zipCode", getZipCode());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long muniId = (Long)attributes.get("muniId");

		if (muniId != null) {
			setMuniId(muniId);
		}

		String muniName = (String)attributes.get("muniName");

		if (muniName != null) {
			setMuniName(muniName);
		}

		String zipCode = (String)attributes.get("zipCode");

		if (zipCode != null) {
			setZipCode(zipCode);
		}
	}

	@Override
	public long getMuniId() {
		return _muniId;
	}

	@Override
	public void setMuniId(long muniId) {
		_muniId = muniId;
	}

	@Override
	public String getMuniName() {
		if (_muniName == null) {
			return StringPool.BLANK;
		}
		else {
			return _muniName;
		}
	}

	@Override
	public void setMuniName(String muniName) {
		_muniName = muniName;
	}

	@Override
	public String getZipCode() {
		if (_zipCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _zipCode;
		}
	}

	@Override
	public void setZipCode(String zipCode) {
		_zipCode = zipCode;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Muni.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Muni toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Muni)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MuniImpl muniImpl = new MuniImpl();

		muniImpl.setMuniId(getMuniId());
		muniImpl.setMuniName(getMuniName());
		muniImpl.setZipCode(getZipCode());

		muniImpl.resetOriginalValues();

		return muniImpl;
	}

	@Override
	public int compareTo(Muni muni) {
		int value = 0;

		value = getMuniName().compareTo(muni.getMuniName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Muni)) {
			return false;
		}

		Muni muni = (Muni)obj;

		long primaryKey = muni.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Muni> toCacheModel() {
		MuniCacheModel muniCacheModel = new MuniCacheModel();

		muniCacheModel.muniId = getMuniId();

		muniCacheModel.muniName = getMuniName();

		String muniName = muniCacheModel.muniName;

		if ((muniName != null) && (muniName.length() == 0)) {
			muniCacheModel.muniName = null;
		}

		muniCacheModel.zipCode = getZipCode();

		String zipCode = muniCacheModel.zipCode;

		if ((zipCode != null) && (zipCode.length() == 0)) {
			muniCacheModel.zipCode = null;
		}

		return muniCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{muniId=");
		sb.append(getMuniId());
		sb.append(", muniName=");
		sb.append(getMuniName());
		sb.append(", zipCode=");
		sb.append(getZipCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("contact.manager.service.model.Muni");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>muniId</column-name><column-value><![CDATA[");
		sb.append(getMuniId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>muniName</column-name><column-value><![CDATA[");
		sb.append(getMuniName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zipCode</column-name><column-value><![CDATA[");
		sb.append(getZipCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Muni.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Muni.class
		};
	private long _muniId;
	private String _muniName;
	private String _zipCode;
	private Muni _escapedModel;
}