/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CCA service. Represents a row in the &quot;contactmanager_CCA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link contact.manager.service.model.impl.CCAModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link contact.manager.service.model.impl.CCAImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CCA
 * @see contact.manager.service.model.impl.CCAImpl
 * @see contact.manager.service.model.impl.CCAModelImpl
 * @generated
 */
@ProviderType
public interface CCAModel extends BaseModel<CCA> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cca model instance should use the {@link CCA} interface instead.
	 */

	/**
	 * Returns the primary key of this cca.
	 *
	 * @return the primary key of this cca
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cca.
	 *
	 * @param primaryKey the primary key of this cca
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cca ID of this cca.
	 *
	 * @return the cca ID of this cca
	 */
	public long getCcaId();

	/**
	 * Sets the cca ID of this cca.
	 *
	 * @param ccaId the cca ID of this cca
	 */
	public void setCcaId(long ccaId);

	/**
	 * Returns the cca name of this cca.
	 *
	 * @return the cca name of this cca
	 */
	@AutoEscape
	public String getCcaName();

	/**
	 * Sets the cca name of this cca.
	 *
	 * @param ccaName the cca name of this cca
	 */
	public void setCcaName(String ccaName);

	/**
	 * Returns the zip code of this cca.
	 *
	 * @return the zip code of this cca
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this cca.
	 *
	 * @param zipCode the zip code of this cca
	 */
	public void setZipCode(String zipCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(contact.manager.service.model.CCA cca);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.service.model.CCA> toCacheModel();

	@Override
	public contact.manager.service.model.CCA toEscapedModel();

	@Override
	public contact.manager.service.model.CCA toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}