/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Chi_Ward service. Represents a row in the &quot;contactmanager_Chi_Ward&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link contact.manager.service.model.impl.Chi_WardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link contact.manager.service.model.impl.Chi_WardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Chi_Ward
 * @see contact.manager.service.model.impl.Chi_WardImpl
 * @see contact.manager.service.model.impl.Chi_WardModelImpl
 * @generated
 */
@ProviderType
public interface Chi_WardModel extends BaseModel<Chi_Ward> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chi_ ward model instance should use the {@link Chi_Ward} interface instead.
	 */

	/**
	 * Returns the primary key of this chi_ ward.
	 *
	 * @return the primary key of this chi_ ward
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chi_ ward.
	 *
	 * @param primaryKey the primary key of this chi_ ward
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the chi ward ID of this chi_ ward.
	 *
	 * @return the chi ward ID of this chi_ ward
	 */
	public long getChiWardId();

	/**
	 * Sets the chi ward ID of this chi_ ward.
	 *
	 * @param chiWardId the chi ward ID of this chi_ ward
	 */
	public void setChiWardId(long chiWardId);

	/**
	 * Returns the chi ward name of this chi_ ward.
	 *
	 * @return the chi ward name of this chi_ ward
	 */
	@AutoEscape
	public String getChiWardName();

	/**
	 * Sets the chi ward name of this chi_ ward.
	 *
	 * @param chiWardName the chi ward name of this chi_ ward
	 */
	public void setChiWardName(String chiWardName);

	/**
	 * Returns the zip code of this chi_ ward.
	 *
	 * @return the zip code of this chi_ ward
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this chi_ ward.
	 *
	 * @param zipCode the zip code of this chi_ ward
	 */
	public void setZipCode(String zipCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(contact.manager.service.model.Chi_Ward chi_Ward);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.service.model.Chi_Ward> toCacheModel();

	@Override
	public contact.manager.service.model.Chi_Ward toEscapedModel();

	@Override
	public contact.manager.service.model.Chi_Ward toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}