/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CmapTag service. Represents a row in the &quot;contactmanager_CmapTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link contact.manager.service.model.impl.CmapTagModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link contact.manager.service.model.impl.CmapTagImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CmapTag
 * @see contact.manager.service.model.impl.CmapTagImpl
 * @see contact.manager.service.model.impl.CmapTagModelImpl
 * @generated
 */
@ProviderType
public interface CmapTagModel extends BaseModel<CmapTag> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cmap tag model instance should use the {@link CmapTag} interface instead.
	 */

	/**
	 * Returns the primary key of this cmap tag.
	 *
	 * @return the primary key of this cmap tag
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cmap tag.
	 *
	 * @param primaryKey the primary key of this cmap tag
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tag ID of this cmap tag.
	 *
	 * @return the tag ID of this cmap tag
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this cmap tag.
	 *
	 * @param tagId the tag ID of this cmap tag
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the tag name of this cmap tag.
	 *
	 * @return the tag name of this cmap tag
	 */
	@AutoEscape
	public String getTagName();

	/**
	 * Sets the tag name of this cmap tag.
	 *
	 * @param tagName the tag name of this cmap tag
	 */
	public void setTagName(String tagName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(contact.manager.service.model.CmapTag cmapTag);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.service.model.CmapTag> toCacheModel();

	@Override
	public contact.manager.service.model.CmapTag toEscapedModel();

	@Override
	public contact.manager.service.model.CmapTag toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}