/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CmapSubGroup service. Represents a row in the &quot;contactmanager_CmapSubGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link contact.manager.service.model.impl.CmapSubGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link contact.manager.service.model.impl.CmapSubGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CmapSubGroup
 * @see contact.manager.service.model.impl.CmapSubGroupImpl
 * @see contact.manager.service.model.impl.CmapSubGroupModelImpl
 * @generated
 */
@ProviderType
public interface CmapSubGroupModel extends BaseModel<CmapSubGroup> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cmap sub group model instance should use the {@link CmapSubGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this cmap sub group.
	 *
	 * @return the primary key of this cmap sub group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cmap sub group.
	 *
	 * @param primaryKey the primary key of this cmap sub group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sub group ID of this cmap sub group.
	 *
	 * @return the sub group ID of this cmap sub group
	 */
	public long getSubGroupId();

	/**
	 * Sets the sub group ID of this cmap sub group.
	 *
	 * @param subGroupId the sub group ID of this cmap sub group
	 */
	public void setSubGroupId(long subGroupId);

	/**
	 * Returns the sub group name of this cmap sub group.
	 *
	 * @return the sub group name of this cmap sub group
	 */
	@AutoEscape
	public String getSubGroupName();

	/**
	 * Sets the sub group name of this cmap sub group.
	 *
	 * @param subGroupName the sub group name of this cmap sub group
	 */
	public void setSubGroupName(String subGroupName);

	/**
	 * Returns the group ID of this cmap sub group.
	 *
	 * @return the group ID of this cmap sub group
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this cmap sub group.
	 *
	 * @param groupId the group ID of this cmap sub group
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this cmap sub group.
	 *
	 * @return the create date of this cmap sub group
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cmap sub group.
	 *
	 * @param createDate the create date of this cmap sub group
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cmap sub group.
	 *
	 * @return the modified date of this cmap sub group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cmap sub group.
	 *
	 * @param modifiedDate the modified date of this cmap sub group
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		contact.manager.service.model.CmapSubGroup cmapSubGroup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.service.model.CmapSubGroup> toCacheModel();

	@Override
	public contact.manager.service.model.CmapSubGroup toEscapedModel();

	@Override
	public contact.manager.service.model.CmapSubGroup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}