/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LTA service. Represents a row in the &quot;contactmanager_LTA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link contact.manager.service.model.impl.LTAModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link contact.manager.service.model.impl.LTAImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LTA
 * @see contact.manager.service.model.impl.LTAImpl
 * @see contact.manager.service.model.impl.LTAModelImpl
 * @generated
 */
@ProviderType
public interface LTAModel extends BaseModel<LTA> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lta model instance should use the {@link LTA} interface instead.
	 */

	/**
	 * Returns the primary key of this lta.
	 *
	 * @return the primary key of this lta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lta.
	 *
	 * @param primaryKey the primary key of this lta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lta ID of this lta.
	 *
	 * @return the lta ID of this lta
	 */
	public long getLtaId();

	/**
	 * Sets the lta ID of this lta.
	 *
	 * @param ltaId the lta ID of this lta
	 */
	public void setLtaId(long ltaId);

	/**
	 * Returns the lta name of this lta.
	 *
	 * @return the lta name of this lta
	 */
	@AutoEscape
	public String getLtaName();

	/**
	 * Sets the lta name of this lta.
	 *
	 * @param ltaName the lta name of this lta
	 */
	public void setLtaName(String ltaName);

	/**
	 * Returns the zip code of this lta.
	 *
	 * @return the zip code of this lta
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this lta.
	 *
	 * @param zipCode the zip code of this lta
	 */
	public void setZipCode(String zipCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(contact.manager.service.model.LTA lta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.service.model.LTA> toCacheModel();

	@Override
	public contact.manager.service.model.LTA toEscapedModel();

	@Override
	public contact.manager.service.model.LTA toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}