/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Note service. Represents a row in the &quot;contactmanager_Note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link contact.manager.service.model.impl.NoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link contact.manager.service.model.impl.NoteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Note
 * @see contact.manager.service.model.impl.NoteImpl
 * @see contact.manager.service.model.impl.NoteModelImpl
 * @generated
 */
@ProviderType
public interface NoteModel extends BaseModel<Note> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a note model instance should use the {@link Note} interface instead.
	 */

	/**
	 * Returns the primary key of this note.
	 *
	 * @return the primary key of this note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this note.
	 *
	 * @param primaryKey the primary key of this note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this note.
	 *
	 * @return the ID of this note
	 */
	public long getId();

	/**
	 * Sets the ID of this note.
	 *
	 * @param id the ID of this note
	 */
	public void setId(long id);

	/**
	 * Returns the contact ID of this note.
	 *
	 * @return the contact ID of this note
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this note.
	 *
	 * @param contactId the contact ID of this note
	 */
	public void setContactId(long contactId);

	/**
	 * Returns the user ID of this note.
	 *
	 * @return the user ID of this note
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this note.
	 *
	 * @param userId the user ID of this note
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this note.
	 *
	 * @return the user uuid of this note
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this note.
	 *
	 * @param userUuid the user uuid of this note
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the note of this note.
	 *
	 * @return the note of this note
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this note.
	 *
	 * @param note the note of this note
	 */
	public void setNote(String note);

	/**
	 * Returns the create date of this note.
	 *
	 * @return the create date of this note
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this note.
	 *
	 * @param createDate the create date of this note
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this note.
	 *
	 * @return the modified date of this note
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this note.
	 *
	 * @param modifiedDate the modified date of this note
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(contact.manager.service.model.Note note);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.service.model.Note> toCacheModel();

	@Override
	public contact.manager.service.model.Note toEscapedModel();

	@Override
	public contact.manager.service.model.Note toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}