/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package contact.manager.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the US_Rep service. Represents a row in the &quot;contactmanager_US_Rep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link contact.manager.service.model.impl.US_RepModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link contact.manager.service.model.impl.US_RepImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see US_Rep
 * @see contact.manager.service.model.impl.US_RepImpl
 * @see contact.manager.service.model.impl.US_RepModelImpl
 * @generated
 */
@ProviderType
public interface US_RepModel extends BaseModel<US_Rep> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a us_ rep model instance should use the {@link US_Rep} interface instead.
	 */

	/**
	 * Returns the primary key of this us_ rep.
	 *
	 * @return the primary key of this us_ rep
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this us_ rep.
	 *
	 * @param primaryKey the primary key of this us_ rep
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the us rep ID of this us_ rep.
	 *
	 * @return the us rep ID of this us_ rep
	 */
	public long getUsRepId();

	/**
	 * Sets the us rep ID of this us_ rep.
	 *
	 * @param usRepId the us rep ID of this us_ rep
	 */
	public void setUsRepId(long usRepId);

	/**
	 * Returns the us rep number of this us_ rep.
	 *
	 * @return the us rep number of this us_ rep
	 */
	@AutoEscape
	public String getUsRepNumber();

	/**
	 * Sets the us rep number of this us_ rep.
	 *
	 * @param usRepNumber the us rep number of this us_ rep
	 */
	public void setUsRepNumber(String usRepNumber);

	/**
	 * Returns the us rep name of this us_ rep.
	 *
	 * @return the us rep name of this us_ rep
	 */
	@AutoEscape
	public String getUsRepName();

	/**
	 * Sets the us rep name of this us_ rep.
	 *
	 * @param usRepName the us rep name of this us_ rep
	 */
	public void setUsRepName(String usRepName);

	/**
	 * Returns the zip code of this us_ rep.
	 *
	 * @return the zip code of this us_ rep
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this us_ rep.
	 *
	 * @param zipCode the zip code of this us_ rep
	 */
	public void setZipCode(String zipCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(contact.manager.service.model.US_Rep us_Rep);

	@Override
	public int hashCode();

	@Override
	public CacheModel<contact.manager.service.model.US_Rep> toCacheModel();

	@Override
	public contact.manager.service.model.US_Rep toEscapedModel();

	@Override
	public contact.manager.service.model.US_Rep toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}