/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ucc.portal.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import ucc.portal.model.UccPeopleAddress;

import ucc.portal.service.UccPeopleAddressLocalService;
import ucc.portal.service.persistence.CExtChurchFinancesIncomeOtherPersistence;
import ucc.portal.service.persistence.CExtHistoricalInformationStaffingPersistence;
import ucc.portal.service.persistence.CExtOrganizationPersistence;
import ucc.portal.service.persistence.CExtParticipationOtherPersistence;
import ucc.portal.service.persistence.CExtParticipationPersistence;
import ucc.portal.service.persistence.CExtRealEstateCampaignPersistence;
import ucc.portal.service.persistence.CExtStaffingChurchPersistence;
import ucc.portal.service.persistence.CExtStaffingCongregationPersistence;
import ucc.portal.service.persistence.ExtContinuingEducationPersistence;
import ucc.portal.service.persistence.ExtDownloadLogPersistence;
import ucc.portal.service.persistence.ExtFormalEducationPersistence;
import ucc.portal.service.persistence.ExtKeyAccomplishmentPersistence;
import ucc.portal.service.persistence.ExtReferencePersistence;
import ucc.portal.service.persistence.ExtRegionalEducationPersistence;
import ucc.portal.service.persistence.ExtValidationPersistence;
import ucc.portal.service.persistence.ExtVocationalHistoryPersistence;
import ucc.portal.service.persistence.UccAssociationPersistence;
import ucc.portal.service.persistence.UccConferencePersistence;
import ucc.portal.service.persistence.UccPeopleAddressPersistence;
import ucc.portal.service.persistence.UccPeopleChurchStandingPersistence;
import ucc.portal.service.persistence.UccPeoplePersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the ucc people address local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link ucc.portal.service.impl.UccPeopleAddressLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ucc.portal.service.impl.UccPeopleAddressLocalServiceImpl
 * @see ucc.portal.service.UccPeopleAddressLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class UccPeopleAddressLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements UccPeopleAddressLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link ucc.portal.service.UccPeopleAddressLocalServiceUtil} to access the ucc people address local service.
	 */

	/**
	 * Adds the ucc people address to the database. Also notifies the appropriate model listeners.
	 *
	 * @param uccPeopleAddress the ucc people address
	 * @return the ucc people address that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UccPeopleAddress addUccPeopleAddress(
		UccPeopleAddress uccPeopleAddress) {
		uccPeopleAddress.setNew(true);

		return uccPeopleAddressPersistence.update(uccPeopleAddress);
	}

	/**
	 * Creates a new ucc people address with the primary key. Does not add the ucc people address to the database.
	 *
	 * @param uccPeopleAddressId the primary key for the new ucc people address
	 * @return the new ucc people address
	 */
	@Override
	@Transactional(enabled = false)
	public UccPeopleAddress createUccPeopleAddress(int uccPeopleAddressId) {
		return uccPeopleAddressPersistence.create(uccPeopleAddressId);
	}

	/**
	 * Deletes the ucc people address with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param uccPeopleAddressId the primary key of the ucc people address
	 * @return the ucc people address that was removed
	 * @throws PortalException if a ucc people address with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UccPeopleAddress deleteUccPeopleAddress(int uccPeopleAddressId)
		throws PortalException {
		return uccPeopleAddressPersistence.remove(uccPeopleAddressId);
	}

	/**
	 * Deletes the ucc people address from the database. Also notifies the appropriate model listeners.
	 *
	 * @param uccPeopleAddress the ucc people address
	 * @return the ucc people address that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UccPeopleAddress deleteUccPeopleAddress(
		UccPeopleAddress uccPeopleAddress) {
		return uccPeopleAddressPersistence.remove(uccPeopleAddress);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(UccPeopleAddress.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return uccPeopleAddressPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link ucc.portal.model.impl.UccPeopleAddressModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return uccPeopleAddressPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link ucc.portal.model.impl.UccPeopleAddressModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return uccPeopleAddressPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return uccPeopleAddressPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return uccPeopleAddressPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public UccPeopleAddress fetchUccPeopleAddress(int uccPeopleAddressId) {
		return uccPeopleAddressPersistence.fetchByPrimaryKey(uccPeopleAddressId);
	}

	/**
	 * Returns the ucc people address with the primary key.
	 *
	 * @param uccPeopleAddressId the primary key of the ucc people address
	 * @return the ucc people address
	 * @throws PortalException if a ucc people address with the primary key could not be found
	 */
	@Override
	public UccPeopleAddress getUccPeopleAddress(int uccPeopleAddressId)
		throws PortalException {
		return uccPeopleAddressPersistence.findByPrimaryKey(uccPeopleAddressId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(uccPeopleAddressLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UccPeopleAddress.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("uccPeopleAddressId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(uccPeopleAddressLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(UccPeopleAddress.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"uccPeopleAddressId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(uccPeopleAddressLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UccPeopleAddress.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("uccPeopleAddressId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return uccPeopleAddressLocalService.deleteUccPeopleAddress((UccPeopleAddress)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return uccPeopleAddressPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the ucc people addresses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link ucc.portal.model.impl.UccPeopleAddressModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of ucc people addresses
	 * @param end the upper bound of the range of ucc people addresses (not inclusive)
	 * @return the range of ucc people addresses
	 */
	@Override
	public List<UccPeopleAddress> getUccPeopleAddresses(int start, int end) {
		return uccPeopleAddressPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of ucc people addresses.
	 *
	 * @return the number of ucc people addresses
	 */
	@Override
	public int getUccPeopleAddressesCount() {
		return uccPeopleAddressPersistence.countAll();
	}

	/**
	 * Updates the ucc people address in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param uccPeopleAddress the ucc people address
	 * @return the ucc people address that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UccPeopleAddress updateUccPeopleAddress(
		UccPeopleAddress uccPeopleAddress) {
		return uccPeopleAddressPersistence.update(uccPeopleAddress);
	}

	/**
	 * Returns the c ext church finances income other local service.
	 *
	 * @return the c ext church finances income other local service
	 */
	public ucc.portal.service.CExtChurchFinancesIncomeOtherLocalService getCExtChurchFinancesIncomeOtherLocalService() {
		return cExtChurchFinancesIncomeOtherLocalService;
	}

	/**
	 * Sets the c ext church finances income other local service.
	 *
	 * @param cExtChurchFinancesIncomeOtherLocalService the c ext church finances income other local service
	 */
	public void setCExtChurchFinancesIncomeOtherLocalService(
		ucc.portal.service.CExtChurchFinancesIncomeOtherLocalService cExtChurchFinancesIncomeOtherLocalService) {
		this.cExtChurchFinancesIncomeOtherLocalService = cExtChurchFinancesIncomeOtherLocalService;
	}

	/**
	 * Returns the c ext church finances income other persistence.
	 *
	 * @return the c ext church finances income other persistence
	 */
	public CExtChurchFinancesIncomeOtherPersistence getCExtChurchFinancesIncomeOtherPersistence() {
		return cExtChurchFinancesIncomeOtherPersistence;
	}

	/**
	 * Sets the c ext church finances income other persistence.
	 *
	 * @param cExtChurchFinancesIncomeOtherPersistence the c ext church finances income other persistence
	 */
	public void setCExtChurchFinancesIncomeOtherPersistence(
		CExtChurchFinancesIncomeOtherPersistence cExtChurchFinancesIncomeOtherPersistence) {
		this.cExtChurchFinancesIncomeOtherPersistence = cExtChurchFinancesIncomeOtherPersistence;
	}

	/**
	 * Returns the c ext historical information staffing local service.
	 *
	 * @return the c ext historical information staffing local service
	 */
	public ucc.portal.service.CExtHistoricalInformationStaffingLocalService getCExtHistoricalInformationStaffingLocalService() {
		return cExtHistoricalInformationStaffingLocalService;
	}

	/**
	 * Sets the c ext historical information staffing local service.
	 *
	 * @param cExtHistoricalInformationStaffingLocalService the c ext historical information staffing local service
	 */
	public void setCExtHistoricalInformationStaffingLocalService(
		ucc.portal.service.CExtHistoricalInformationStaffingLocalService cExtHistoricalInformationStaffingLocalService) {
		this.cExtHistoricalInformationStaffingLocalService = cExtHistoricalInformationStaffingLocalService;
	}

	/**
	 * Returns the c ext historical information staffing persistence.
	 *
	 * @return the c ext historical information staffing persistence
	 */
	public CExtHistoricalInformationStaffingPersistence getCExtHistoricalInformationStaffingPersistence() {
		return cExtHistoricalInformationStaffingPersistence;
	}

	/**
	 * Sets the c ext historical information staffing persistence.
	 *
	 * @param cExtHistoricalInformationStaffingPersistence the c ext historical information staffing persistence
	 */
	public void setCExtHistoricalInformationStaffingPersistence(
		CExtHistoricalInformationStaffingPersistence cExtHistoricalInformationStaffingPersistence) {
		this.cExtHistoricalInformationStaffingPersistence = cExtHistoricalInformationStaffingPersistence;
	}

	/**
	 * Returns the c ext organization local service.
	 *
	 * @return the c ext organization local service
	 */
	public ucc.portal.service.CExtOrganizationLocalService getCExtOrganizationLocalService() {
		return cExtOrganizationLocalService;
	}

	/**
	 * Sets the c ext organization local service.
	 *
	 * @param cExtOrganizationLocalService the c ext organization local service
	 */
	public void setCExtOrganizationLocalService(
		ucc.portal.service.CExtOrganizationLocalService cExtOrganizationLocalService) {
		this.cExtOrganizationLocalService = cExtOrganizationLocalService;
	}

	/**
	 * Returns the c ext organization persistence.
	 *
	 * @return the c ext organization persistence
	 */
	public CExtOrganizationPersistence getCExtOrganizationPersistence() {
		return cExtOrganizationPersistence;
	}

	/**
	 * Sets the c ext organization persistence.
	 *
	 * @param cExtOrganizationPersistence the c ext organization persistence
	 */
	public void setCExtOrganizationPersistence(
		CExtOrganizationPersistence cExtOrganizationPersistence) {
		this.cExtOrganizationPersistence = cExtOrganizationPersistence;
	}

	/**
	 * Returns the c ext participation local service.
	 *
	 * @return the c ext participation local service
	 */
	public ucc.portal.service.CExtParticipationLocalService getCExtParticipationLocalService() {
		return cExtParticipationLocalService;
	}

	/**
	 * Sets the c ext participation local service.
	 *
	 * @param cExtParticipationLocalService the c ext participation local service
	 */
	public void setCExtParticipationLocalService(
		ucc.portal.service.CExtParticipationLocalService cExtParticipationLocalService) {
		this.cExtParticipationLocalService = cExtParticipationLocalService;
	}

	/**
	 * Returns the c ext participation persistence.
	 *
	 * @return the c ext participation persistence
	 */
	public CExtParticipationPersistence getCExtParticipationPersistence() {
		return cExtParticipationPersistence;
	}

	/**
	 * Sets the c ext participation persistence.
	 *
	 * @param cExtParticipationPersistence the c ext participation persistence
	 */
	public void setCExtParticipationPersistence(
		CExtParticipationPersistence cExtParticipationPersistence) {
		this.cExtParticipationPersistence = cExtParticipationPersistence;
	}

	/**
	 * Returns the c ext participation other local service.
	 *
	 * @return the c ext participation other local service
	 */
	public ucc.portal.service.CExtParticipationOtherLocalService getCExtParticipationOtherLocalService() {
		return cExtParticipationOtherLocalService;
	}

	/**
	 * Sets the c ext participation other local service.
	 *
	 * @param cExtParticipationOtherLocalService the c ext participation other local service
	 */
	public void setCExtParticipationOtherLocalService(
		ucc.portal.service.CExtParticipationOtherLocalService cExtParticipationOtherLocalService) {
		this.cExtParticipationOtherLocalService = cExtParticipationOtherLocalService;
	}

	/**
	 * Returns the c ext participation other persistence.
	 *
	 * @return the c ext participation other persistence
	 */
	public CExtParticipationOtherPersistence getCExtParticipationOtherPersistence() {
		return cExtParticipationOtherPersistence;
	}

	/**
	 * Sets the c ext participation other persistence.
	 *
	 * @param cExtParticipationOtherPersistence the c ext participation other persistence
	 */
	public void setCExtParticipationOtherPersistence(
		CExtParticipationOtherPersistence cExtParticipationOtherPersistence) {
		this.cExtParticipationOtherPersistence = cExtParticipationOtherPersistence;
	}

	/**
	 * Returns the c ext real estate campaign local service.
	 *
	 * @return the c ext real estate campaign local service
	 */
	public ucc.portal.service.CExtRealEstateCampaignLocalService getCExtRealEstateCampaignLocalService() {
		return cExtRealEstateCampaignLocalService;
	}

	/**
	 * Sets the c ext real estate campaign local service.
	 *
	 * @param cExtRealEstateCampaignLocalService the c ext real estate campaign local service
	 */
	public void setCExtRealEstateCampaignLocalService(
		ucc.portal.service.CExtRealEstateCampaignLocalService cExtRealEstateCampaignLocalService) {
		this.cExtRealEstateCampaignLocalService = cExtRealEstateCampaignLocalService;
	}

	/**
	 * Returns the c ext real estate campaign persistence.
	 *
	 * @return the c ext real estate campaign persistence
	 */
	public CExtRealEstateCampaignPersistence getCExtRealEstateCampaignPersistence() {
		return cExtRealEstateCampaignPersistence;
	}

	/**
	 * Sets the c ext real estate campaign persistence.
	 *
	 * @param cExtRealEstateCampaignPersistence the c ext real estate campaign persistence
	 */
	public void setCExtRealEstateCampaignPersistence(
		CExtRealEstateCampaignPersistence cExtRealEstateCampaignPersistence) {
		this.cExtRealEstateCampaignPersistence = cExtRealEstateCampaignPersistence;
	}

	/**
	 * Returns the c ext staffing church local service.
	 *
	 * @return the c ext staffing church local service
	 */
	public ucc.portal.service.CExtStaffingChurchLocalService getCExtStaffingChurchLocalService() {
		return cExtStaffingChurchLocalService;
	}

	/**
	 * Sets the c ext staffing church local service.
	 *
	 * @param cExtStaffingChurchLocalService the c ext staffing church local service
	 */
	public void setCExtStaffingChurchLocalService(
		ucc.portal.service.CExtStaffingChurchLocalService cExtStaffingChurchLocalService) {
		this.cExtStaffingChurchLocalService = cExtStaffingChurchLocalService;
	}

	/**
	 * Returns the c ext staffing church persistence.
	 *
	 * @return the c ext staffing church persistence
	 */
	public CExtStaffingChurchPersistence getCExtStaffingChurchPersistence() {
		return cExtStaffingChurchPersistence;
	}

	/**
	 * Sets the c ext staffing church persistence.
	 *
	 * @param cExtStaffingChurchPersistence the c ext staffing church persistence
	 */
	public void setCExtStaffingChurchPersistence(
		CExtStaffingChurchPersistence cExtStaffingChurchPersistence) {
		this.cExtStaffingChurchPersistence = cExtStaffingChurchPersistence;
	}

	/**
	 * Returns the c ext staffing congregation local service.
	 *
	 * @return the c ext staffing congregation local service
	 */
	public ucc.portal.service.CExtStaffingCongregationLocalService getCExtStaffingCongregationLocalService() {
		return cExtStaffingCongregationLocalService;
	}

	/**
	 * Sets the c ext staffing congregation local service.
	 *
	 * @param cExtStaffingCongregationLocalService the c ext staffing congregation local service
	 */
	public void setCExtStaffingCongregationLocalService(
		ucc.portal.service.CExtStaffingCongregationLocalService cExtStaffingCongregationLocalService) {
		this.cExtStaffingCongregationLocalService = cExtStaffingCongregationLocalService;
	}

	/**
	 * Returns the c ext staffing congregation persistence.
	 *
	 * @return the c ext staffing congregation persistence
	 */
	public CExtStaffingCongregationPersistence getCExtStaffingCongregationPersistence() {
		return cExtStaffingCongregationPersistence;
	}

	/**
	 * Sets the c ext staffing congregation persistence.
	 *
	 * @param cExtStaffingCongregationPersistence the c ext staffing congregation persistence
	 */
	public void setCExtStaffingCongregationPersistence(
		CExtStaffingCongregationPersistence cExtStaffingCongregationPersistence) {
		this.cExtStaffingCongregationPersistence = cExtStaffingCongregationPersistence;
	}

	/**
	 * Returns the ext continuing education local service.
	 *
	 * @return the ext continuing education local service
	 */
	public ucc.portal.service.ExtContinuingEducationLocalService getExtContinuingEducationLocalService() {
		return extContinuingEducationLocalService;
	}

	/**
	 * Sets the ext continuing education local service.
	 *
	 * @param extContinuingEducationLocalService the ext continuing education local service
	 */
	public void setExtContinuingEducationLocalService(
		ucc.portal.service.ExtContinuingEducationLocalService extContinuingEducationLocalService) {
		this.extContinuingEducationLocalService = extContinuingEducationLocalService;
	}

	/**
	 * Returns the ext continuing education persistence.
	 *
	 * @return the ext continuing education persistence
	 */
	public ExtContinuingEducationPersistence getExtContinuingEducationPersistence() {
		return extContinuingEducationPersistence;
	}

	/**
	 * Sets the ext continuing education persistence.
	 *
	 * @param extContinuingEducationPersistence the ext continuing education persistence
	 */
	public void setExtContinuingEducationPersistence(
		ExtContinuingEducationPersistence extContinuingEducationPersistence) {
		this.extContinuingEducationPersistence = extContinuingEducationPersistence;
	}

	/**
	 * Returns the ext download log local service.
	 *
	 * @return the ext download log local service
	 */
	public ucc.portal.service.ExtDownloadLogLocalService getExtDownloadLogLocalService() {
		return extDownloadLogLocalService;
	}

	/**
	 * Sets the ext download log local service.
	 *
	 * @param extDownloadLogLocalService the ext download log local service
	 */
	public void setExtDownloadLogLocalService(
		ucc.portal.service.ExtDownloadLogLocalService extDownloadLogLocalService) {
		this.extDownloadLogLocalService = extDownloadLogLocalService;
	}

	/**
	 * Returns the ext download log persistence.
	 *
	 * @return the ext download log persistence
	 */
	public ExtDownloadLogPersistence getExtDownloadLogPersistence() {
		return extDownloadLogPersistence;
	}

	/**
	 * Sets the ext download log persistence.
	 *
	 * @param extDownloadLogPersistence the ext download log persistence
	 */
	public void setExtDownloadLogPersistence(
		ExtDownloadLogPersistence extDownloadLogPersistence) {
		this.extDownloadLogPersistence = extDownloadLogPersistence;
	}

	/**
	 * Returns the ext formal education local service.
	 *
	 * @return the ext formal education local service
	 */
	public ucc.portal.service.ExtFormalEducationLocalService getExtFormalEducationLocalService() {
		return extFormalEducationLocalService;
	}

	/**
	 * Sets the ext formal education local service.
	 *
	 * @param extFormalEducationLocalService the ext formal education local service
	 */
	public void setExtFormalEducationLocalService(
		ucc.portal.service.ExtFormalEducationLocalService extFormalEducationLocalService) {
		this.extFormalEducationLocalService = extFormalEducationLocalService;
	}

	/**
	 * Returns the ext formal education persistence.
	 *
	 * @return the ext formal education persistence
	 */
	public ExtFormalEducationPersistence getExtFormalEducationPersistence() {
		return extFormalEducationPersistence;
	}

	/**
	 * Sets the ext formal education persistence.
	 *
	 * @param extFormalEducationPersistence the ext formal education persistence
	 */
	public void setExtFormalEducationPersistence(
		ExtFormalEducationPersistence extFormalEducationPersistence) {
		this.extFormalEducationPersistence = extFormalEducationPersistence;
	}

	/**
	 * Returns the ext key accomplishment local service.
	 *
	 * @return the ext key accomplishment local service
	 */
	public ucc.portal.service.ExtKeyAccomplishmentLocalService getExtKeyAccomplishmentLocalService() {
		return extKeyAccomplishmentLocalService;
	}

	/**
	 * Sets the ext key accomplishment local service.
	 *
	 * @param extKeyAccomplishmentLocalService the ext key accomplishment local service
	 */
	public void setExtKeyAccomplishmentLocalService(
		ucc.portal.service.ExtKeyAccomplishmentLocalService extKeyAccomplishmentLocalService) {
		this.extKeyAccomplishmentLocalService = extKeyAccomplishmentLocalService;
	}

	/**
	 * Returns the ext key accomplishment persistence.
	 *
	 * @return the ext key accomplishment persistence
	 */
	public ExtKeyAccomplishmentPersistence getExtKeyAccomplishmentPersistence() {
		return extKeyAccomplishmentPersistence;
	}

	/**
	 * Sets the ext key accomplishment persistence.
	 *
	 * @param extKeyAccomplishmentPersistence the ext key accomplishment persistence
	 */
	public void setExtKeyAccomplishmentPersistence(
		ExtKeyAccomplishmentPersistence extKeyAccomplishmentPersistence) {
		this.extKeyAccomplishmentPersistence = extKeyAccomplishmentPersistence;
	}

	/**
	 * Returns the ext reference local service.
	 *
	 * @return the ext reference local service
	 */
	public ucc.portal.service.ExtReferenceLocalService getExtReferenceLocalService() {
		return extReferenceLocalService;
	}

	/**
	 * Sets the ext reference local service.
	 *
	 * @param extReferenceLocalService the ext reference local service
	 */
	public void setExtReferenceLocalService(
		ucc.portal.service.ExtReferenceLocalService extReferenceLocalService) {
		this.extReferenceLocalService = extReferenceLocalService;
	}

	/**
	 * Returns the ext reference persistence.
	 *
	 * @return the ext reference persistence
	 */
	public ExtReferencePersistence getExtReferencePersistence() {
		return extReferencePersistence;
	}

	/**
	 * Sets the ext reference persistence.
	 *
	 * @param extReferencePersistence the ext reference persistence
	 */
	public void setExtReferencePersistence(
		ExtReferencePersistence extReferencePersistence) {
		this.extReferencePersistence = extReferencePersistence;
	}

	/**
	 * Returns the ext regional education local service.
	 *
	 * @return the ext regional education local service
	 */
	public ucc.portal.service.ExtRegionalEducationLocalService getExtRegionalEducationLocalService() {
		return extRegionalEducationLocalService;
	}

	/**
	 * Sets the ext regional education local service.
	 *
	 * @param extRegionalEducationLocalService the ext regional education local service
	 */
	public void setExtRegionalEducationLocalService(
		ucc.portal.service.ExtRegionalEducationLocalService extRegionalEducationLocalService) {
		this.extRegionalEducationLocalService = extRegionalEducationLocalService;
	}

	/**
	 * Returns the ext regional education persistence.
	 *
	 * @return the ext regional education persistence
	 */
	public ExtRegionalEducationPersistence getExtRegionalEducationPersistence() {
		return extRegionalEducationPersistence;
	}

	/**
	 * Sets the ext regional education persistence.
	 *
	 * @param extRegionalEducationPersistence the ext regional education persistence
	 */
	public void setExtRegionalEducationPersistence(
		ExtRegionalEducationPersistence extRegionalEducationPersistence) {
		this.extRegionalEducationPersistence = extRegionalEducationPersistence;
	}

	/**
	 * Returns the ext validation local service.
	 *
	 * @return the ext validation local service
	 */
	public ucc.portal.service.ExtValidationLocalService getExtValidationLocalService() {
		return extValidationLocalService;
	}

	/**
	 * Sets the ext validation local service.
	 *
	 * @param extValidationLocalService the ext validation local service
	 */
	public void setExtValidationLocalService(
		ucc.portal.service.ExtValidationLocalService extValidationLocalService) {
		this.extValidationLocalService = extValidationLocalService;
	}

	/**
	 * Returns the ext validation persistence.
	 *
	 * @return the ext validation persistence
	 */
	public ExtValidationPersistence getExtValidationPersistence() {
		return extValidationPersistence;
	}

	/**
	 * Sets the ext validation persistence.
	 *
	 * @param extValidationPersistence the ext validation persistence
	 */
	public void setExtValidationPersistence(
		ExtValidationPersistence extValidationPersistence) {
		this.extValidationPersistence = extValidationPersistence;
	}

	/**
	 * Returns the ext vocational history local service.
	 *
	 * @return the ext vocational history local service
	 */
	public ucc.portal.service.ExtVocationalHistoryLocalService getExtVocationalHistoryLocalService() {
		return extVocationalHistoryLocalService;
	}

	/**
	 * Sets the ext vocational history local service.
	 *
	 * @param extVocationalHistoryLocalService the ext vocational history local service
	 */
	public void setExtVocationalHistoryLocalService(
		ucc.portal.service.ExtVocationalHistoryLocalService extVocationalHistoryLocalService) {
		this.extVocationalHistoryLocalService = extVocationalHistoryLocalService;
	}

	/**
	 * Returns the ext vocational history persistence.
	 *
	 * @return the ext vocational history persistence
	 */
	public ExtVocationalHistoryPersistence getExtVocationalHistoryPersistence() {
		return extVocationalHistoryPersistence;
	}

	/**
	 * Sets the ext vocational history persistence.
	 *
	 * @param extVocationalHistoryPersistence the ext vocational history persistence
	 */
	public void setExtVocationalHistoryPersistence(
		ExtVocationalHistoryPersistence extVocationalHistoryPersistence) {
		this.extVocationalHistoryPersistence = extVocationalHistoryPersistence;
	}

	/**
	 * Returns the ucc association local service.
	 *
	 * @return the ucc association local service
	 */
	public ucc.portal.service.UccAssociationLocalService getUccAssociationLocalService() {
		return uccAssociationLocalService;
	}

	/**
	 * Sets the ucc association local service.
	 *
	 * @param uccAssociationLocalService the ucc association local service
	 */
	public void setUccAssociationLocalService(
		ucc.portal.service.UccAssociationLocalService uccAssociationLocalService) {
		this.uccAssociationLocalService = uccAssociationLocalService;
	}

	/**
	 * Returns the ucc association persistence.
	 *
	 * @return the ucc association persistence
	 */
	public UccAssociationPersistence getUccAssociationPersistence() {
		return uccAssociationPersistence;
	}

	/**
	 * Sets the ucc association persistence.
	 *
	 * @param uccAssociationPersistence the ucc association persistence
	 */
	public void setUccAssociationPersistence(
		UccAssociationPersistence uccAssociationPersistence) {
		this.uccAssociationPersistence = uccAssociationPersistence;
	}

	/**
	 * Returns the ucc conference local service.
	 *
	 * @return the ucc conference local service
	 */
	public ucc.portal.service.UccConferenceLocalService getUccConferenceLocalService() {
		return uccConferenceLocalService;
	}

	/**
	 * Sets the ucc conference local service.
	 *
	 * @param uccConferenceLocalService the ucc conference local service
	 */
	public void setUccConferenceLocalService(
		ucc.portal.service.UccConferenceLocalService uccConferenceLocalService) {
		this.uccConferenceLocalService = uccConferenceLocalService;
	}

	/**
	 * Returns the ucc conference persistence.
	 *
	 * @return the ucc conference persistence
	 */
	public UccConferencePersistence getUccConferencePersistence() {
		return uccConferencePersistence;
	}

	/**
	 * Sets the ucc conference persistence.
	 *
	 * @param uccConferencePersistence the ucc conference persistence
	 */
	public void setUccConferencePersistence(
		UccConferencePersistence uccConferencePersistence) {
		this.uccConferencePersistence = uccConferencePersistence;
	}

	/**
	 * Returns the ucc people local service.
	 *
	 * @return the ucc people local service
	 */
	public ucc.portal.service.UccPeopleLocalService getUccPeopleLocalService() {
		return uccPeopleLocalService;
	}

	/**
	 * Sets the ucc people local service.
	 *
	 * @param uccPeopleLocalService the ucc people local service
	 */
	public void setUccPeopleLocalService(
		ucc.portal.service.UccPeopleLocalService uccPeopleLocalService) {
		this.uccPeopleLocalService = uccPeopleLocalService;
	}

	/**
	 * Returns the ucc people persistence.
	 *
	 * @return the ucc people persistence
	 */
	public UccPeoplePersistence getUccPeoplePersistence() {
		return uccPeoplePersistence;
	}

	/**
	 * Sets the ucc people persistence.
	 *
	 * @param uccPeoplePersistence the ucc people persistence
	 */
	public void setUccPeoplePersistence(
		UccPeoplePersistence uccPeoplePersistence) {
		this.uccPeoplePersistence = uccPeoplePersistence;
	}

	/**
	 * Returns the ucc people address local service.
	 *
	 * @return the ucc people address local service
	 */
	public UccPeopleAddressLocalService getUccPeopleAddressLocalService() {
		return uccPeopleAddressLocalService;
	}

	/**
	 * Sets the ucc people address local service.
	 *
	 * @param uccPeopleAddressLocalService the ucc people address local service
	 */
	public void setUccPeopleAddressLocalService(
		UccPeopleAddressLocalService uccPeopleAddressLocalService) {
		this.uccPeopleAddressLocalService = uccPeopleAddressLocalService;
	}

	/**
	 * Returns the ucc people address persistence.
	 *
	 * @return the ucc people address persistence
	 */
	public UccPeopleAddressPersistence getUccPeopleAddressPersistence() {
		return uccPeopleAddressPersistence;
	}

	/**
	 * Sets the ucc people address persistence.
	 *
	 * @param uccPeopleAddressPersistence the ucc people address persistence
	 */
	public void setUccPeopleAddressPersistence(
		UccPeopleAddressPersistence uccPeopleAddressPersistence) {
		this.uccPeopleAddressPersistence = uccPeopleAddressPersistence;
	}

	/**
	 * Returns the ucc people church standing local service.
	 *
	 * @return the ucc people church standing local service
	 */
	public ucc.portal.service.UccPeopleChurchStandingLocalService getUccPeopleChurchStandingLocalService() {
		return uccPeopleChurchStandingLocalService;
	}

	/**
	 * Sets the ucc people church standing local service.
	 *
	 * @param uccPeopleChurchStandingLocalService the ucc people church standing local service
	 */
	public void setUccPeopleChurchStandingLocalService(
		ucc.portal.service.UccPeopleChurchStandingLocalService uccPeopleChurchStandingLocalService) {
		this.uccPeopleChurchStandingLocalService = uccPeopleChurchStandingLocalService;
	}

	/**
	 * Returns the ucc people church standing persistence.
	 *
	 * @return the ucc people church standing persistence
	 */
	public UccPeopleChurchStandingPersistence getUccPeopleChurchStandingPersistence() {
		return uccPeopleChurchStandingPersistence;
	}

	/**
	 * Sets the ucc people church standing persistence.
	 *
	 * @param uccPeopleChurchStandingPersistence the ucc people church standing persistence
	 */
	public void setUccPeopleChurchStandingPersistence(
		UccPeopleChurchStandingPersistence uccPeopleChurchStandingPersistence) {
		this.uccPeopleChurchStandingPersistence = uccPeopleChurchStandingPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("ucc.portal.model.UccPeopleAddress",
			uccPeopleAddressLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"ucc.portal.model.UccPeopleAddress");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UccPeopleAddressLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UccPeopleAddress.class;
	}

	protected String getModelClassName() {
		return UccPeopleAddress.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = uccPeopleAddressPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ucc.portal.service.CExtChurchFinancesIncomeOtherLocalService.class)
	protected ucc.portal.service.CExtChurchFinancesIncomeOtherLocalService cExtChurchFinancesIncomeOtherLocalService;
	@BeanReference(type = CExtChurchFinancesIncomeOtherPersistence.class)
	protected CExtChurchFinancesIncomeOtherPersistence cExtChurchFinancesIncomeOtherPersistence;
	@BeanReference(type = ucc.portal.service.CExtHistoricalInformationStaffingLocalService.class)
	protected ucc.portal.service.CExtHistoricalInformationStaffingLocalService cExtHistoricalInformationStaffingLocalService;
	@BeanReference(type = CExtHistoricalInformationStaffingPersistence.class)
	protected CExtHistoricalInformationStaffingPersistence cExtHistoricalInformationStaffingPersistence;
	@BeanReference(type = ucc.portal.service.CExtOrganizationLocalService.class)
	protected ucc.portal.service.CExtOrganizationLocalService cExtOrganizationLocalService;
	@BeanReference(type = CExtOrganizationPersistence.class)
	protected CExtOrganizationPersistence cExtOrganizationPersistence;
	@BeanReference(type = ucc.portal.service.CExtParticipationLocalService.class)
	protected ucc.portal.service.CExtParticipationLocalService cExtParticipationLocalService;
	@BeanReference(type = CExtParticipationPersistence.class)
	protected CExtParticipationPersistence cExtParticipationPersistence;
	@BeanReference(type = ucc.portal.service.CExtParticipationOtherLocalService.class)
	protected ucc.portal.service.CExtParticipationOtherLocalService cExtParticipationOtherLocalService;
	@BeanReference(type = CExtParticipationOtherPersistence.class)
	protected CExtParticipationOtherPersistence cExtParticipationOtherPersistence;
	@BeanReference(type = ucc.portal.service.CExtRealEstateCampaignLocalService.class)
	protected ucc.portal.service.CExtRealEstateCampaignLocalService cExtRealEstateCampaignLocalService;
	@BeanReference(type = CExtRealEstateCampaignPersistence.class)
	protected CExtRealEstateCampaignPersistence cExtRealEstateCampaignPersistence;
	@BeanReference(type = ucc.portal.service.CExtStaffingChurchLocalService.class)
	protected ucc.portal.service.CExtStaffingChurchLocalService cExtStaffingChurchLocalService;
	@BeanReference(type = CExtStaffingChurchPersistence.class)
	protected CExtStaffingChurchPersistence cExtStaffingChurchPersistence;
	@BeanReference(type = ucc.portal.service.CExtStaffingCongregationLocalService.class)
	protected ucc.portal.service.CExtStaffingCongregationLocalService cExtStaffingCongregationLocalService;
	@BeanReference(type = CExtStaffingCongregationPersistence.class)
	protected CExtStaffingCongregationPersistence cExtStaffingCongregationPersistence;
	@BeanReference(type = ucc.portal.service.ExtContinuingEducationLocalService.class)
	protected ucc.portal.service.ExtContinuingEducationLocalService extContinuingEducationLocalService;
	@BeanReference(type = ExtContinuingEducationPersistence.class)
	protected ExtContinuingEducationPersistence extContinuingEducationPersistence;
	@BeanReference(type = ucc.portal.service.ExtDownloadLogLocalService.class)
	protected ucc.portal.service.ExtDownloadLogLocalService extDownloadLogLocalService;
	@BeanReference(type = ExtDownloadLogPersistence.class)
	protected ExtDownloadLogPersistence extDownloadLogPersistence;
	@BeanReference(type = ucc.portal.service.ExtFormalEducationLocalService.class)
	protected ucc.portal.service.ExtFormalEducationLocalService extFormalEducationLocalService;
	@BeanReference(type = ExtFormalEducationPersistence.class)
	protected ExtFormalEducationPersistence extFormalEducationPersistence;
	@BeanReference(type = ucc.portal.service.ExtKeyAccomplishmentLocalService.class)
	protected ucc.portal.service.ExtKeyAccomplishmentLocalService extKeyAccomplishmentLocalService;
	@BeanReference(type = ExtKeyAccomplishmentPersistence.class)
	protected ExtKeyAccomplishmentPersistence extKeyAccomplishmentPersistence;
	@BeanReference(type = ucc.portal.service.ExtReferenceLocalService.class)
	protected ucc.portal.service.ExtReferenceLocalService extReferenceLocalService;
	@BeanReference(type = ExtReferencePersistence.class)
	protected ExtReferencePersistence extReferencePersistence;
	@BeanReference(type = ucc.portal.service.ExtRegionalEducationLocalService.class)
	protected ucc.portal.service.ExtRegionalEducationLocalService extRegionalEducationLocalService;
	@BeanReference(type = ExtRegionalEducationPersistence.class)
	protected ExtRegionalEducationPersistence extRegionalEducationPersistence;
	@BeanReference(type = ucc.portal.service.ExtValidationLocalService.class)
	protected ucc.portal.service.ExtValidationLocalService extValidationLocalService;
	@BeanReference(type = ExtValidationPersistence.class)
	protected ExtValidationPersistence extValidationPersistence;
	@BeanReference(type = ucc.portal.service.ExtVocationalHistoryLocalService.class)
	protected ucc.portal.service.ExtVocationalHistoryLocalService extVocationalHistoryLocalService;
	@BeanReference(type = ExtVocationalHistoryPersistence.class)
	protected ExtVocationalHistoryPersistence extVocationalHistoryPersistence;
	@BeanReference(type = ucc.portal.service.UccAssociationLocalService.class)
	protected ucc.portal.service.UccAssociationLocalService uccAssociationLocalService;
	@BeanReference(type = UccAssociationPersistence.class)
	protected UccAssociationPersistence uccAssociationPersistence;
	@BeanReference(type = ucc.portal.service.UccConferenceLocalService.class)
	protected ucc.portal.service.UccConferenceLocalService uccConferenceLocalService;
	@BeanReference(type = UccConferencePersistence.class)
	protected UccConferencePersistence uccConferencePersistence;
	@BeanReference(type = ucc.portal.service.UccPeopleLocalService.class)
	protected ucc.portal.service.UccPeopleLocalService uccPeopleLocalService;
	@BeanReference(type = UccPeoplePersistence.class)
	protected UccPeoplePersistence uccPeoplePersistence;
	@BeanReference(type = UccPeopleAddressLocalService.class)
	protected UccPeopleAddressLocalService uccPeopleAddressLocalService;
	@BeanReference(type = UccPeopleAddressPersistence.class)
	protected UccPeopleAddressPersistence uccPeopleAddressPersistence;
	@BeanReference(type = ucc.portal.service.UccPeopleChurchStandingLocalService.class)
	protected ucc.portal.service.UccPeopleChurchStandingLocalService uccPeopleChurchStandingLocalService;
	@BeanReference(type = UccPeopleChurchStandingPersistence.class)
	protected UccPeopleChurchStandingPersistence uccPeopleChurchStandingPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}